// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :one

insert into audit_log (course_id, actor_id, entity, entity_id, action, before, after, trace_id)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
returning id, course_id, actor_id, entity, entity_id, action, before, after, trace_id, created_at
`

type InsertAuditLogParams struct {
	CourseID *uuid.UUID
	ActorID  *uuid.UUID
	Entity   string
	EntityID string
	Action   string
	Before   json.RawMessage
	After    json.RawMessage
	TraceID  *string
}

// `audit_log` chỉ-thêm: chỉ có INSERT (trigger chặn UPDATE/DELETE/TRUNCATE).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.CourseID,
		arg.ActorID,
		arg.Entity,
		arg.EntityID,
		arg.Action,
		arg.Before,
		arg.After,
		arg.TraceID,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ActorID,
		&i.Entity,
		&i.EntityID,
		&i.Action,
		&i.Before,
		&i.After,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}
