// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
select id, user_id, kind, token_hash, expires_at, used_at, revoked_at, created_by, created_at from auth_tokens where token_hash = $1
`

func (q *Queries) GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, tokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuthToken = `-- name: InsertAuthToken :one

insert into auth_tokens (user_id, kind, token_hash, expires_at, created_by)
values ($1, $2, $3, $4, $5)
returning id, user_id, kind, token_hash, expires_at, used_at, revoked_at, created_by, created_at
`

type InsertAuthTokenParams struct {
	UserID    uuid.UUID
	Kind      AuthTokenKind
	TokenHash string
	ExpiresAt time.Time
	CreatedBy *uuid.UUID
}

// Token một lần (SRS FEAT-account-security 5.3). CHỈ gói internal/auth được gọi các truy vấn này
// (TestOnlyAuthPackageTouchesTokenTables). Bản rõ không bao giờ vào DB: chỉ nhận sha256 hex.
func (q *Queries) InsertAuthToken(ctx context.Context, arg InsertAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, insertAuthToken,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeUnusedAuthTokens = `-- name: RevokeUnusedAuthTokens :execrows
update auth_tokens
set revoked_at = now()
where user_id = $1
  and kind = $2
  and used_at is null
  and revoked_at is null
`

type RevokeUnusedAuthTokensParams struct {
	UserID uuid.UUID
	Kind   AuthTokenKind
}

func (q *Queries) RevokeUnusedAuthTokens(ctx context.Context, arg RevokeUnusedAuthTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUnusedAuthTokens, arg.UserID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
