// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :one
update auth_tokens
set used_at = $1::timestamptz
where token_hash = $2
  and kind = $3
  and used_at is null
  and revoked_at is null
  and expires_at > $1::timestamptz
returning user_id
`

type ConsumeAuthTokenParams struct {
	Now       time.Time
	TokenHash string
	Kind      AuthTokenKind
}

// Nguyên tử: hai yêu cầu song song cùng token ⇒ đúng một dòng trả về.
func (q *Queries) ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeAuthToken, arg.Now, arg.TokenHash, arg.Kind)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getAuthSessionRevokedReason = `-- name: GetAuthSessionRevokedReason :one
select revoked_reason from auth_sessions where id = $1
`

func (q *Queries) GetAuthSessionRevokedReason(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getAuthSessionRevokedReason, id)
	var revoked_reason *string
	err := row.Scan(&revoked_reason)
	return revoked_reason, err
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
select id, user_id, kind, token_hash, expires_at, used_at, revoked_at, created_by, created_at from auth_tokens where token_hash = $1
`

func (q *Queries) GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, tokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuthSession = `-- name: InsertAuthSession :one

insert into auth_sessions (user_id, refresh_hash, user_agent, device_label, ip, created_at, last_used_at, expires_at, absolute_expires_at)
values (
    $1, $2, $3, $4, $5,
    $6, $6, $7, $8
)
returning id, user_id, refresh_hash, prev_refresh_hash, user_agent, device_label, ip, created_at, rotated_at, last_used_at, expires_at, absolute_expires_at, revoked_at, revoked_reason, updated_at
`

type InsertAuthSessionParams struct {
	UserID            uuid.UUID
	RefreshHash       string
	UserAgent         *string
	DeviceLabel       *string
	Ip                *netip.Addr
	Now               time.Time
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
}

// Phiên đăng nhập (SRS FEAT-account-security 5.2). Thời điểm do ứng dụng truyền vào (đồng hồ giả được trong test).
func (q *Queries) InsertAuthSession(ctx context.Context, arg InsertAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, insertAuthSession,
		arg.UserID,
		arg.RefreshHash,
		arg.UserAgent,
		arg.DeviceLabel,
		arg.Ip,
		arg.Now,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.PrevRefreshHash,
		&i.UserAgent,
		&i.DeviceLabel,
		&i.Ip,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuthToken = `-- name: InsertAuthToken :one

insert into auth_tokens (user_id, kind, token_hash, expires_at, created_by)
values ($1, $2, $3, $4, $5)
returning id, user_id, kind, token_hash, expires_at, used_at, revoked_at, created_by, created_at
`

type InsertAuthTokenParams struct {
	UserID    uuid.UUID
	Kind      AuthTokenKind
	TokenHash string
	ExpiresAt time.Time
	CreatedBy *uuid.UUID
}

// Token một lần (SRS FEAT-account-security 5.3). CHỈ gói internal/auth được gọi các truy vấn này
// (TestOnlyAuthPackageTouchesTokenTables). Bản rõ không bao giờ vào DB: chỉ nhận sha256 hex.
func (q *Queries) InsertAuthToken(ctx context.Context, arg InsertAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, insertAuthToken,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec
insert into login_attempts (email_hash, user_id, ip, user_agent, outcome, created_at)
values ($1, $2, $3, $4, $5, $6)
`

type InsertLoginAttemptParams struct {
	EmailHash string
	UserID    *uuid.UUID
	Ip        *netip.Addr
	UserAgent *string
	Outcome   LoginOutcome
	Now       time.Time
}

func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt,
		arg.EmailHash,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
		arg.Outcome,
		arg.Now,
	)
	return err
}

const insertPendingStudent = `-- name: InsertPendingStudent :one

insert into users (email, full_name, role, status, password_hash, student_code)
values ($1, $2, 'STUDENT', 'PENDING_VERIFICATION', $3, $4)
on conflict (email) do nothing
returning id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at
`

type InsertPendingStudentParams struct {
	Email        string
	FullName     string
	PasswordHash *string
	StudentCode  *string
}

// Đăng ký / xác minh email (US-P2-03). MSSV chỉ được GHI (InsertPendingStudent), không bao giờ nằm trong điều kiện nối lớp (SRS 4.2.5).
// Idempotent theo email: trùng (cả khi hai đăng ký đua nhau) ⇒ không có dòng nào trả về, không lỗi, giao dịch không bị huỷ.
func (q *Queries) InsertPendingStudent(ctx context.Context, arg InsertPendingStudentParams) (User, error) {
	row := q.db.QueryRow(ctx, insertPendingStudent,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.StudentCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestInviterName = `-- name: LatestInviterName :one
select u.full_name
from auth_tokens t
join users u on u.id = t.created_by
where t.user_id = $1 and t.kind = 'INVITE' and t.created_by is not null
order by t.created_at desc
limit 1
`

// Tên người đã phát lời mời gần nhất cho user (để gửi lại thư mời); không có ⇒ không dòng.
func (q *Queries) LatestInviterName(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, latestInviterName, userID)
	var full_name string
	err := row.Scan(&full_name)
	return full_name, err
}

const lockAuthSessionByRefresh = `-- name: LockAuthSessionByRefresh :one
select id, user_id, refresh_hash, prev_refresh_hash, user_agent, device_label, ip, created_at, rotated_at, last_used_at, expires_at, absolute_expires_at, revoked_at, revoked_reason, updated_at from auth_sessions
where refresh_hash = $1 or prev_refresh_hash = $1
for update
`

// Khoá hàng của phiên có refresh hiện tại HOẶC thế hệ trước; hai yêu cầu cùng phiên chạy tuần tự.
func (q *Queries) LockAuthSessionByRefresh(ctx context.Context, hash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, lockAuthSessionByRefresh, hash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.PrevRefreshHash,
		&i.UserAgent,
		&i.DeviceLabel,
		&i.Ip,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
update users
set email_verified_at = coalesce(email_verified_at, $1::timestamptz),
    status = case when status = 'PENDING_VERIFICATION' then 'ACTIVE'::user_status else status end
where id = $2
returning id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at
`

type MarkEmailVerifiedParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, arg.Now, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const promoteUnverifiedRosterEnrollments = `-- name: PromoteUnverifiedRosterEnrollments :execrows
update enrollments
set status = 'ACTIVE', previous_status = 'PENDING', warning = null, status_changed_at = $1::timestamptz, version = version + 1
where user_id = $2 and status = 'PENDING' and warning = 'EMAIL_UNVERIFIED'
`

type PromoteUnverifiedRosterEnrollmentsParams struct {
	Now    time.Time
	UserID uuid.UUID
}

// Email đã xác minh trùng email trong danh sách lớp ⇒ đẩy các enrollment PENDING (cảnh báo EMAIL_UNVERIFIED) thành ACTIVE.
func (q *Queries) PromoteUnverifiedRosterEnrollments(ctx context.Context, arg PromoteUnverifiedRosterEnrollmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteUnverifiedRosterEnrollments, arg.Now, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
update auth_sessions
set revoked_at = $1::timestamptz, revoked_reason = $2::text
where id = $3 and revoked_at is null
`

type RevokeAuthSessionParams struct {
	Now    time.Time
	Reason string
	ID     uuid.UUID
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.Now, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUnusedAuthTokens = `-- name: RevokeUnusedAuthTokens :execrows
update auth_tokens
set revoked_at = now()
where user_id = $1
  and kind = $2
  and used_at is null
  and revoked_at is null
`

type RevokeUnusedAuthTokensParams struct {
	UserID uuid.UUID
	Kind   AuthTokenKind
}

func (q *Queries) RevokeUnusedAuthTokens(ctx context.Context, arg RevokeUnusedAuthTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUnusedAuthTokens, arg.UserID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAuthSession = `-- name: RotateAuthSession :exec
update auth_sessions
set prev_refresh_hash = refresh_hash,
    refresh_hash = $1,
    rotated_at = $2::timestamptz,
    last_used_at = $2::timestamptz,
    expires_at = $3
where id = $4
`

type RotateAuthSessionParams struct {
	NewHash   string
	Now       time.Time
	ExpiresAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, rotateAuthSession,
		arg.NewHash,
		arg.Now,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
