// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const calCourseStatus = `-- name: CalCourseStatus :one
select status from courses where id = $1
`

func (q *Queries) CalCourseStatus(ctx context.Context, id uuid.UUID) (CourseStatus, error) {
	row := q.db.QueryRow(ctx, calCourseStatus, id)
	var status CourseStatus
	err := row.Scan(&status)
	return status, err
}

const calDue = `-- name: CalDue :many
select d.src, d.id, d.course_id, d.typ, d.title, d.starts_at from (
  select 'CLASS_SESSION'::text as src, cs.id, cs.course_id, 'CLASS_SESSION'::text as typ, ('Buổi ' || cs.session_no::text || coalesce(' · ' || nullif(cs.topic, ''), ''))::text as title, cs.starts_at
  from class_sessions cs
  union all
  select 'WEEKLY_EXAM', e.id, e.course_id, 'EXAM', e.title, e.opens_at from exams e where e.status in ('SCHEDULED', 'OPEN') and e.opens_at is not null
  union all
  select 'CALENDAR_EVENT', ce.id, ce.course_id, ce.type::text, ce.title, ce.starts_at from calendar_events ce
) d join courses c on c.id = d.course_id and c.status = 'ACTIVE'
where d.starts_at > $1::timestamptz and d.starts_at <= $2::timestamptz
order by d.starts_at, d.id
`

type CalDueParams struct {
	NowAt   time.Time
	UntilAt time.Time
}

type CalDueRow struct {
	Src      string
	ID       uuid.UUID
	CourseID uuid.UUID
	Typ      string
	Title    string
	StartsAt time.Time
}

// Nguồn có starts_at ∈ (now, until] của lớp ACTIVE: buổi học, bài thi SCHEDULED / OPEN, sự kiện.
func (q *Queries) CalDue(ctx context.Context, arg CalDueParams) ([]CalDueRow, error) {
	rows, err := q.db.Query(ctx, calDue, arg.NowAt, arg.UntilAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalDueRow{}
	for rows.Next() {
		var i CalDueRow
		if err := rows.Scan(
			&i.Src,
			&i.ID,
			&i.CourseID,
			&i.Typ,
			&i.Title,
			&i.StartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calEventDelete = `-- name: CalEventDelete :execrows
delete from calendar_events where id = $1 and course_id = $2
`

type CalEventDeleteParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) CalEventDelete(ctx context.Context, arg CalEventDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, calEventDelete, arg.ID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const calEventGet = `-- name: CalEventGet :one
select id, course_id, type, title, starts_at, ends_at, location, description, ref_type, ref_id, created_by, version, created_at, updated_at from calendar_events where id = $1 and course_id = $2
`

type CalEventGetParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) CalEventGet(ctx context.Context, arg CalEventGetParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, calEventGet, arg.ID, arg.CourseID)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.RefType,
		&i.RefID,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const calEventInsert = `-- name: CalEventInsert :one
insert into calendar_events (course_id, type, title, starts_at, ends_at, location, description, created_by)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, course_id, type, title, starts_at, ends_at, location, description, ref_type, ref_id, created_by, version, created_at, updated_at
`

type CalEventInsertParams struct {
	CourseID    uuid.UUID
	Type        CalendarEventType
	Title       string
	StartsAt    time.Time
	EndsAt      *time.Time
	Location    *string
	Description *string
	CreatedBy   uuid.UUID
}

func (q *Queries) CalEventInsert(ctx context.Context, arg CalEventInsertParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, calEventInsert,
		arg.CourseID,
		arg.Type,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
		arg.Location,
		arg.Description,
		arg.CreatedBy,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.RefType,
		&i.RefID,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const calEventUpdate = `-- name: CalEventUpdate :one
update calendar_events set type = $1, title = $2, starts_at = $3, ends_at = $4,
       location = $5, description = $6, version = version + 1
where id = $7 and course_id = $8 and version = $9
returning id, course_id, type, title, starts_at, ends_at, location, description, ref_type, ref_id, created_by, version, created_at, updated_at
`

type CalEventUpdateParams struct {
	Type        CalendarEventType
	Title       string
	StartsAt    time.Time
	EndsAt      *time.Time
	Location    *string
	Description *string
	ID          uuid.UUID
	CourseID    uuid.UUID
	Version     int32
}

func (q *Queries) CalEventUpdate(ctx context.Context, arg CalEventUpdateParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, calEventUpdate,
		arg.Type,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
		arg.Location,
		arg.Description,
		arg.ID,
		arg.CourseID,
		arg.Version,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.RefType,
		&i.RefID,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const calFeed = `-- name: CalFeed :many
with feed as (
  select c.class_code, 'class_session'::text as src, cs.id, ('Buổi ' || cs.session_no::text || coalesce(' · ' || nullif(cs.topic, ''), ''))::text as title, cs.starts_at, cs.ends_at, cs.room as location, cs.updated_at
  from class_sessions cs join courses c on c.id = cs.course_id
  where cs.course_id in (select en.course_id from enrollments en where en.user_id = $1 and en.status = 'ACTIVE')
  union all
  select c.class_code, 'weekly_exam', e.id, e.title, e.opens_at, e.closes_at, null, e.updated_at
  from exams e join courses c on c.id = e.course_id
  where e.status <> 'DRAFT' and e.opens_at is not null
    and e.course_id in (select en.course_id from enrollments en where en.user_id = $1 and en.status = 'ACTIVE')
  union all
  select c.class_code, 'calendar_event', ce.id, ce.title, ce.starts_at, ce.ends_at, ce.location, ce.updated_at
  from calendar_events ce join courses c on c.id = ce.course_id
  where ce.course_id in (select en.course_id from enrollments en where en.user_id = $1 and en.status = 'ACTIVE')
)
select f.class_code, f.src, f.id, f.title, f.starts_at, coalesce(f.ends_at, 'epoch'::timestamptz)::timestamptz as ends_at, (f.ends_at is not null)::bool as has_end, f.location, f.updated_at,
       (select count(*) from enrollments en2 where en2.user_id = $1 and en2.status = 'ACTIVE')::int as course_count
from feed f where f.starts_at >= $2::timestamptz and f.starts_at <= $3::timestamptz
order by f.starts_at, f.id
limit $4
`

type CalFeedParams struct {
	Owner     uuid.UUID
	FromAt    time.Time
	ToAt      time.Time
	PageLimit int32
}

type CalFeedRow struct {
	ClassCode   string
	Src         string
	ID          uuid.UUID
	Title       string
	StartsAt    time.Time
	EndsAt      time.Time
	HasEnd      bool
	Location    *string
	UpdatedAt   time.Time
	CourseCount int32
}

// Feed ICS: mọi lớp người đó ACTIVE; kèm mã lớp (tiền tố khi ≥ 2 lớp). Giới hạn do người gọi (≤ 2.000).
func (q *Queries) CalFeed(ctx context.Context, arg CalFeedParams) ([]CalFeedRow, error) {
	rows, err := q.db.Query(ctx, calFeed,
		arg.Owner,
		arg.FromAt,
		arg.ToAt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalFeedRow{}
	for rows.Next() {
		var i CalFeedRow
		if err := rows.Scan(
			&i.ClassCode,
			&i.Src,
			&i.ID,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.HasEnd,
			&i.Location,
			&i.UpdatedAt,
			&i.CourseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calInsertReminder = `-- name: CalInsertReminder :execrows
insert into reminder_log (user_id, course_id, source_type, source_id, starts_at, kind)
values ($1, $2, $3, $4, $5, 'T24H')
on conflict (user_id, source_type, source_id, starts_at, kind) do nothing
`

type CalInsertReminderParams struct {
	UserID     uuid.UUID
	CourseID   uuid.UUID
	SourceType ReminderSource
	SourceID   uuid.UUID
	StartsAt   time.Time
}

func (q *Queries) CalInsertReminder(ctx context.Context, arg CalInsertReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, calInsertReminder,
		arg.UserID,
		arg.CourseID,
		arg.SourceType,
		arg.SourceID,
		arg.StartsAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const calList = `-- name: CalList :many

with u as (
  select 'class_session'::text as src, cs.id, 'CLASS_SESSION'::text as typ, ('Buổi ' || cs.session_no::text || coalesce(' · ' || nullif(cs.topic, ''), ''))::text as title,
         cs.starts_at, cs.ends_at, cs.room as location, ''::text as exam_status, cs.updated_at, 0::int as ver
  from class_sessions cs where cs.course_id = $9
  union all
  select 'weekly_exam', e.id, 'EXAM', e.title, e.opens_at, e.closes_at, null, e.status::text, e.updated_at, 0
  from exams e where e.course_id = $9 and e.status <> 'DRAFT' and e.opens_at is not null
  union all
  select 'calendar_event', ce.id, ce.type::text, ce.title, ce.starts_at, ce.ends_at, ce.location, '', ce.updated_at, ce.version
  from calendar_events ce where ce.course_id = $9
)
select u.src, u.id, u.typ, u.title, u.starts_at, coalesce(u.ends_at, 'epoch'::timestamptz)::timestamptz as ends_at, (u.ends_at is not null)::bool as has_end, u.location, u.exam_status, u.updated_at, u.ver,
       case when u.src = 'weekly_exam' and $1::bool then coalesce((
         select case when a.status = 'IN_PROGRESS' then 'IN_PROGRESS' else 'SUBMITTED' end
         from exam_attempts a where a.exam_id = u.id and a.student_id = $2 limit 1), 'NOT_STARTED') else '' end::text as personal_state
from u
where u.starts_at < $3::timestamptz and coalesce(u.ends_at, u.starts_at) >= $4::timestamptz
  and (not $5::bool or u.typ = 'EXAM')
  and ($6::timestamptz is null or (u.starts_at, u.id) > ($6::timestamptz, $7::uuid))
order by u.starts_at, u.id
limit $8
`

type CalListParams struct {
	IsStudent bool
	ViewerID  uuid.UUID
	ToAt      time.Time
	FromAt    time.Time
	OnlyExam  bool
	CursorAt  *time.Time
	CursorID  *uuid.UUID
	PageLimit int32
	CourseID  uuid.UUID
}

type CalListRow struct {
	Src           string
	ID            uuid.UUID
	Typ           string
	Title         string
	StartsAt      time.Time
	EndsAt        time.Time
	HasEnd        bool
	Location      *string
	ExamStatus    string
	UpdatedAt     time.Time
	Ver           int32
	PersonalState string
}

// US-P8-03 — lịch gộp lúc đọc (UNION, không nhân bản), sự kiện của Staff, token ICS (băm), nhắc 24 giờ. Mọi truy vấn bắt đầu từ course_id / user_id (luật 13).
// Ba nguồn gộp: class_sessions, exams (không DRAFT), calendar_events. `personal_state` chỉ cho sinh viên và dòng bài thi, từ exam_attempts của CHÍNH người xem.
// Khoảng [from, to): dòng giao với khoảng. Keyset (starts_at, id).
func (q *Queries) CalList(ctx context.Context, arg CalListParams) ([]CalListRow, error) {
	rows, err := q.db.Query(ctx, calList,
		arg.IsStudent,
		arg.ViewerID,
		arg.ToAt,
		arg.FromAt,
		arg.OnlyExam,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalListRow{}
	for rows.Next() {
		var i CalListRow
		if err := rows.Scan(
			&i.Src,
			&i.ID,
			&i.Typ,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.HasEnd,
			&i.Location,
			&i.ExamStatus,
			&i.UpdatedAt,
			&i.Ver,
			&i.PersonalState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calRecipients = `-- name: CalRecipients :many
select e.user_id, u.email, u.full_name, (u.email_verified_at is not null)::bool as verified,
       coalesce(us.remind_deadline_by_mail, true)::bool as remind_mail, coalesce(us.preferences, '{}'::jsonb) as preferences
from enrollments e join users u on u.id = e.user_id
left join user_settings us on us.user_id = e.user_id
where e.course_id = $1 and e.status = 'ACTIVE' and e.role_in_course = 'STUDENT' and u.status = 'ACTIVE'
  and e.user_id > $2::uuid
order by e.user_id
limit $3
`

type CalRecipientsParams struct {
	CourseID  uuid.UUID
	AfterUser uuid.UUID
	PageLimit int32
}

type CalRecipientsRow struct {
	UserID      uuid.UUID
	Email       string
	FullName    string
	Verified    bool
	RemindMail  bool
	Preferences json.RawMessage
}

// Sinh viên ACTIVE của lớp, tài khoản ACTIVE; lô theo user_id (keyset). Chưa có user_settings = mặc định bật.
func (q *Queries) CalRecipients(ctx context.Context, arg CalRecipientsParams) ([]CalRecipientsRow, error) {
	rows, err := q.db.Query(ctx, calRecipients, arg.CourseID, arg.AfterUser, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalRecipientsRow{}
	for rows.Next() {
		var i CalRecipientsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.FullName,
			&i.Verified,
			&i.RemindMail,
			&i.Preferences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const icsTokenClear = `-- name: IcsTokenClear :execrows
update users u set ics_token = null where u.id = $1
`

func (q *Queries) IcsTokenClear(ctx context.Context, owner uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, icsTokenClear, owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const icsTokenExists = `-- name: IcsTokenExists :one
select (u.ics_token is not null)::bool from users u where u.id = $1
`

func (q *Queries) IcsTokenExists(ctx context.Context, owner uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, icsTokenExists, owner)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const icsTokenSet = `-- name: IcsTokenSet :execrows
update users u set ics_token = $1 where u.id = $2
`

type IcsTokenSetParams struct {
	TokenHash *string
	Owner     uuid.UUID
}

func (q *Queries) IcsTokenSet(ctx context.Context, arg IcsTokenSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, icsTokenSet, arg.TokenHash, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const icsUserByHash = `-- name: IcsUserByHash :one
select u.id from users u where u.ics_token = $1 and u.status = 'ACTIVE'
`

// Tra theo sha256(token) bằng chỉ mục duy nhất; tài khoản không ACTIVE → như không có.
func (q *Queries) IcsUserByHash(ctx context.Context, tokenHash *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, icsUserByHash, tokenHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
