// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const finishChatMessage = `-- name: FinishChatMessage :one
update chat_messages
set content = $1, partial_content = null, stream_status = $2, completed_at = now(),
    citations = $3, blocks = $4, confidence = $5, low_confidence = $6,
    no_context = $7, degraded = $8, error_code = $9, trace_id = $10
where id = $11 and stream_status = 'STREAMING'
returning id, course_id, session_id, user_id, role, content, partial_content, stream_status, client_msg_id, reply_to, attempt, intent, citations, blocks, confidence, low_confidence, no_context, degraded, masked_count, feedback, error_code, trace_id, completed_at, created_at, updated_at
`

type FinishChatMessageParams struct {
	Content       string
	StreamStatus  ChatStreamStatus
	Citations     json.RawMessage
	Blocks        json.RawMessage
	Confidence    decimal.NullDecimal
	LowConfidence bool
	NoContext     bool
	Degraded      bool
	ErrorCode     *string
	TraceID       *string
	ID            uuid.UUID
}

// Ghi có điều kiện: chỉ tin còn STREAMING mới được đóng (tin đã bị Dừng / reaper đóng thì 0 hàng → pgx.ErrNoRows).
func (q *Queries) FinishChatMessage(ctx context.Context, arg FinishChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, finishChatMessage,
		arg.Content,
		arg.StreamStatus,
		arg.Citations,
		arg.Blocks,
		arg.Confidence,
		arg.LowConfidence,
		arg.NoContext,
		arg.Degraded,
		arg.ErrorCode,
		arg.TraceID,
		arg.ID,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SessionID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.PartialContent,
		&i.StreamStatus,
		&i.ClientMsgID,
		&i.ReplyTo,
		&i.Attempt,
		&i.Intent,
		&i.Citations,
		&i.Blocks,
		&i.Confidence,
		&i.LowConfidence,
		&i.NoContext,
		&i.Degraded,
		&i.MaskedCount,
		&i.Feedback,
		&i.ErrorCode,
		&i.TraceID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatSession = `-- name: GetChatSession :one
select id, course_id, user_id, channel, title, document_id, last_message_at, deleted_at, created_at, updated_at from chat_sessions
where id = $1 and user_id = $2 and deleted_at is null
`

type GetChatSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Channel,
		&i.Title,
		&i.DocumentID,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChatMessage = `-- name: InsertChatMessage :one
insert into chat_messages (course_id, session_id, user_id, role, content, stream_status, client_msg_id, reply_to, intent, masked_count)
values ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10)
returning id, course_id, session_id, user_id, role, content, partial_content, stream_status, client_msg_id, reply_to, attempt, intent, citations, blocks, confidence, low_confidence, no_context, degraded, masked_count, feedback, error_code, trace_id, completed_at, created_at, updated_at
`

type InsertChatMessageParams struct {
	CourseID     uuid.UUID
	SessionID    uuid.UUID
	UserID       uuid.UUID
	Role         ChatRole
	Content      string
	StreamStatus ChatStreamStatus
	ClientMsgID  *uuid.UUID
	ReplyTo      *uuid.UUID
	Intent       *string
	MaskedCount  int32
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertChatMessage,
		arg.CourseID,
		arg.SessionID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.StreamStatus,
		arg.ClientMsgID,
		arg.ReplyTo,
		arg.Intent,
		arg.MaskedCount,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SessionID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.PartialContent,
		&i.StreamStatus,
		&i.ClientMsgID,
		&i.ReplyTo,
		&i.Attempt,
		&i.Intent,
		&i.Citations,
		&i.Blocks,
		&i.Confidence,
		&i.LowConfidence,
		&i.NoContext,
		&i.Degraded,
		&i.MaskedCount,
		&i.Feedback,
		&i.ErrorCode,
		&i.TraceID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChatSession = `-- name: InsertChatSession :one

insert into chat_sessions (course_id, user_id, title, document_id)
values ($1, $2, $3, $4)
returning id, course_id, user_id, channel, title, document_id, last_message_at, deleted_at, created_at, updated_at
`

type InsertChatSessionParams struct {
	CourseID   uuid.UUID
	UserID     uuid.UUID
	Title      *string
	DocumentID *uuid.UUID
}

// Chat riêng (US-P3-01; service ở US-P3-05). Mọi truy vấn lọc theo chủ phiên (user_id) — không có đường đọc chat của người khác.
func (q *Queries) InsertChatSession(ctx context.Context, arg InsertChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, insertChatSession,
		arg.CourseID,
		arg.UserID,
		arg.Title,
		arg.DocumentID,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Channel,
		&i.Title,
		&i.DocumentID,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
select id, course_id, session_id, user_id, role, content, partial_content, stream_status, client_msg_id, reply_to, attempt, intent, citations, blocks, confidence, low_confidence, no_context, degraded, masked_count, feedback, error_code, trace_id, completed_at, created_at, updated_at from chat_messages
where session_id = $1
  and ($2::timestamptz is null or (created_at, id) < ($2::timestamptz, $3::uuid))
order by created_at desc, id desc
limit $4
`

type ListChatMessagesParams struct {
	SessionID uuid.UUID
	CursorAt  *time.Time
	CursorID  *uuid.UUID
	PageLimit int32
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages,
		arg.SessionID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.SessionID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.PartialContent,
			&i.StreamStatus,
			&i.ClientMsgID,
			&i.ReplyTo,
			&i.Attempt,
			&i.Intent,
			&i.Citations,
			&i.Blocks,
			&i.Confidence,
			&i.LowConfidence,
			&i.NoContext,
			&i.Degraded,
			&i.MaskedCount,
			&i.Feedback,
			&i.ErrorCode,
			&i.TraceID,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessions = `-- name: ListChatSessions :many
select id, course_id, user_id, channel, title, document_id, last_message_at, deleted_at, created_at, updated_at from chat_sessions
where course_id = $1 and user_id = $2 and deleted_at is null
  and ($3::timestamptz is null or (last_message_at, id) < ($3::timestamptz, $4::uuid))
order by last_message_at desc, id desc
limit $5
`

type ListChatSessionsParams struct {
	CourseID  uuid.UUID
	UserID    uuid.UUID
	CursorAt  *time.Time
	CursorID  *uuid.UUID
	PageLimit int32
}

func (q *Queries) ListChatSessions(ctx context.Context, arg ListChatSessionsParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessions,
		arg.CourseID,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.UserID,
			&i.Channel,
			&i.Title,
			&i.DocumentID,
			&i.LastMessageAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapStaleChatMessages = `-- name: ReapStaleChatMessages :many
update chat_messages
set stream_status = 'FAILED', content = coalesce(partial_content, ''), partial_content = null, completed_at = now(), error_code = 'STALE'
where stream_status = 'STREAMING' and updated_at < $1
returning id, course_id, session_id
`

type ReapStaleChatMessagesRow struct {
	ID        uuid.UUID
	CourseID  uuid.UUID
	SessionID uuid.UUID
}

// Reaper: tin STREAMING quá hạn → FAILED, giữ phần đã có.
func (q *Queries) ReapStaleChatMessages(ctx context.Context, before time.Time) ([]ReapStaleChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, reapStaleChatMessages, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReapStaleChatMessagesRow{}
	for rows.Next() {
		var i ReapStaleChatMessagesRow
		if err := rows.Scan(&i.ID, &i.CourseID, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreChatSession = `-- name: RestoreChatSession :execrows
update chat_sessions set deleted_at = null where id = $1 and user_id = $2 and deleted_at is not null
`

type RestoreChatSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RestoreChatSession(ctx context.Context, arg RestoreChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreChatSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setChatPartial = `-- name: SetChatPartial :exec
update chat_messages set partial_content = $1
where id = $2 and stream_status = 'STREAMING'
`

type SetChatPartialParams struct {
	PartialContent *string
	ID             uuid.UUID
}

func (q *Queries) SetChatPartial(ctx context.Context, arg SetChatPartialParams) error {
	_, err := q.db.Exec(ctx, setChatPartial, arg.PartialContent, arg.ID)
	return err
}

const softDeleteChatSession = `-- name: SoftDeleteChatSession :execrows
update chat_sessions set deleted_at = now() where id = $1 and user_id = $2 and deleted_at is null
`

type SoftDeleteChatSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeleteChatSession(ctx context.Context, arg SoftDeleteChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteChatSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchChatSession = `-- name: TouchChatSession :exec
update chat_sessions set last_message_at = now() where id = $1
`

func (q *Queries) TouchChatSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchChatSession, id)
	return err
}
