// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertLLMAudit implements pgx.CopyFromSource.
type iteratorForInsertLLMAudit struct {
	rows                 []InsertLLMAuditParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLLMAudit) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLLMAudit) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Task,
		r.rows[0].Lane,
		r.rows[0].Provider,
		r.rows[0].Model,
		r.rows[0].TokensIn,
		r.rows[0].TokensOut,
		r.rows[0].LatencyMs,
		r.rows[0].QueueWaitMs,
		r.rows[0].Attempts,
		r.rows[0].FallbackIndex,
		r.rows[0].CostEst,
		r.rows[0].Status,
		r.rows[0].ErrorKind,
		r.rows[0].Degraded,
		r.rows[0].PiiMaskedCount,
		r.rows[0].UserID,
		r.rows[0].CourseID,
		r.rows[0].TraceID,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForInsertLLMAudit) Err() error {
	return nil
}

// Ghi llm_audit theo lô bằng COPY — cổng llm ghi bất đồng bộ, một lần cho cả lô.
func (q *Queries) InsertLLMAudit(ctx context.Context, arg []InsertLLMAuditParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"llm_audit"}, []string{"task", "lane", "provider", "model", "tokens_in", "tokens_out", "latency_ms", "queue_wait_ms", "attempts", "fallback_index", "cost_est", "status", "error_kind", "degraded", "pii_masked_count", "user_id", "course_id", "trace_id", "created_at"}, &iteratorForInsertLLMAudit{rows: arg})
}
