// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activateStaffEnrollment = `-- name: ActivateStaffEnrollment :one
insert into enrollments (course_id, user_id, role_in_course, status, joined_via, status_changed_by)
values ($1, $2, $3, 'ACTIVE', 'ADMIN', $4)
on conflict (course_id, user_id) do update
set role_in_course = excluded.role_in_course, status = 'ACTIVE', joined_via = 'ADMIN',
    previous_status = enrollments.status, status_changed_at = now(), status_changed_by = excluded.status_changed_by,
    removed_at = null, version = enrollments.version + 1
returning id
`

type ActivateStaffEnrollmentParams struct {
	CourseID     uuid.UUID
	UserID       uuid.UUID
	RoleInCourse EnrollmentRole
	Actor        *uuid.UUID
}

// Gán giảng viên / TA. Người từng bị gỡ (REMOVED) ⇒ DÙNG LẠI dòng cũ (SRS 4.4). joined_via=ADMIN.
func (q *Queries) ActivateStaffEnrollment(ctx context.Context, arg ActivateStaffEnrollmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, activateStaffEnrollment,
		arg.CourseID,
		arg.UserID,
		arg.RoleInCourse,
		arg.Actor,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const archiveCourse = `-- name: ArchiveCourse :one
update courses
set status = 'ARCHIVED', archived_at = now(), join_enabled = false, version = version + 1
where id = $1 and status = 'ACTIVE'
returning id, subject_code, class_code, name, semester, status, escalation_threshold, settings, join_code, join_enabled, join_expires_at, join_require_approval, allowed_email_domain, capacity, created_by, archived_at, version, created_at, updated_at
`

// Lưu trữ: tắt mã tham gia NGAY; thành viên giữ nguyên. Không dòng ⇒ đã lưu trữ (idempotent ở người gọi).
func (q *Queries) ArchiveCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, archiveCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SubjectCode,
		&i.ClassCode,
		&i.Name,
		&i.Semester,
		&i.Status,
		&i.EscalationThreshold,
		&i.Settings,
		&i.JoinCode,
		&i.JoinEnabled,
		&i.JoinExpiresAt,
		&i.JoinRequireApproval,
		&i.AllowedEmailDomain,
		&i.Capacity,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const chunksForCourse = `-- name: ChunksForCourse :many
select id, document_id, text, audience
from content_chunks
where course_ids @> array[$1::uuid]
order by id
limit $2
`

type ChunksForCourseParams struct {
	CourseID uuid.UUID
	Lim      int32
}

type ChunksForCourseRow struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
	Text       string
	Audience   ChunkAudience
}

// Đường DUY NHẤT đọc content_chunks ở P2: luôn lọc theo lớp (course_ids, GIN). Không có hàm đọc chunk "không lọc lớp".
func (q *Queries) ChunksForCourse(ctx context.Context, arg ChunksForCourseParams) ([]ChunksForCourseRow, error) {
	rows, err := q.db.Query(ctx, chunksForCourse, arg.CourseID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChunksForCourseRow{}
	for rows.Next() {
		var i ChunksForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Text,
			&i.Audience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveStudents = `-- name: CountActiveStudents :one
select count(*)::int from enrollments where course_id = $1 and role_in_course = 'STUDENT' and status = 'ACTIVE'
`

func (q *Queries) CountActiveStudents(ctx context.Context, courseID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveStudents, courseID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countCourseStudents = `-- name: CountCourseStudents :one
select count(*) filter (where status = 'ACTIVE')::int as active, count(*) filter (where status = 'PENDING')::int as pending
from enrollments
where course_id = $1 and role_in_course = 'STUDENT'
`

type CountCourseStudentsRow struct {
	Active  int32
	Pending int32
}

func (q *Queries) CountCourseStudents(ctx context.Context, courseID uuid.UUID) (CountCourseStudentsRow, error) {
	row := q.db.QueryRow(ctx, countCourseStudents, courseID)
	var i CountCourseStudentsRow
	err := row.Scan(&i.Active, &i.Pending)
	return i, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
select count(*)::int from notifications where user_id = $1 and read_at is null
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const enrollmentConflictByStudentCode = `-- name: EnrollmentConflictByStudentCode :one
select exists (
    select 1 from enrollments
    where course_id = $1 and student_code_snapshot = $2 and user_id <> $3 and status in ('ACTIVE', 'PENDING')
) as held
`

type EnrollmentConflictByStudentCodeParams struct {
	CourseID uuid.UUID
	Code     *string
	UserID   uuid.UUID
}

// (Danh sách trắng SRS FEAT-account-security 4.2.5.) MSSV tự khai của người vào bằng mã đã là ảnh chụp của người KHÁC đang ở / chờ vào lớp? (không bao giờ dùng để nối tài khoản)
func (q *Queries) EnrollmentConflictByStudentCode(ctx context.Context, arg EnrollmentConflictByStudentCodeParams) (bool, error) {
	row := q.db.QueryRow(ctx, enrollmentConflictByStudentCode, arg.CourseID, arg.Code, arg.UserID)
	var held bool
	err := row.Scan(&held)
	return held, err
}

const getCourse = `-- name: GetCourse :one
select id, subject_code, class_code, name, semester, status, escalation_threshold, settings, join_code, join_enabled, join_expires_at, join_require_approval, allowed_email_domain, capacity, created_by, archived_at, version, created_at, updated_at from courses where id = $1
`

// Đọc đầy đủ một lớp (worker, không khoá).
func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SubjectCode,
		&i.ClassCode,
		&i.Name,
		&i.Semester,
		&i.Status,
		&i.EscalationThreshold,
		&i.Settings,
		&i.JoinCode,
		&i.JoinEnabled,
		&i.JoinExpiresAt,
		&i.JoinRequireApproval,
		&i.AllowedEmailDomain,
		&i.Capacity,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseBasic = `-- name: GetCourseBasic :one
select id, class_code, subject_code, name, semester, status from courses where id = $1
`

type GetCourseBasicRow struct {
	ID          uuid.UUID
	ClassCode   string
	SubjectCode string
	Name        string
	Semester    string
	Status      CourseStatus
}

func (q *Queries) GetCourseBasic(ctx context.Context, id uuid.UUID) (GetCourseBasicRow, error) {
	row := q.db.QueryRow(ctx, getCourseBasic, id)
	var i GetCourseBasicRow
	err := row.Scan(
		&i.ID,
		&i.ClassCode,
		&i.SubjectCode,
		&i.Name,
		&i.Semester,
		&i.Status,
	)
	return i, err
}

const getCourseByJoinCode = `-- name: GetCourseByJoinCode :one

select id, subject_code, class_code, name, semester, status, escalation_threshold, settings, join_code, join_enabled, join_expires_at, join_require_approval, allowed_email_domain, capacity, created_by, archived_at, version, created_at, updated_at from courses where join_code = $1
`

// ===== Vào lớp bằng mã, cài đặt tham gia, thành viên (US-P2-09) =====
// Bước tra mã DUY NHẤT của preview và join (luôn đúng một truy vấn ở mọi nhánh thất bại).
func (q *Queries) GetCourseByJoinCode(ctx context.Context, joinCode string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByJoinCode, joinCode)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SubjectCode,
		&i.ClassCode,
		&i.Name,
		&i.Semester,
		&i.Status,
		&i.EscalationThreshold,
		&i.Settings,
		&i.JoinCode,
		&i.JoinEnabled,
		&i.JoinExpiresAt,
		&i.JoinRequireApproval,
		&i.AllowedEmailDomain,
		&i.Capacity,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one

select role_in_course, status from enrollments where course_id = $1 and user_id = $2
`

type GetMembershipParams struct {
	CourseID uuid.UUID
	UserID   uuid.UUID
}

type GetMembershipRow struct {
	RoleInCourse EnrollmentRole
	Status       EnrollmentStatus
}

// Lớp học: tra quyền và đọc (FEAT-course-foundation US-P2-07). Mọi truy vấn của bảng thuộc lớp bắt đầu bằng course_id (luật 13).
// CourseAccessGuard: MỘT truy vấn theo chỉ mục (course_id, user_id), không cache.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.CourseID, arg.UserID)
	var i GetMembershipRow
	err := row.Scan(&i.RoleInCourse, &i.Status)
	return i, err
}

const getUsersForAssign = `-- name: GetUsersForAssign :many
select id, full_name, role, status from users where id = any($1::text[]::uuid[])
`

type GetUsersForAssignRow struct {
	ID       uuid.UUID
	FullName string
	Role     UserRole
	Status   UserStatus
}

func (q *Queries) GetUsersForAssign(ctx context.Context, ids []string) ([]GetUsersForAssignRow, error) {
	rows, err := q.db.Query(ctx, getUsersForAssign, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersForAssignRow{}
	for rows.Next() {
		var i GetUsersForAssignRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCodeEnrollment = `-- name: InsertCodeEnrollment :one
insert into enrollments (course_id, user_id, role_in_course, status, joined_via, student_code_snapshot, warning, status_changed_at)
values ($1, $2, 'STUDENT', $3, 'CODE', $4, $5, $6)
returning id, course_id, user_id, role_in_course, status, joined_via, student_code_snapshot, warning, previous_status, status_changed_at, status_changed_by, removed_at, version, created_at, updated_at
`

type InsertCodeEnrollmentParams struct {
	CourseID uuid.UUID
	UserID   uuid.UUID
	Status   EnrollmentStatus
	Snapshot *string
	Warning  *string
	At       time.Time
}

func (q *Queries) InsertCodeEnrollment(ctx context.Context, arg InsertCodeEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, insertCodeEnrollment,
		arg.CourseID,
		arg.UserID,
		arg.Status,
		arg.Snapshot,
		arg.Warning,
		arg.At,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.RoleInCourse,
		&i.Status,
		&i.JoinedVia,
		&i.StudentCodeSnapshot,
		&i.Warning,
		&i.PreviousStatus,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.RemovedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCourse = `-- name: InsertCourse :one

insert into courses (subject_code, class_code, name, semester, capacity, join_code, created_by)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (join_code) do nothing
returning id, subject_code, class_code, name, semester, status, escalation_threshold, settings, join_code, join_enabled, join_expires_at, join_require_approval, allowed_email_domain, capacity, created_by, archived_at, version, created_at, updated_at
`

type InsertCourseParams struct {
	SubjectCode string
	ClassCode   string
	Name        string
	Semester    string
	Capacity    *int32
	JoinCode    string
	CreatedBy   uuid.UUID
}

// ===== Admin mở lớp, gán giảng viên / TA, lưu trữ (US-P2-08) =====
// Trùng join_code ⇒ không dòng (người gọi sinh mã khác, tối đa 5 lần); trùng class_code ⇒ 23505 courses_class_code_key.
func (q *Queries) InsertCourse(ctx context.Context, arg InsertCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, insertCourse,
		arg.SubjectCode,
		arg.ClassCode,
		arg.Name,
		arg.Semester,
		arg.Capacity,
		arg.JoinCode,
		arg.CreatedBy,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SubjectCode,
		&i.ClassCode,
		&i.Name,
		&i.Semester,
		&i.Status,
		&i.EscalationThreshold,
		&i.Settings,
		&i.JoinCode,
		&i.JoinEnabled,
		&i.JoinExpiresAt,
		&i.JoinRequireApproval,
		&i.AllowedEmailDomain,
		&i.Capacity,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :execrows

insert into notifications (user_id, course_id, type, title, body, link, dedupe_key)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing
`

type InsertNotificationParams struct {
	UserID    uuid.UUID
	CourseID  *uuid.UUID
	Type      string
	Title     string
	Body      *string
	Link      *string
	DedupeKey *string
}

// ===== Thông báo (US-P2-08) =====
// Idempotent theo (user_id, dedupe_key): giao lại cùng tin outbox không tạo dòng thứ hai.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.CourseID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.DedupeKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAdminCourses = `-- name: ListAdminCourses :many
select c.id, c.class_code, c.subject_code, c.name, c.semester, c.status, c.capacity, c.version, c.created_at,
       t.user_id as teacher_id, tu.full_name as teacher_name,
       (select count(*) from enrollments e where e.course_id = c.id and e.role_in_course = 'TA' and e.status = 'ACTIVE')::int as assistants_count,
       (select count(*) from enrollments e where e.course_id = c.id and e.role_in_course = 'STUDENT' and e.status = 'ACTIVE')::int as students_active,
       (select count(*) from enrollments e where e.course_id = c.id and e.role_in_course = 'STUDENT' and e.status = 'PENDING')::int as students_pending
from courses c
left join enrollments t on t.course_id = c.id and t.role_in_course = 'TEACHER' and t.status = 'ACTIVE'
left join users tu on tu.id = t.user_id
where ($1::uuid is null or c.id = $1::uuid)
  and ($2::course_status is null or c.status = $2::course_status)
  and ($3::text is null or c.semester = $3::text)
  and ($4::text is null
       or vn_fold(c.name) like $4::text escape '\'
       or lower(c.class_code) like $5::text escape '\')
  and ($6::timestamptz is null or (c.created_at, c.id) < ($6::timestamptz, $7::uuid))
order by c.created_at desc, c.id desc
limit $8
`

type ListAdminCoursesParams struct {
	ID       *uuid.UUID
	Status   *CourseStatus
	Semester *string
	NameLike *string
	CodeLike *string
	CurAt    *time.Time
	CurID    *uuid.UUID
	Lim      int32
}

type ListAdminCoursesRow struct {
	ID              uuid.UUID
	ClassCode       string
	SubjectCode     string
	Name            string
	Semester        string
	Status          CourseStatus
	Capacity        *int32
	Version         int32
	CreatedAt       time.Time
	TeacherID       *uuid.UUID
	TeacherName     *string
	AssistantsCount int32
	StudentsActive  int32
	StudentsPending int32
}

// MỘT truy vấn tổng hợp cho cả trang (không N+1). Không có join_code, không có sinh viên (Admin không đọc nội dung lớp).
func (q *Queries) ListAdminCourses(ctx context.Context, arg ListAdminCoursesParams) ([]ListAdminCoursesRow, error) {
	rows, err := q.db.Query(ctx, listAdminCourses,
		arg.ID,
		arg.Status,
		arg.Semester,
		arg.NameLike,
		arg.CodeLike,
		arg.CurAt,
		arg.CurID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminCoursesRow{}
	for rows.Next() {
		var i ListAdminCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassCode,
			&i.SubjectCode,
			&i.Name,
			&i.Semester,
			&i.Status,
			&i.Capacity,
			&i.Version,
			&i.CreatedAt,
			&i.TeacherID,
			&i.TeacherName,
			&i.AssistantsCount,
			&i.StudentsActive,
			&i.StudentsPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantCandidates = `-- name: ListAssistantCandidates :many

select id, full_name, email
from users
where role = 'TA' and status in ('ACTIVE', 'INVITED')
  and ($1::text is null
       or vn_fold(full_name) like $1::text escape '\'
       or email like $2::text escape '\')
order by full_name, id
limit 20
`

type ListAssistantCandidatesParams struct {
	NameLike  *string
	EmailLike *string
}

type ListAssistantCandidatesRow struct {
	ID       uuid.UUID
	FullName string
	Email    string
}

// ids là text[]: pgx ở chế độ simple protocol (PgBouncer) không mã hoá được []uuid.UUID
func (q *Queries) ListAssistantCandidates(ctx context.Context, arg ListAssistantCandidatesParams) ([]ListAssistantCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAssistantCandidates, arg.NameLike, arg.EmailLike)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssistantCandidatesRow{}
	for rows.Next() {
		var i ListAssistantCandidatesRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseTeacherNames = `-- name: ListCourseTeacherNames :many
select u.full_name
from enrollments e
join users u on u.id = e.user_id
where e.course_id = $1 and e.role_in_course = 'TEACHER' and e.status = 'ACTIVE'
order by u.full_name
`

func (q *Queries) ListCourseTeacherNames(ctx context.Context, courseID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listCourseTeacherNames, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var full_name string
		if err := rows.Scan(&full_name); err != nil {
			return nil, err
		}
		items = append(items, full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
with cnt as (
    select count(*) filter (where c.status = 'ACTIVE' and c.role_in_course = 'STUDENT')::int as active,
           count(*) filter (where c.status = 'PENDING' and c.role_in_course = 'STUDENT')::int as pending
    from enrollments c where c.course_id = $1
), page as (
    select e.user_id, u.full_name, u.email, e.student_code_snapshot, e.role_in_course, e.status, e.joined_via, e.warning, e.status_changed_at
    from enrollments e join users u on u.id = e.user_id
    where e.course_id = $1
      and (case when $2::enrollment_status is null then e.status in ('ACTIVE', 'PENDING') else e.status = $2::enrollment_status end)
      and ($3::enrollment_role is null or e.role_in_course = $3::enrollment_role)
      and ($4::text is null
           or vn_fold(u.full_name) like $4::text escape '\'
           or e.student_code_snapshot like $5::text escape '\'
           or u.email like $6::text escape '\')
      and ($7::timestamptz is null
           or e.status_changed_at < $7::timestamptz
           or (e.status_changed_at = $7::timestamptz and e.user_id > $8::uuid))
    order by e.status_changed_at desc, e.user_id
    limit $9
)
select cnt.active, cnt.pending, page.user_id, page.full_name, page.email, page.student_code_snapshot, page.role_in_course, page.status, page.joined_via, page.warning, page.status_changed_at
from cnt left join page on true
order by page.status_changed_at desc nulls last, page.user_id
`

type ListMembersParams struct {
	CourseID  uuid.UUID
	Status    *EnrollmentStatus
	Role      *EnrollmentRole
	NameLike  *string
	CodeLike  *string
	EmailLike *string
	CurAt     *time.Time
	CurID     *uuid.UUID
	Lim       int32
}

type ListMembersRow struct {
	Active              int32
	Pending             int32
	UserID              *uuid.UUID
	FullName            *string
	Email               *string
	StudentCodeSnapshot *string
	RoleInCourse        *EnrollmentRole
	Status              *EnrollmentStatus
	JoinedVia           *EnrollmentJoinedVia
	Warning             *string
	StatusChangedAt     *time.Time
}

// Một truy vấn: số đếm (toàn lớp, không theo bộ lọc) + một trang thành viên. Trang rỗng vẫn trả đúng một dòng mang số đếm.
func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.CourseID,
		arg.Status,
		arg.Role,
		arg.NameLike,
		arg.CodeLike,
		arg.EmailLike,
		arg.CurAt,
		arg.CurID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.Active,
			&i.Pending,
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.StudentCodeSnapshot,
			&i.RoleInCourse,
			&i.Status,
			&i.JoinedVia,
			&i.Warning,
			&i.StatusChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCourses = `-- name: ListMyCourses :many
select c.id, c.class_code, c.subject_code, c.name, c.semester, c.status as course_status,
       e.role_in_course, e.status as enrollment_status, e.created_at as enrolled_at, e.id as enrollment_id
from enrollments e
join courses c on c.id = e.course_id
where e.user_id = $1
  and (e.status = 'ACTIVE' or (e.status = 'PENDING' and e.role_in_course = 'STUDENT'))
  and ($2::timestamptz is null or (e.created_at, e.id) < ($2::timestamptz, $3::uuid))
order by e.created_at desc, e.id desc
limit $4
`

type ListMyCoursesParams struct {
	UserID uuid.UUID
	CurAt  *time.Time
	CurID  *uuid.UUID
	Lim    int32
}

type ListMyCoursesRow struct {
	ID               uuid.UUID
	ClassCode        string
	SubjectCode      string
	Name             string
	Semester         string
	CourseStatus     CourseStatus
	RoleInCourse     EnrollmentRole
	EnrollmentStatus EnrollmentStatus
	EnrolledAt       time.Time
	EnrollmentID     uuid.UUID
}

// Sinh viên: lớp ACTIVE và PENDING của chính mình; Giảng viên / TA: lớp được phân công (ACTIVE). Một truy vấn, không N+1.
func (q *Queries) ListMyCourses(ctx context.Context, arg ListMyCoursesParams) ([]ListMyCoursesRow, error) {
	rows, err := q.db.Query(ctx, listMyCourses,
		arg.UserID,
		arg.CurAt,
		arg.CurID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyCoursesRow{}
	for rows.Next() {
		var i ListMyCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassCode,
			&i.SubjectCode,
			&i.Name,
			&i.Semester,
			&i.CourseStatus,
			&i.RoleInCourse,
			&i.EnrollmentStatus,
			&i.EnrolledAt,
			&i.EnrollmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
select id, type, title, body, link, course_id, read_at, created_at
from notifications
where user_id = $1
  and (not $2::bool or read_at is null)
  and ($3::timestamptz is null or (created_at, id) < ($3::timestamptz, $4::uuid))
order by created_at desc, id desc
limit $5
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	UnreadOnly bool
	CurAt      *time.Time
	CurID      *uuid.UUID
	Lim        int32
}

type ListNotificationsRow struct {
	ID        uuid.UUID
	Type      string
	Title     string
	Body      *string
	Link      *string
	CourseID  *uuid.UUID
	ReadAt    *time.Time
	CreatedAt time.Time
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.CurAt,
		arg.CurID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.CourseID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffEnrollments = `-- name: ListStaffEnrollments :many
select e.user_id, e.role_in_course, u.full_name
from enrollments e join users u on u.id = e.user_id
where e.course_id = $1 and e.role_in_course in ('TEACHER', 'TA') and e.status = 'ACTIVE'
order by u.full_name, e.user_id
`

type ListStaffEnrollmentsRow struct {
	UserID       uuid.UUID
	RoleInCourse EnrollmentRole
	FullName     string
}

// Giảng viên và TA ACTIVE của lớp (để so khác biệt khi gán).
func (q *Queries) ListStaffEnrollments(ctx context.Context, courseID uuid.UUID) ([]ListStaffEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listStaffEnrollments, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffEnrollmentsRow{}
	for rows.Next() {
		var i ListStaffEnrollmentsRow
		if err := rows.Scan(&i.UserID, &i.RoleInCourse, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCourse = `-- name: LockCourse :one
select id, subject_code, class_code, name, semester, status, escalation_threshold, settings, join_code, join_enabled, join_expires_at, join_require_approval, allowed_email_domain, capacity, created_by, archived_at, version, created_at, updated_at from courses where id = $1 for update
`

func (q *Queries) LockCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, lockCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SubjectCode,
		&i.ClassCode,
		&i.Name,
		&i.Semester,
		&i.Status,
		&i.EscalationThreshold,
		&i.Settings,
		&i.JoinCode,
		&i.JoinEnabled,
		&i.JoinExpiresAt,
		&i.JoinRequireApproval,
		&i.AllowedEmailDomain,
		&i.Capacity,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockEnrollment = `-- name: LockEnrollment :one
select id, course_id, user_id, role_in_course, status, joined_via, student_code_snapshot, warning, previous_status, status_changed_at, status_changed_by, removed_at, version, created_at, updated_at from enrollments where course_id = $1 and user_id = $2 for update
`

type LockEnrollmentParams struct {
	CourseID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) LockEnrollment(ctx context.Context, arg LockEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, lockEnrollment, arg.CourseID, arg.UserID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.RoleInCourse,
		&i.Status,
		&i.JoinedVia,
		&i.StudentCodeSnapshot,
		&i.Warning,
		&i.PreviousStatus,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.RemovedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
update notifications set read_at = coalesce(read_at, now()) where id = $1 and user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Chỉ thông báo CỦA MÌNH (người khác ⇒ 0 dòng ⇒ 404). Đã đọc rồi vẫn tính là thành công (idempotent): giữ read_at đầu tiên.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const regenerateJoinCode = `-- name: RegenerateJoinCode :one
update courses
set join_code = $1, version = version + 1
where courses.id = $2 and courses.status = 'ACTIVE' and not exists (select 1 from courses o where o.join_code = $1)
returning id, subject_code, class_code, name, semester, status, escalation_threshold, settings, join_code, join_enabled, join_expires_at, join_require_approval, allowed_email_domain, capacity, created_by, archived_at, version, created_at, updated_at
`

type RegenerateJoinCodeParams struct {
	JoinCode string
	ID       uuid.UUID
}

// Thay mã trong MỘT câu UPDATE (mã cũ chết ngay). Trùng mã mới ⇒ không dòng (người gọi thử mã khác, tối đa 5 lần).
func (q *Queries) RegenerateJoinCode(ctx context.Context, arg RegenerateJoinCodeParams) (Course, error) {
	row := q.db.QueryRow(ctx, regenerateJoinCode, arg.JoinCode, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SubjectCode,
		&i.ClassCode,
		&i.Name,
		&i.Semester,
		&i.Status,
		&i.EscalationThreshold,
		&i.Settings,
		&i.JoinCode,
		&i.JoinEnabled,
		&i.JoinExpiresAt,
		&i.JoinRequireApproval,
		&i.AllowedEmailDomain,
		&i.Capacity,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejoinEnrollment = `-- name: RejoinEnrollment :one
update enrollments
set status = 'PENDING', previous_status = 'REMOVED', warning = $1, status_changed_at = $2, status_changed_by = null, removed_at = null, version = version + 1
where id = $3 and status = 'REMOVED'
returning id, course_id, user_id, role_in_course, status, joined_via, student_code_snapshot, warning, previous_status, status_changed_at, status_changed_by, removed_at, version, created_at, updated_at
`

type RejoinEnrollmentParams struct {
	Warning *string
	At      time.Time
	ID      uuid.UUID
}

// Vào lại sau khi bị mời ra: CÙNG dòng, REMOVED → PENDING (mặc định an toàn, Q5); snapshot cũ giữ nguyên.
func (q *Queries) RejoinEnrollment(ctx context.Context, arg RejoinEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, rejoinEnrollment, arg.Warning, arg.At, arg.ID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.RoleInCourse,
		&i.Status,
		&i.JoinedVia,
		&i.StudentCodeSnapshot,
		&i.Warning,
		&i.PreviousStatus,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.RemovedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeStaffEnrollment = `-- name: RemoveStaffEnrollment :exec
update enrollments
set previous_status = status, status = 'REMOVED', status_changed_at = now(), status_changed_by = $1, removed_at = now(), version = version + 1
where course_id = $2 and user_id = $3 and role_in_course in ('TEACHER', 'TA') and status <> 'REMOVED'
`

type RemoveStaffEnrollmentParams struct {
	Actor    *uuid.UUID
	CourseID uuid.UUID
	UserID   uuid.UUID
}

// Gỡ giảng viên / TA: mất quyền ở yêu cầu kế tiếp (guard không cache).
func (q *Queries) RemoveStaffEnrollment(ctx context.Context, arg RemoveStaffEnrollmentParams) error {
	_, err := q.db.Exec(ctx, removeStaffEnrollment, arg.Actor, arg.CourseID, arg.UserID)
	return err
}

const setEnrollmentStatus = `-- name: SetEnrollmentStatus :one
update enrollments
set status = $1::enrollment_status,
    previous_status = $2::enrollment_status,
    status_changed_at = $3,
    status_changed_by = $4,
    removed_at = case when $1::enrollment_status = 'REMOVED' then $3::timestamptz else null end,
    version = version + 1
where id = $5
returning id, course_id, user_id, role_in_course, status, joined_via, student_code_snapshot, warning, previous_status, status_changed_at, status_changed_by, removed_at, version, created_at, updated_at
`

type SetEnrollmentStatusParams struct {
	Status   EnrollmentStatus
	Previous *EnrollmentStatus
	At       time.Time
	Actor    *uuid.UUID
	ID       uuid.UUID
}

// Đổi trạng thái một ghi danh (duyệt / từ chối / mời ra / hoàn tác). `previous` = trạng thái ghi vào previous_status (null = không hoàn tác được nữa).
func (q *Queries) SetEnrollmentStatus(ctx context.Context, arg SetEnrollmentStatusParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, setEnrollmentStatus,
		arg.Status,
		arg.Previous,
		arg.At,
		arg.Actor,
		arg.ID,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.RoleInCourse,
		&i.Status,
		&i.JoinedVia,
		&i.StudentCodeSnapshot,
		&i.Warning,
		&i.PreviousStatus,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.RemovedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
update courses
set subject_code = coalesce($1, subject_code),
    class_code = coalesce($2, class_code),
    name = coalesce($3, name),
    semester = coalesce($4, semester),
    capacity = case when $5::bool then $6::int else capacity end,
    version = version + 1
where id = $7 and version = $8
returning id, subject_code, class_code, name, semester, status, escalation_threshold, settings, join_code, join_enabled, join_expires_at, join_require_approval, allowed_email_domain, capacity, created_by, archived_at, version, created_at, updated_at
`

type UpdateCourseParams struct {
	SubjectCode *string
	ClassCode   *string
	Name        *string
	Semester    *string
	SetCapacity bool
	Capacity    *int32
	ID          uuid.UUID
	Version     int32
}

// Khoá lạc quan theo version; không dòng ⇒ sai version (người gọi đã khoá dòng nên đọc lại bản hiện hành).
func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.SubjectCode,
		arg.ClassCode,
		arg.Name,
		arg.Semester,
		arg.SetCapacity,
		arg.Capacity,
		arg.ID,
		arg.Version,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SubjectCode,
		&i.ClassCode,
		&i.Name,
		&i.Semester,
		&i.Status,
		&i.EscalationThreshold,
		&i.Settings,
		&i.JoinCode,
		&i.JoinEnabled,
		&i.JoinExpiresAt,
		&i.JoinRequireApproval,
		&i.AllowedEmailDomain,
		&i.Capacity,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJoinSettings = `-- name: UpdateJoinSettings :one
update courses
set join_enabled = coalesce($1, join_enabled),
    join_require_approval = coalesce($2, join_require_approval),
    join_expires_at = case when $3::bool then $4::timestamptz else join_expires_at end,
    allowed_email_domain = case when $5::bool then $6::text else allowed_email_domain end,
    capacity = case when $7::bool then $8::int else capacity end,
    version = version + 1
where id = $9 and version = $10
returning id, subject_code, class_code, name, semester, status, escalation_threshold, settings, join_code, join_enabled, join_expires_at, join_require_approval, allowed_email_domain, capacity, created_by, archived_at, version, created_at, updated_at
`

type UpdateJoinSettingsParams struct {
	Enabled         *bool
	RequireApproval *bool
	SetExpires      bool
	ExpiresAt       *time.Time
	SetDomain       bool
	Domain          *string
	SetCapacity     bool
	Capacity        *int32
	ID              uuid.UUID
	Version         int32
}

func (q *Queries) UpdateJoinSettings(ctx context.Context, arg UpdateJoinSettingsParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateJoinSettings,
		arg.Enabled,
		arg.RequireApproval,
		arg.SetExpires,
		arg.ExpiresAt,
		arg.SetDomain,
		arg.Domain,
		arg.SetCapacity,
		arg.Capacity,
		arg.ID,
		arg.Version,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SubjectCode,
		&i.ClassCode,
		&i.Name,
		&i.Semester,
		&i.Status,
		&i.EscalationThreshold,
		&i.Settings,
		&i.JoinCode,
		&i.JoinEnabled,
		&i.JoinExpiresAt,
		&i.JoinRequireApproval,
		&i.AllowedEmailDomain,
		&i.Capacity,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
