// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const chunksForCourse = `-- name: ChunksForCourse :many
select id, document_id, text, audience
from content_chunks
where course_ids @> array[$1::uuid]
order by id
limit $2
`

type ChunksForCourseParams struct {
	CourseID uuid.UUID
	Lim      int32
}

type ChunksForCourseRow struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
	Text       string
	Audience   ChunkAudience
}

// Đường DUY NHẤT đọc content_chunks ở P2: luôn lọc theo lớp (course_ids, GIN). Không có hàm đọc chunk "không lọc lớp".
func (q *Queries) ChunksForCourse(ctx context.Context, arg ChunksForCourseParams) ([]ChunksForCourseRow, error) {
	rows, err := q.db.Query(ctx, chunksForCourse, arg.CourseID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChunksForCourseRow{}
	for rows.Next() {
		var i ChunksForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Text,
			&i.Audience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCourseStudents = `-- name: CountCourseStudents :one
select count(*) filter (where status = 'ACTIVE')::int as active, count(*) filter (where status = 'PENDING')::int as pending
from enrollments
where course_id = $1 and role_in_course = 'STUDENT'
`

type CountCourseStudentsRow struct {
	Active  int32
	Pending int32
}

func (q *Queries) CountCourseStudents(ctx context.Context, courseID uuid.UUID) (CountCourseStudentsRow, error) {
	row := q.db.QueryRow(ctx, countCourseStudents, courseID)
	var i CountCourseStudentsRow
	err := row.Scan(&i.Active, &i.Pending)
	return i, err
}

const getCourseBasic = `-- name: GetCourseBasic :one
select id, class_code, subject_code, name, semester, status from courses where id = $1
`

type GetCourseBasicRow struct {
	ID          uuid.UUID
	ClassCode   string
	SubjectCode string
	Name        string
	Semester    string
	Status      CourseStatus
}

func (q *Queries) GetCourseBasic(ctx context.Context, id uuid.UUID) (GetCourseBasicRow, error) {
	row := q.db.QueryRow(ctx, getCourseBasic, id)
	var i GetCourseBasicRow
	err := row.Scan(
		&i.ID,
		&i.ClassCode,
		&i.SubjectCode,
		&i.Name,
		&i.Semester,
		&i.Status,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one

select role_in_course, status from enrollments where course_id = $1 and user_id = $2
`

type GetMembershipParams struct {
	CourseID uuid.UUID
	UserID   uuid.UUID
}

type GetMembershipRow struct {
	RoleInCourse EnrollmentRole
	Status       EnrollmentStatus
}

// Lớp học: tra quyền và đọc (FEAT-course-foundation US-P2-07). Mọi truy vấn của bảng thuộc lớp bắt đầu bằng course_id (luật 13).
// CourseAccessGuard: MỘT truy vấn theo chỉ mục (course_id, user_id), không cache.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.CourseID, arg.UserID)
	var i GetMembershipRow
	err := row.Scan(&i.RoleInCourse, &i.Status)
	return i, err
}

const listCourseTeacherNames = `-- name: ListCourseTeacherNames :many
select u.full_name
from enrollments e
join users u on u.id = e.user_id
where e.course_id = $1 and e.role_in_course = 'TEACHER' and e.status = 'ACTIVE'
order by u.full_name
`

func (q *Queries) ListCourseTeacherNames(ctx context.Context, courseID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listCourseTeacherNames, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var full_name string
		if err := rows.Scan(&full_name); err != nil {
			return nil, err
		}
		items = append(items, full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCourses = `-- name: ListMyCourses :many
select c.id, c.class_code, c.subject_code, c.name, c.semester, c.status as course_status,
       e.role_in_course, e.status as enrollment_status, e.created_at as enrolled_at, e.id as enrollment_id
from enrollments e
join courses c on c.id = e.course_id
where e.user_id = $1
  and (e.status = 'ACTIVE' or (e.status = 'PENDING' and e.role_in_course = 'STUDENT'))
  and ($2::timestamptz is null or (e.created_at, e.id) < ($2::timestamptz, $3::uuid))
order by e.created_at desc, e.id desc
limit $4
`

type ListMyCoursesParams struct {
	UserID uuid.UUID
	CurAt  *time.Time
	CurID  *uuid.UUID
	Lim    int32
}

type ListMyCoursesRow struct {
	ID               uuid.UUID
	ClassCode        string
	SubjectCode      string
	Name             string
	Semester         string
	CourseStatus     CourseStatus
	RoleInCourse     EnrollmentRole
	EnrollmentStatus EnrollmentStatus
	EnrolledAt       time.Time
	EnrollmentID     uuid.UUID
}

// Sinh viên: lớp ACTIVE và PENDING của chính mình; Giảng viên / TA: lớp được phân công (ACTIVE). Một truy vấn, không N+1.
func (q *Queries) ListMyCourses(ctx context.Context, arg ListMyCoursesParams) ([]ListMyCoursesRow, error) {
	rows, err := q.db.Query(ctx, listMyCourses,
		arg.UserID,
		arg.CurAt,
		arg.CurID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyCoursesRow{}
	for rows.Next() {
		var i ListMyCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassCode,
			&i.SubjectCode,
			&i.Name,
			&i.Semester,
			&i.CourseStatus,
			&i.RoleInCourse,
			&i.EnrollmentStatus,
			&i.EnrolledAt,
			&i.EnrollmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
