// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const docCourseStatus = `-- name: DocCourseStatus :one

select status from courses where id = $1
`

// Tài liệu của lớp (US-P8-01: tải lên / hoàn tất / thử lại). Mọi truy vấn bắt đầu từ course_id (luật 13).
func (q *Queries) DocCourseStatus(ctx context.Context, id uuid.UUID) (CourseStatus, error) {
	row := q.db.QueryRow(ctx, docCourseStatus, id)
	var status CourseStatus
	err := row.Scan(&status)
	return status, err
}

const docFindDuplicateElsewhere = `-- name: DocFindDuplicateElsewhere :one
select d.id, c.class_code
from documents d
join courses c on c.id = d.course_id
join enrollments e on e.course_id = d.course_id and e.user_id = $1 and e.role_in_course in ('TEACHER', 'TA') and e.status = 'ACTIVE'
where d.sha256 = $2 and d.course_id <> $3
order by d.created_at limit 1
`

type DocFindDuplicateElsewhereParams struct {
	UserID   uuid.UUID
	Sha256   *string
	CourseID uuid.UUID
}

type DocFindDuplicateElsewhereRow struct {
	ID        uuid.UUID
	ClassCode string
}

// Cùng băm ở lớp KHÁC mà người gọi là Staff ACTIVE (lớp không thuộc người gọi: coi như không trùng — không lộ).
func (q *Queries) DocFindDuplicateElsewhere(ctx context.Context, arg DocFindDuplicateElsewhereParams) (DocFindDuplicateElsewhereRow, error) {
	row := q.db.QueryRow(ctx, docFindDuplicateElsewhere, arg.UserID, arg.Sha256, arg.CourseID)
	var i DocFindDuplicateElsewhereRow
	err := row.Scan(&i.ID, &i.ClassCode)
	return i, err
}

const docFindDuplicateInCourse = `-- name: DocFindDuplicateInCourse :one
select d.id from documents d
where d.sha256 = $1
  and (d.course_id = $2 or exists (select 1 from document_courses dc where dc.document_id = d.id and dc.course_id = $2))
order by d.created_at limit 1
`

type DocFindDuplicateInCourseParams struct {
	Sha256   *string
	CourseID uuid.UUID
}

// Cùng băm ở CÙNG lớp, kể cả tài liệu được chia sẻ vào lớp.
func (q *Queries) DocFindDuplicateInCourse(ctx context.Context, arg DocFindDuplicateInCourseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, docFindDuplicateInCourse, arg.Sha256, arg.CourseID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const docGetInCourse = `-- name: DocGetInCourse :one
select d.id, d.course_id, d.title, d.type, d.filename, d.mime_type, d.size_bytes, d.sha256, d.blob_key, d.status, d.error, d.page_count, d.visible_to_students, d.use_for_rag, d.category, d.week_no, d.download_count, d.uploaded_by, d.version, d.created_at, d.updated_at from documents d
where d.id = $1
  and (d.course_id = $2 or exists (select 1 from document_courses dc where dc.document_id = d.id and dc.course_id = $2))
`

type DocGetInCourseParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

// Tài liệu thuộc lớp (của lớp hoặc được chia sẻ vào lớp).
func (q *Queries) DocGetInCourse(ctx context.Context, arg DocGetInCourseParams) (Document, error) {
	row := q.db.QueryRow(ctx, docGetInCourse, arg.ID, arg.CourseID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Type,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.BlobKey,
		&i.Status,
		&i.Error,
		&i.PageCount,
		&i.VisibleToStudents,
		&i.UseForRag,
		&i.Category,
		&i.WeekNo,
		&i.DownloadCount,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const docInsert = `-- name: DocInsert :one
insert into documents (course_id, title, type, filename, mime_type, size_bytes, sha256, blob_key, status, visible_to_students, use_for_rag, category, week_no, uploaded_by)
values ($1, $2, $3, $4, $5, $6, $7, $8,
        'QUEUED', $9, $10, $11, $12, $13)
returning id, course_id, title, type, filename, mime_type, size_bytes, sha256, blob_key, status, error, page_count, visible_to_students, use_for_rag, category, week_no, download_count, uploaded_by, version, created_at, updated_at
`

type DocInsertParams struct {
	CourseID          uuid.UUID
	Title             string
	Type              DocumentType
	Filename          *string
	MimeType          *string
	SizeBytes         *int64
	Sha256            *string
	BlobKey           *string
	VisibleToStudents bool
	UseForRag         bool
	Category          *string
	WeekNo            *int16
	UploadedBy        *uuid.UUID
}

func (q *Queries) DocInsert(ctx context.Context, arg DocInsertParams) (Document, error) {
	row := q.db.QueryRow(ctx, docInsert,
		arg.CourseID,
		arg.Title,
		arg.Type,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.BlobKey,
		arg.VisibleToStudents,
		arg.UseForRag,
		arg.Category,
		arg.WeekNo,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Type,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.BlobKey,
		&i.Status,
		&i.Error,
		&i.PageCount,
		&i.VisibleToStudents,
		&i.UseForRag,
		&i.Category,
		&i.WeekNo,
		&i.DownloadCount,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const docLockHash = `-- name: DocLockHash :exec
select pg_advisory_xact_lock(hashtextextended($1::text || $2::text, 0))
`

type DocLockHashParams struct {
	CourseID string
	Sha256   string
}

// Khoá tư vấn trong giao dịch: hai complete song song cùng tệp (khác Idempotency-Key) → đúng một dòng documents.
func (q *Queries) DocLockHash(ctx context.Context, arg DocLockHashParams) error {
	_, err := q.db.Exec(ctx, docLockHash, arg.CourseID, arg.Sha256)
	return err
}

const docRetry = `-- name: DocRetry :one
update documents set status = 'QUEUED', error = null
where id = $1 and course_id = $2 and status = 'FAILED'
returning id, course_id, title, type, filename, mime_type, size_bytes, sha256, blob_key, status, error, page_count, visible_to_students, use_for_rag, category, week_no, download_count, uploaded_by, version, created_at, updated_at
`

type DocRetryParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

// FAILED → QUEUED (chỉ tài liệu của chính lớp này).
func (q *Queries) DocRetry(ctx context.Context, arg DocRetryParams) (Document, error) {
	row := q.db.QueryRow(ctx, docRetry, arg.ID, arg.CourseID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Type,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.BlobKey,
		&i.Status,
		&i.Error,
		&i.PageCount,
		&i.VisibleToStudents,
		&i.UseForRag,
		&i.Category,
		&i.WeekNo,
		&i.DownloadCount,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
