// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_attempt.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const answersDelete = `-- name: AnswersDelete :exec
delete from exam_answers where course_id = $1 and attempt_id = $2 and item_id = any($3::text[]::uuid[])
`

type AnswersDeleteParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
	ItemIds   []string
}

// Mảng rỗng = xoá lựa chọn (câu coi như chưa trả lời).
func (q *Queries) AnswersDelete(ctx context.Context, arg AnswersDeleteParams) error {
	_, err := q.db.Exec(ctx, answersDelete, arg.CourseID, arg.AttemptID, arg.ItemIds)
	return err
}

const answersList = `-- name: AnswersList :many
select item_id, answer from exam_answers where course_id = $1 and attempt_id = $2
`

type AnswersListParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
}

type AnswersListRow struct {
	ItemID uuid.UUID
	Answer json.RawMessage
}

func (q *Queries) AnswersList(ctx context.Context, arg AnswersListParams) ([]AnswersListRow, error) {
	rows, err := q.db.Query(ctx, answersList, arg.CourseID, arg.AttemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnswersListRow{}
	for rows.Next() {
		var i AnswersListRow
		if err := rows.Scan(&i.ItemID, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const answersUpsert = `-- name: AnswersUpsert :exec
insert into exam_answers (attempt_id, item_id, course_id, answer, saved_at)
select $1, x.item_id, $2, x.answer, $3
from jsonb_to_recordset($4::jsonb) as x(item_id uuid, answer jsonb)
on conflict (attempt_id, item_id) do update set answer = excluded.answer, saved_at = excluded.saved_at
`

type AnswersUpsertParams struct {
	AttemptID uuid.UUID
	CourseID  uuid.UUID
	SavedAt   time.Time
	Rows      json.RawMessage
}

// Một lệnh cho cả lô (SRS 4.3.3): `rows` = [{"item_id":…,"answer":{…}}].
func (q *Queries) AnswersUpsert(ctx context.Context, arg AnswersUpsertParams) error {
	_, err := q.db.Exec(ctx, answersUpsert,
		arg.AttemptID,
		arg.CourseID,
		arg.SavedAt,
		arg.Rows,
	)
	return err
}

const attemptByStudent = `-- name: AttemptByStudent :one
select id, course_id, exam_id, student_id, status, started_at, deadline_at, submitted_at, submit_reason, writer_tab, writer_seen_at, auto_score, adjusted_score, adjusted_reason, adjusted_by, adjusted_at, breakdown, graded_at, version, created_at, updated_at from exam_attempts where course_id = $1 and exam_id = $2 and student_id = $3
`

type AttemptByStudentParams struct {
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) AttemptByStudent(ctx context.Context, arg AttemptByStudentParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, attemptByStudent, arg.CourseID, arg.ExamID, arg.StudentID)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamID,
		&i.StudentID,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.SubmitReason,
		&i.WriterTab,
		&i.WriterSeenAt,
		&i.AutoScore,
		&i.AdjustedScore,
		&i.AdjustedReason,
		&i.AdjustedBy,
		&i.AdjustedAt,
		&i.Breakdown,
		&i.GradedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attemptCountsByAnswer = `-- name: AttemptCountsByAnswer :one
select count(*)::int as answered from exam_answers where course_id = $1 and attempt_id = $2
`

type AttemptCountsByAnswerParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
}

func (q *Queries) AttemptCountsByAnswer(ctx context.Context, arg AttemptCountsByAnswerParams) (int32, error) {
	row := q.db.QueryRow(ctx, attemptCountsByAnswer, arg.CourseID, arg.AttemptID)
	var answered int32
	err := row.Scan(&answered)
	return answered, err
}

const attemptFinish = `-- name: AttemptFinish :one
update exam_attempts
set status = $1, submitted_at = $2, submit_reason = $3,
    auto_score = $4, graded_at = $5, breakdown = $6, version = version + 1
where course_id = $7 and id = $8 and status = 'IN_PROGRESS'
returning id, course_id, exam_id, student_id, status, started_at, deadline_at, submitted_at, submit_reason, writer_tab, writer_seen_at, auto_score, adjusted_score, adjusted_reason, adjusted_by, adjusted_at, breakdown, graded_at, version, created_at, updated_at
`

type AttemptFinishParams struct {
	Status       AttemptStatus
	SubmittedAt  *time.Time
	SubmitReason *AttemptSubmitReason
	AutoScore    decimal.NullDecimal
	GradedAt     *time.Time
	Breakdown    json.RawMessage
	CourseID     uuid.UUID
	ID           uuid.UUID
}

// `where status = 'IN_PROGRESS'`: nộp lần hai (hoặc tick chạy song song) không tìm thấy dòng → đã nộp, idempotent.
func (q *Queries) AttemptFinish(ctx context.Context, arg AttemptFinishParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, attemptFinish,
		arg.Status,
		arg.SubmittedAt,
		arg.SubmitReason,
		arg.AutoScore,
		arg.GradedAt,
		arg.Breakdown,
		arg.CourseID,
		arg.ID,
	)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamID,
		&i.StudentID,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.SubmitReason,
		&i.WriterTab,
		&i.WriterSeenAt,
		&i.AutoScore,
		&i.AdjustedScore,
		&i.AdjustedReason,
		&i.AdjustedBy,
		&i.AdjustedAt,
		&i.Breakdown,
		&i.GradedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attemptInsert = `-- name: AttemptInsert :one

insert into exam_attempts (course_id, exam_id, student_id, started_at, deadline_at, writer_tab, writer_seen_at)
values ($1, $2, $3, $4, $5, $6, $4)
on conflict (exam_id, student_id) do nothing
returning id, course_id, exam_id, student_id, status, started_at, deadline_at, submitted_at, submit_reason, writer_tab, writer_seen_at, auto_score, adjusted_score, adjusted_reason, adjusted_by, adjusted_at, breakdown, graded_at, version, created_at, updated_at
`

type AttemptInsertParams struct {
	CourseID   uuid.UUID
	ExamID     uuid.UUID
	StudentID  uuid.UUID
	StartedAt  time.Time
	DeadlineAt time.Time
	WriterTab  *uuid.UUID
}

// Lượt làm của sinh viên (US-PE-05, SRS FEAT-weekly-exam 5.8–5.9, 4.3). Mọi truy vấn bắt đầu bằng course_id (luật 13).
// Hai yêu cầu bắt đầu song song cho đúng MỘT dòng nhờ UNIQUE(exam_id, student_id); 0 dòng trả về = đã có lượt.
func (q *Queries) AttemptInsert(ctx context.Context, arg AttemptInsertParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, attemptInsert,
		arg.CourseID,
		arg.ExamID,
		arg.StudentID,
		arg.StartedAt,
		arg.DeadlineAt,
		arg.WriterTab,
	)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamID,
		&i.StudentID,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.SubmitReason,
		&i.WriterTab,
		&i.WriterSeenAt,
		&i.AutoScore,
		&i.AdjustedScore,
		&i.AdjustedReason,
		&i.AdjustedBy,
		&i.AdjustedAt,
		&i.Breakdown,
		&i.GradedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attemptLock = `-- name: AttemptLock :one
select id, course_id, exam_id, student_id, status, started_at, deadline_at, submitted_at, submit_reason, writer_tab, writer_seen_at, auto_score, adjusted_score, adjusted_reason, adjusted_by, adjusted_at, breakdown, graded_at, version, created_at, updated_at from exam_attempts
where course_id = $1 and exam_id = $2 and id = $3 and student_id = $4
for update
`

type AttemptLockParams struct {
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	ID        uuid.UUID
	StudentID uuid.UUID
}

// Lượt của CHÍNH sinh viên (người khác → không có dòng → 404), khoá hàng để kiểm trạng thái / người ghi.
func (q *Queries) AttemptLock(ctx context.Context, arg AttemptLockParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, attemptLock,
		arg.CourseID,
		arg.ExamID,
		arg.ID,
		arg.StudentID,
	)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamID,
		&i.StudentID,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.SubmitReason,
		&i.WriterTab,
		&i.WriterSeenAt,
		&i.AutoScore,
		&i.AdjustedScore,
		&i.AdjustedReason,
		&i.AdjustedBy,
		&i.AdjustedAt,
		&i.Breakdown,
		&i.GradedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attemptLockByID = `-- name: AttemptLockByID :one
select id, course_id, exam_id, student_id, status, started_at, deadline_at, submitted_at, submit_reason, writer_tab, writer_seen_at, auto_score, adjusted_score, adjusted_reason, adjusted_by, adjusted_at, breakdown, graded_at, version, created_at, updated_at from exam_attempts where course_id = $1 and id = $2 for update
`

type AttemptLockByIDParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) AttemptLockByID(ctx context.Context, arg AttemptLockByIDParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, attemptLockByID, arg.CourseID, arg.ID)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamID,
		&i.StudentID,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.SubmitReason,
		&i.WriterTab,
		&i.WriterSeenAt,
		&i.AutoScore,
		&i.AdjustedScore,
		&i.AdjustedReason,
		&i.AdjustedBy,
		&i.AdjustedAt,
		&i.Breakdown,
		&i.GradedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attemptOwn = `-- name: AttemptOwn :one
select id, course_id, exam_id, student_id, status, started_at, deadline_at, submitted_at, submit_reason, writer_tab, writer_seen_at, auto_score, adjusted_score, adjusted_reason, adjusted_by, adjusted_at, breakdown, graded_at, version, created_at, updated_at from exam_attempts
where course_id = $1 and exam_id = $2 and id = $3 and student_id = $4
`

type AttemptOwnParams struct {
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	ID        uuid.UUID
	StudentID uuid.UUID
}

// Đọc (không khoá) lượt của CHÍNH sinh viên; người khác → không có dòng → 404.
func (q *Queries) AttemptOwn(ctx context.Context, arg AttemptOwnParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, attemptOwn,
		arg.CourseID,
		arg.ExamID,
		arg.ID,
		arg.StudentID,
	)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamID,
		&i.StudentID,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.SubmitReason,
		&i.WriterTab,
		&i.WriterSeenAt,
		&i.AutoScore,
		&i.AdjustedScore,
		&i.AdjustedReason,
		&i.AdjustedBy,
		&i.AdjustedAt,
		&i.Breakdown,
		&i.GradedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attemptSetWriter = `-- name: AttemptSetWriter :exec
update exam_attempts set writer_tab = $1, writer_seen_at = $2
where course_id = $3 and id = $4
`

type AttemptSetWriterParams struct {
	WriterTab *uuid.UUID
	SeenAt    *time.Time
	CourseID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) AttemptSetWriter(ctx context.Context, arg AttemptSetWriterParams) error {
	_, err := q.db.Exec(ctx, attemptSetWriter,
		arg.WriterTab,
		arg.SeenAt,
		arg.CourseID,
		arg.ID,
	)
	return err
}

const attemptsDue = `-- name: AttemptsDue :many
select a.id, a.course_id, a.exam_id, a.student_id, a.deadline_at, (a.deadline_at >= e.closes_at)::boolean as by_close
from exam_attempts a
join exams e on e.course_id = a.course_id and e.id = a.exam_id
where a.status = 'IN_PROGRESS' and a.deadline_at + make_interval(secs => $1::int) < $2::timestamptz
order by a.deadline_at, a.id
limit 200
`

type AttemptsDueParams struct {
	GraceSeconds int32
	Now          time.Time
}

type AttemptsDueRow struct {
	ID         uuid.UUID
	CourseID   uuid.UUID
	ExamID     uuid.UUID
	StudentID  uuid.UUID
	DeadlineAt time.Time
	ByClose    bool
}

// Lượt IN_PROGRESS đã quá deadline + grace (lô 200). `by_close`: hạn do giờ đóng của lớp (CLOSED) hay do thời lượng (TIMEOUT).
func (q *Queries) AttemptsDue(ctx context.Context, arg AttemptsDueParams) ([]AttemptsDueRow, error) {
	rows, err := q.db.Query(ctx, attemptsDue, arg.GraceSeconds, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptsDueRow{}
	for rows.Next() {
		var i AttemptsDueRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ExamID,
			&i.StudentID,
			&i.DeadlineAt,
			&i.ByClose,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examEventInsert = `-- name: ExamEventInsert :exec
insert into exam_events (course_id, exam_id, attempt_id, student_id, type, meta)
values ($1, $2, $3, $4, $5, $6)
`

type ExamEventInsertParams struct {
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	AttemptID uuid.UUID
	StudentID uuid.UUID
	Type      ExamEventType
	Meta      json.RawMessage
}

func (q *Queries) ExamEventInsert(ctx context.Context, arg ExamEventInsertParams) error {
	_, err := q.db.Exec(ctx, examEventInsert,
		arg.CourseID,
		arg.ExamID,
		arg.AttemptID,
		arg.StudentID,
		arg.Type,
		arg.Meta,
	)
	return err
}

const examGradeItems = `-- name: ExamGradeItems :many
select i.id as item_id, i.question_id, i.points, i.override, q.type, q.answer_key
from exam_items i
join question_bank q on q.course_id = i.course_id and q.id = i.question_id
where i.course_id = $1 and i.exam_id = $2
order by i.position
`

type ExamGradeItemsParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type ExamGradeItemsRow struct {
	ItemID     uuid.UUID
	QuestionID uuid.UUID
	Points     decimal.Decimal
	Override   json.RawMessage
	Type       QuestionType
	AnswerKey  json.RawMessage
}

// Mục kèm đáp án đúng và `override` để chấm (CHỈ dùng ở phía máy chủ khi chấm — không bao giờ vào DTO sinh viên).
func (q *Queries) ExamGradeItems(ctx context.Context, arg ExamGradeItemsParams) ([]ExamGradeItemsRow, error) {
	rows, err := q.db.Query(ctx, examGradeItems, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamGradeItemsRow{}
	for rows.Next() {
		var i ExamGradeItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.QuestionID,
			&i.Points,
			&i.Override,
			&i.Type,
			&i.AnswerKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
