// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_code.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const codeDraftGet = `-- name: CodeDraftGet :one
select language, source, rev, updated_at from code_drafts
where course_id = $1 and attempt_id = $2 and item_id = $3 and language = $4
`

type CodeDraftGetParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
	ItemID    uuid.UUID
	Language  string
}

type CodeDraftGetRow struct {
	Language  string
	Source    string
	Rev       int32
	UpdatedAt time.Time
}

func (q *Queries) CodeDraftGet(ctx context.Context, arg CodeDraftGetParams) (CodeDraftGetRow, error) {
	row := q.db.QueryRow(ctx, codeDraftGet,
		arg.CourseID,
		arg.AttemptID,
		arg.ItemID,
		arg.Language,
	)
	var i CodeDraftGetRow
	err := row.Scan(
		&i.Language,
		&i.Source,
		&i.Rev,
		&i.UpdatedAt,
	)
	return i, err
}

const codeDraftLatest = `-- name: CodeDraftLatest :one
select language, source from code_drafts
where course_id = $1 and attempt_id = $2 and item_id = $3
order by updated_at desc, language
limit 1
`

type CodeDraftLatestParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
	ItemID    uuid.UUID
}

type CodeDraftLatestRow struct {
	Language string
	Source   string
}

// Bản nháp có `updated_at` lớn nhất của câu (một bản duy nhất — SRS 4.4.5, góp ý #2 (b)).
func (q *Queries) CodeDraftLatest(ctx context.Context, arg CodeDraftLatestParams) (CodeDraftLatestRow, error) {
	row := q.db.QueryRow(ctx, codeDraftLatest, arg.CourseID, arg.AttemptID, arg.ItemID)
	var i CodeDraftLatestRow
	err := row.Scan(&i.Language, &i.Source)
	return i, err
}

const codeDraftUpsert = `-- name: CodeDraftUpsert :one
insert into code_drafts (attempt_id, item_id, course_id, language, source, rev, updated_at)
values ($1, $2, $3, $4, $5, 1, $6)
on conflict (attempt_id, item_id, language) do update set source = excluded.source, rev = code_drafts.rev + 1, updated_at = excluded.updated_at
returning rev, updated_at
`

type CodeDraftUpsertParams struct {
	AttemptID uuid.UUID
	ItemID    uuid.UUID
	CourseID  uuid.UUID
	Language  string
	Source    string
	At        time.Time
}

type CodeDraftUpsertRow struct {
	Rev       int32
	UpdatedAt time.Time
}

// Gọi sau khi đã kiểm `base_rev` (lượt đã bị khoá `for update`, nên không có hai bản ghi chen nhau). `rev` tăng 1 mỗi lần ghi.
func (q *Queries) CodeDraftUpsert(ctx context.Context, arg CodeDraftUpsertParams) (CodeDraftUpsertRow, error) {
	row := q.db.QueryRow(ctx, codeDraftUpsert,
		arg.AttemptID,
		arg.ItemID,
		arg.CourseID,
		arg.Language,
		arg.Source,
		arg.At,
	)
	var i CodeDraftUpsertRow
	err := row.Scan(&i.Rev, &i.UpdatedAt)
	return i, err
}

const codeDraftsOfAttempt = `-- name: CodeDraftsOfAttempt :many
select item_id, language, source, rev, updated_at from code_drafts
where course_id = $1 and attempt_id = $2
order by item_id, updated_at desc
`

type CodeDraftsOfAttemptParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
}

type CodeDraftsOfAttemptRow struct {
	ItemID    uuid.UUID
	Language  string
	Source    string
	Rev       int32
	UpdatedAt time.Time
}

// Bản nháp của CHÍNH lượt này (trả lại khi mở / tải lại trang làm bài).
func (q *Queries) CodeDraftsOfAttempt(ctx context.Context, arg CodeDraftsOfAttemptParams) ([]CodeDraftsOfAttemptRow, error) {
	rows, err := q.db.Query(ctx, codeDraftsOfAttempt, arg.CourseID, arg.AttemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeDraftsOfAttemptRow{}
	for rows.Next() {
		var i CodeDraftsOfAttemptRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Language,
			&i.Source,
			&i.Rev,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const codeItemOfExam = `-- name: CodeItemOfExam :one

select i.id as item_id, i.question_id as problem_id, cp.languages
from exam_items i
join question_bank q on q.course_id = i.course_id and q.id = i.question_id and q.type = 'CODE'
join code_problems cp on cp.course_id = q.course_id and cp.question_id = q.id
where i.course_id = $1 and i.exam_id = $2 and i.id = $3
`

type CodeItemOfExamParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
	ItemID   uuid.UUID
}

type CodeItemOfExamRow struct {
	ItemID    uuid.UUID
	ProblemID uuid.UUID
	Languages []string
}

// Bài code trong lượt làm (US-PE-06, SRS FEAT-weekly-exam 4.4, 5.10–5.11). Mọi truy vấn bắt đầu bằng course_id (luật 13).
// Mục CODE của bài thi: `languages` để kiểm ngôn ngữ; không phải mục code → 0 dòng.
func (q *Queries) CodeItemOfExam(ctx context.Context, arg CodeItemOfExamParams) (CodeItemOfExamRow, error) {
	row := q.db.QueryRow(ctx, codeItemOfExam, arg.CourseID, arg.ExamID, arg.ItemID)
	var i CodeItemOfExamRow
	err := row.Scan(&i.ItemID, &i.ProblemID, &i.Languages)
	return i, err
}

const codeSamplesOfProblem = `-- name: CodeSamplesOfProblem :many
select id, name, input, expected from code_testcases
where course_id = $1 and problem_id = $2 and is_sample and approved and input is not null and expected is not null
order by position
`

type CodeSamplesOfProblemParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
}

type CodeSamplesOfProblemRow struct {
	ID       uuid.UUID
	Name     string
	Input    *string
	Expected *string
}

// Test MẪU đã duyệt (công khai theo định nghĩa); test lớn lưu ở kho (input NULL) không có ở đây.
func (q *Queries) CodeSamplesOfProblem(ctx context.Context, arg CodeSamplesOfProblemParams) ([]CodeSamplesOfProblemRow, error) {
	rows, err := q.db.Query(ctx, codeSamplesOfProblem, arg.CourseID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeSamplesOfProblemRow{}
	for rows.Next() {
		var i CodeSamplesOfProblemRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Input,
			&i.Expected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const codeSubmissionGetOwn = `-- name: CodeSubmissionGetOwn :one
select c.id, c.item_id, c.problem_id, c.kind, c.language, c.source, c.status, c.verdict, c.compile_ok, c.compile_log, c.results, c.auto, c.created_at,
       (c.kind = 'SUBMIT' and c.status <> 'SUPERSEDED' and not exists (
          select 1 from code_submissions n
          where n.course_id = c.course_id and n.attempt_id = c.attempt_id and n.item_id = c.item_id and n.kind = 'SUBMIT' and n.status <> 'SUPERSEDED'
            and (n.created_at, n.id) > (c.created_at, c.id)))::boolean as is_final
from code_submissions c
where c.course_id = $1 and c.exam_id = $2 and c.attempt_id = $3 and c.student_id = $4 and c.id = $5
  and c.kind = $6
`

type CodeSubmissionGetOwnParams struct {
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	AttemptID uuid.UUID
	StudentID uuid.UUID
	ID        uuid.UUID
	Kind      SubmissionKind
}

type CodeSubmissionGetOwnRow struct {
	ID         uuid.UUID
	ItemID     uuid.UUID
	ProblemID  uuid.UUID
	Kind       SubmissionKind
	Language   string
	Source     string
	Status     SubmissionStatus
	Verdict    *JudgeVerdict
	CompileOk  *bool
	CompileLog *string
	Results    json.RawMessage
	Auto       bool
	CreatedAt  time.Time
	IsFinal    bool
}

// Một bản nộp / chạy thử của CHÍNH sinh viên trong lượt này; người khác → 0 dòng → 404. `is_final`: bản SUBMIT mới nhất chưa bị thay.
func (q *Queries) CodeSubmissionGetOwn(ctx context.Context, arg CodeSubmissionGetOwnParams) (CodeSubmissionGetOwnRow, error) {
	row := q.db.QueryRow(ctx, codeSubmissionGetOwn,
		arg.CourseID,
		arg.ExamID,
		arg.AttemptID,
		arg.StudentID,
		arg.ID,
		arg.Kind,
	)
	var i CodeSubmissionGetOwnRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.ProblemID,
		&i.Kind,
		&i.Language,
		&i.Source,
		&i.Status,
		&i.Verdict,
		&i.CompileOk,
		&i.CompileLog,
		&i.Results,
		&i.Auto,
		&i.CreatedAt,
		&i.IsFinal,
	)
	return i, err
}

const codeSubmissionInsert = `-- name: CodeSubmissionInsert :one
insert into code_submissions (course_id, exam_id, attempt_id, item_id, problem_id, student_id, kind, language, source, source_sha256, auto)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11)
returning id, created_at
`

type CodeSubmissionInsertParams struct {
	CourseID     uuid.UUID
	ExamID       uuid.UUID
	AttemptID    uuid.UUID
	ItemID       uuid.UUID
	ProblemID    uuid.UUID
	StudentID    uuid.UUID
	Kind         SubmissionKind
	Language     string
	Source       string
	SourceSha256 string
	Auto         bool
}

type CodeSubmissionInsertRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CodeSubmissionInsert(ctx context.Context, arg CodeSubmissionInsertParams) (CodeSubmissionInsertRow, error) {
	row := q.db.QueryRow(ctx, codeSubmissionInsert,
		arg.CourseID,
		arg.ExamID,
		arg.AttemptID,
		arg.ItemID,
		arg.ProblemID,
		arg.StudentID,
		arg.Kind,
		arg.Language,
		arg.Source,
		arg.SourceSha256,
		arg.Auto,
	)
	var i CodeSubmissionInsertRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const codeSubmissionStudent = `-- name: CodeSubmissionStudent :one
select student_id, course_id, kind, status, item_id, attempt_id from code_submissions where id = $1
`

type CodeSubmissionStudentRow struct {
	StudentID uuid.UUID
	CourseID  uuid.UUID
	Kind      SubmissionKind
	Status    SubmissionStatus
	ItemID    uuid.UUID
	AttemptID uuid.UUID
}

// Chủ của bản nộp: worker dùng để phát SSE tới đúng người (không đưa danh tính vào payload outbox của máy chấm).
func (q *Queries) CodeSubmissionStudent(ctx context.Context, id uuid.UUID) (CodeSubmissionStudentRow, error) {
	row := q.db.QueryRow(ctx, codeSubmissionStudent, id)
	var i CodeSubmissionStudentRow
	err := row.Scan(
		&i.StudentID,
		&i.CourseID,
		&i.Kind,
		&i.Status,
		&i.ItemID,
		&i.AttemptID,
	)
	return i, err
}

const codeSubmissionsListOwn = `-- name: CodeSubmissionsListOwn :many
select c.id, c.item_id, c.problem_id, c.kind, c.language, c.status, c.verdict, c.compile_ok, c.compile_log, c.results, c.auto, c.created_at,
       (c.status <> 'SUPERSEDED' and not exists (
          select 1 from code_submissions n
          where n.course_id = c.course_id and n.attempt_id = c.attempt_id and n.item_id = c.item_id and n.kind = 'SUBMIT' and n.status <> 'SUPERSEDED'
            and (n.created_at, n.id) > (c.created_at, c.id)))::boolean as is_final
from code_submissions c
where c.course_id = $1 and c.attempt_id = $2 and c.student_id = $3 and c.item_id = $4 and c.kind = 'SUBMIT'
  and ($5::timestamptz is null or (c.created_at, c.id) < ($5::timestamptz, $6::uuid))
order by c.created_at desc, c.id desc
limit $7
`

type CodeSubmissionsListOwnParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
	StudentID uuid.UUID
	ItemID    uuid.UUID
	CursorAt  *time.Time
	CursorID  *uuid.UUID
	RowLimit  int32
}

type CodeSubmissionsListOwnRow struct {
	ID         uuid.UUID
	ItemID     uuid.UUID
	ProblemID  uuid.UUID
	Kind       SubmissionKind
	Language   string
	Status     SubmissionStatus
	Verdict    *JudgeVerdict
	CompileOk  *bool
	CompileLog *string
	Results    json.RawMessage
	Auto       bool
	CreatedAt  time.Time
	IsFinal    bool
}

// Lịch sử nộp của (lượt, câu), mới nhất trước, cursor (created_at, id). Không lấy `source` (xem lại mã qua GET một bản).
func (q *Queries) CodeSubmissionsListOwn(ctx context.Context, arg CodeSubmissionsListOwnParams) ([]CodeSubmissionsListOwnRow, error) {
	rows, err := q.db.Query(ctx, codeSubmissionsListOwn,
		arg.CourseID,
		arg.AttemptID,
		arg.StudentID,
		arg.ItemID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeSubmissionsListOwnRow{}
	for rows.Next() {
		var i CodeSubmissionsListOwnRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.ProblemID,
			&i.Kind,
			&i.Language,
			&i.Status,
			&i.Verdict,
			&i.CompileOk,
			&i.CompileLog,
			&i.Results,
			&i.Auto,
			&i.CreatedAt,
			&i.IsFinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const codeSubmitCount = `-- name: CodeSubmitCount :one
select count(*)::int from code_submissions
where course_id = $1 and attempt_id = $2 and item_id = $3 and kind = 'SUBMIT'
`

type CodeSubmitCountParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
	ItemID    uuid.UUID
}

func (q *Queries) CodeSubmitCount(ctx context.Context, arg CodeSubmitCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, codeSubmitCount, arg.CourseID, arg.AttemptID, arg.ItemID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
