// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_question.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const codeProblemBumpTests = `-- name: CodeProblemBumpTests :one
update code_problems
set tests_version = tests_version + 1, reference_verified_version = null, reference_verified_at = null, updated_at = now()
where course_id = $1 and question_id = $2
returning question_id, course_id, languages, time_limit_ms, memory_limit_mb, output_limit_kb, checker, float_eps, starter_code, reference_language, reference_source, reference_verified_version, reference_verified_at, tests_version, created_at, updated_at
`

type CodeProblemBumpTestsParams struct {
	CourseID   uuid.UUID
	QuestionID uuid.UUID
}

// Mỗi thay đổi tập test: tests_version + 1, gỡ cờ lời giải mẫu đã kiểm.
func (q *Queries) CodeProblemBumpTests(ctx context.Context, arg CodeProblemBumpTestsParams) (CodeProblem, error) {
	row := q.db.QueryRow(ctx, codeProblemBumpTests, arg.CourseID, arg.QuestionID)
	var i CodeProblem
	err := row.Scan(
		&i.QuestionID,
		&i.CourseID,
		&i.Languages,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.OutputLimitKb,
		&i.Checker,
		&i.FloatEps,
		&i.StarterCode,
		&i.ReferenceLanguage,
		&i.ReferenceSource,
		&i.ReferenceVerifiedVersion,
		&i.ReferenceVerifiedAt,
		&i.TestsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const codeProblemGet = `-- name: CodeProblemGet :one
select question_id, course_id, languages, time_limit_ms, memory_limit_mb, output_limit_kb, checker, float_eps, starter_code, reference_language, reference_source, reference_verified_version, reference_verified_at, tests_version, created_at, updated_at from code_problems where course_id = $1 and question_id = $2
`

type CodeProblemGetParams struct {
	CourseID   uuid.UUID
	QuestionID uuid.UUID
}

func (q *Queries) CodeProblemGet(ctx context.Context, arg CodeProblemGetParams) (CodeProblem, error) {
	row := q.db.QueryRow(ctx, codeProblemGet, arg.CourseID, arg.QuestionID)
	var i CodeProblem
	err := row.Scan(
		&i.QuestionID,
		&i.CourseID,
		&i.Languages,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.OutputLimitKb,
		&i.Checker,
		&i.FloatEps,
		&i.StarterCode,
		&i.ReferenceLanguage,
		&i.ReferenceSource,
		&i.ReferenceVerifiedVersion,
		&i.ReferenceVerifiedAt,
		&i.TestsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const codeProblemInsert = `-- name: CodeProblemInsert :one
insert into code_problems (question_id, course_id) values ($1, $2) returning question_id, course_id, languages, time_limit_ms, memory_limit_mb, output_limit_kb, checker, float_eps, starter_code, reference_language, reference_source, reference_verified_version, reference_verified_at, tests_version, created_at, updated_at
`

type CodeProblemInsertParams struct {
	QuestionID uuid.UUID
	CourseID   uuid.UUID
}

func (q *Queries) CodeProblemInsert(ctx context.Context, arg CodeProblemInsertParams) (CodeProblem, error) {
	row := q.db.QueryRow(ctx, codeProblemInsert, arg.QuestionID, arg.CourseID)
	var i CodeProblem
	err := row.Scan(
		&i.QuestionID,
		&i.CourseID,
		&i.Languages,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.OutputLimitKb,
		&i.Checker,
		&i.FloatEps,
		&i.StarterCode,
		&i.ReferenceLanguage,
		&i.ReferenceSource,
		&i.ReferenceVerifiedVersion,
		&i.ReferenceVerifiedAt,
		&i.TestsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const codeProblemInsertFull = `-- name: CodeProblemInsertFull :one
insert into code_problems (question_id, course_id, languages, time_limit_ms, memory_limit_mb, output_limit_kb, checker, float_eps, starter_code, reference_language, reference_source)
values ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11)
returning question_id, course_id, languages, time_limit_ms, memory_limit_mb, output_limit_kb, checker, float_eps, starter_code, reference_language, reference_source, reference_verified_version, reference_verified_at, tests_version, created_at, updated_at
`

type CodeProblemInsertFullParams struct {
	QuestionID        uuid.UUID
	CourseID          uuid.UUID
	Languages         []string
	TimeLimitMs       int32
	MemoryLimitMb     int32
	OutputLimitKb     int32
	Checker           CheckerKind
	FloatEps          decimal.NullDecimal
	StarterCode       json.RawMessage
	ReferenceLanguage *string
	ReferenceSource   *string
}

func (q *Queries) CodeProblemInsertFull(ctx context.Context, arg CodeProblemInsertFullParams) (CodeProblem, error) {
	row := q.db.QueryRow(ctx, codeProblemInsertFull,
		arg.QuestionID,
		arg.CourseID,
		arg.Languages,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
		arg.OutputLimitKb,
		arg.Checker,
		arg.FloatEps,
		arg.StarterCode,
		arg.ReferenceLanguage,
		arg.ReferenceSource,
	)
	var i CodeProblem
	err := row.Scan(
		&i.QuestionID,
		&i.CourseID,
		&i.Languages,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.OutputLimitKb,
		&i.Checker,
		&i.FloatEps,
		&i.StarterCode,
		&i.ReferenceLanguage,
		&i.ReferenceSource,
		&i.ReferenceVerifiedVersion,
		&i.ReferenceVerifiedAt,
		&i.TestsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const codeProblemLock = `-- name: CodeProblemLock :one
select question_id, course_id, languages, time_limit_ms, memory_limit_mb, output_limit_kb, checker, float_eps, starter_code, reference_language, reference_source, reference_verified_version, reference_verified_at, tests_version, created_at, updated_at from code_problems where course_id = $1 and question_id = $2 for update
`

type CodeProblemLockParams struct {
	CourseID   uuid.UUID
	QuestionID uuid.UUID
}

func (q *Queries) CodeProblemLock(ctx context.Context, arg CodeProblemLockParams) (CodeProblem, error) {
	row := q.db.QueryRow(ctx, codeProblemLock, arg.CourseID, arg.QuestionID)
	var i CodeProblem
	err := row.Scan(
		&i.QuestionID,
		&i.CourseID,
		&i.Languages,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.OutputLimitKb,
		&i.Checker,
		&i.FloatEps,
		&i.StarterCode,
		&i.ReferenceLanguage,
		&i.ReferenceSource,
		&i.ReferenceVerifiedVersion,
		&i.ReferenceVerifiedAt,
		&i.TestsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const codeProblemMarkVerified = `-- name: CodeProblemMarkVerified :execrows
update code_problems set reference_verified_version = tests_version, reference_verified_at = now(), updated_at = now()
where course_id = $1 and question_id = $2 and tests_version = $3
`

type CodeProblemMarkVerifiedParams struct {
	CourseID     uuid.UUID
	QuestionID   uuid.UUID
	TestsVersion int32
}

// Chỉ ghi cờ khi tests_version chưa đổi từ lúc job bắt đầu (job chạy trên bản test cũ không được "xác minh" bản mới).
func (q *Queries) CodeProblemMarkVerified(ctx context.Context, arg CodeProblemMarkVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, codeProblemMarkVerified, arg.CourseID, arg.QuestionID, arg.TestsVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const codeProblemUpdate = `-- name: CodeProblemUpdate :one
update code_problems
set languages = $1, time_limit_ms = $2, memory_limit_mb = $3, output_limit_kb = $4,
    checker = $5, float_eps = $6, starter_code = $7,
    reference_language = $8, reference_source = $9,
    tests_version = tests_version + case when $10::boolean then 1 else 0 end,
    reference_verified_version = case when $10::boolean or $11::boolean then null else reference_verified_version end,
    reference_verified_at = case when $10::boolean or $11::boolean then null else reference_verified_at end,
    updated_at = now()
where course_id = $12 and question_id = $13
returning question_id, course_id, languages, time_limit_ms, memory_limit_mb, output_limit_kb, checker, float_eps, starter_code, reference_language, reference_source, reference_verified_version, reference_verified_at, tests_version, created_at, updated_at
`

type CodeProblemUpdateParams struct {
	Languages         []string
	TimeLimitMs       int32
	MemoryLimitMb     int32
	OutputLimitKb     int32
	Checker           CheckerKind
	FloatEps          decimal.NullDecimal
	StarterCode       json.RawMessage
	ReferenceLanguage *string
	ReferenceSource   *string
	Bump              bool
	ClearVerified     bool
	CourseID          uuid.UUID
	QuestionID        uuid.UUID
}

// `bump`: giới hạn / checker / ngôn ngữ / lời giải mẫu đổi → tests_version + 1 và gỡ cờ đã kiểm; chỉ `starter_code` đổi thì giữ nguyên (góp ý #2 (a)).
func (q *Queries) CodeProblemUpdate(ctx context.Context, arg CodeProblemUpdateParams) (CodeProblem, error) {
	row := q.db.QueryRow(ctx, codeProblemUpdate,
		arg.Languages,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
		arg.OutputLimitKb,
		arg.Checker,
		arg.FloatEps,
		arg.StarterCode,
		arg.ReferenceLanguage,
		arg.ReferenceSource,
		arg.Bump,
		arg.ClearVerified,
		arg.CourseID,
		arg.QuestionID,
	)
	var i CodeProblem
	err := row.Scan(
		&i.QuestionID,
		&i.CourseID,
		&i.Languages,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.OutputLimitKb,
		&i.Checker,
		&i.FloatEps,
		&i.StarterCode,
		&i.ReferenceLanguage,
		&i.ReferenceSource,
		&i.ReferenceVerifiedVersion,
		&i.ReferenceVerifiedAt,
		&i.TestsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const questionArchive = `-- name: QuestionArchive :one
update question_bank set archived_at = coalesce(archived_at, now()), version = version + 1, updated_at = now()
where course_id = $1 and id = $2
returning id, course_id, type, title, topic, difficulty, stem, answer_key, explanation, citations, origin, review_status, created_by, reviewed_by, reviewed_at, ai_job_id, archived_at, version, created_at, updated_at
`

type QuestionArchiveParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) QuestionArchive(ctx context.Context, arg QuestionArchiveParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, questionArchive, arg.CourseID, arg.ID)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.Topic,
		&i.Difficulty,
		&i.Stem,
		&i.AnswerKey,
		&i.Explanation,
		&i.Citations,
		&i.Origin,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AiJobID,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const questionBump = `-- name: QuestionBump :one
update question_bank
set version = version + 1, updated_at = now(),
    review_status = case when review_status in ('APPROVED', 'REJECTED') then 'DRAFT'::question_review_status else review_status end,
    reviewed_by = case when review_status in ('APPROVED', 'REJECTED') then null else reviewed_by end,
    reviewed_at = case when review_status in ('APPROVED', 'REJECTED') then null else reviewed_at end
where course_id = $1 and id = $2
returning id, course_id, type, title, topic, difficulty, stem, answer_key, explanation, citations, origin, review_status, created_by, reviewed_by, reviewed_at, ai_job_id, archived_at, version, created_at, updated_at
`

type QuestionBumpParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

// Đổi cấu hình bài code / test: tăng version, về DRAFT.
func (q *Queries) QuestionBump(ctx context.Context, arg QuestionBumpParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, questionBump, arg.CourseID, arg.ID)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.Topic,
		&i.Difficulty,
		&i.Stem,
		&i.AnswerKey,
		&i.Explanation,
		&i.Citations,
		&i.Origin,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AiJobID,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const questionCourseStatus = `-- name: QuestionCourseStatus :one

select status from courses where id = $1
`

// Ngân hàng câu hỏi (US-PE-03, SRS 5.2–5.5). Mọi truy vấn đều bắt đầu bằng course_id (luật 13).
func (q *Queries) QuestionCourseStatus(ctx context.Context, courseID uuid.UUID) (CourseStatus, error) {
	row := q.db.QueryRow(ctx, questionCourseStatus, courseID)
	var status CourseStatus
	err := row.Scan(&status)
	return status, err
}

const questionGet = `-- name: QuestionGet :one
select id, course_id, type, title, topic, difficulty, stem, answer_key, explanation, citations, origin, review_status, created_by, reviewed_by, reviewed_at, ai_job_id, archived_at, version, created_at, updated_at from question_bank where course_id = $1 and id = $2
`

type QuestionGetParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) QuestionGet(ctx context.Context, arg QuestionGetParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, questionGet, arg.CourseID, arg.ID)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.Topic,
		&i.Difficulty,
		&i.Stem,
		&i.AnswerKey,
		&i.Explanation,
		&i.Citations,
		&i.Origin,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AiJobID,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const questionInsert = `-- name: QuestionInsert :one
insert into question_bank (course_id, type, title, topic, difficulty, stem, answer_key, explanation, origin, review_status, created_by, ai_job_id)
values ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12)
returning id, course_id, type, title, topic, difficulty, stem, answer_key, explanation, citations, origin, review_status, created_by, reviewed_by, reviewed_at, ai_job_id, archived_at, version, created_at, updated_at
`

type QuestionInsertParams struct {
	CourseID     uuid.UUID
	Type         QuestionType
	Title        string
	Topic        string
	Difficulty   QuestionDifficulty
	Stem         string
	AnswerKey    json.RawMessage
	Explanation  *string
	Origin       QuestionOrigin
	ReviewStatus QuestionReviewStatus
	CreatedBy    uuid.UUID
	AiJobID      *uuid.UUID
}

func (q *Queries) QuestionInsert(ctx context.Context, arg QuestionInsertParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, questionInsert,
		arg.CourseID,
		arg.Type,
		arg.Title,
		arg.Topic,
		arg.Difficulty,
		arg.Stem,
		arg.AnswerKey,
		arg.Explanation,
		arg.Origin,
		arg.ReviewStatus,
		arg.CreatedBy,
		arg.AiJobID,
	)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.Topic,
		&i.Difficulty,
		&i.Stem,
		&i.AnswerKey,
		&i.Explanation,
		&i.Citations,
		&i.Origin,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AiJobID,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const questionList = `-- name: QuestionList :many
select q.id, q.type, q.title, q.topic, q.difficulty, q.review_status, q.origin, q.version, q.updated_at, q.created_at, q.archived_at,
       (select count(distinct i.exam_id) from exam_items i where i.course_id = q.course_id and i.question_id = q.id)::int as used_in_exams
from question_bank q
where q.course_id = $1
  and ($2::boolean or q.archived_at is null)
  and ($3::question_review_status is null or q.review_status = $3)
  and ($4::text is null or q.topic = $4)
  and ($5::question_difficulty is null or q.difficulty = $5)
  and ($6::question_type is null or q.type = $6)
  and ($7::question_origin is null or q.origin = $7)
  and ($8::text is null or q.title ilike '%' || $8 || '%')
  and ($9::timestamptz is null or (q.created_at, q.id) < ($9::timestamptz, $10::uuid))
order by q.created_at desc, q.id desc
limit $11
`

type QuestionListParams struct {
	CourseID     uuid.UUID
	Archived     bool
	ReviewStatus *QuestionReviewStatus
	Topic        *string
	Difficulty   *QuestionDifficulty
	Type         *QuestionType
	Origin       *QuestionOrigin
	Q            *string
	CursorAt     *time.Time
	CursorID     *uuid.UUID
	MaxRows      int32
}

type QuestionListRow struct {
	ID           uuid.UUID
	Type         QuestionType
	Title        string
	Topic        string
	Difficulty   QuestionDifficulty
	ReviewStatus QuestionReviewStatus
	Origin       QuestionOrigin
	Version      int32
	UpdatedAt    time.Time
	CreatedAt    time.Time
	ArchivedAt   *time.Time
	UsedInExams  int32
}

// Danh sách có lọc, phân trang con trỏ (created_at desc, id desc). `used_in_exams` đếm bằng truy vấn con (không N+1).
func (q *Queries) QuestionList(ctx context.Context, arg QuestionListParams) ([]QuestionListRow, error) {
	rows, err := q.db.Query(ctx, questionList,
		arg.CourseID,
		arg.Archived,
		arg.ReviewStatus,
		arg.Topic,
		arg.Difficulty,
		arg.Type,
		arg.Origin,
		arg.Q,
		arg.CursorAt,
		arg.CursorID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionListRow{}
	for rows.Next() {
		var i QuestionListRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Topic,
			&i.Difficulty,
			&i.ReviewStatus,
			&i.Origin,
			&i.Version,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.UsedInExams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const questionLock = `-- name: QuestionLock :one
select id, course_id, type, title, topic, difficulty, stem, answer_key, explanation, citations, origin, review_status, created_by, reviewed_by, reviewed_at, ai_job_id, archived_at, version, created_at, updated_at from question_bank where course_id = $1 and id = $2 for update
`

type QuestionLockParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) QuestionLock(ctx context.Context, arg QuestionLockParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, questionLock, arg.CourseID, arg.ID)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.Topic,
		&i.Difficulty,
		&i.Stem,
		&i.AnswerKey,
		&i.Explanation,
		&i.Citations,
		&i.Origin,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AiJobID,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const questionOptionInsert = `-- name: QuestionOptionInsert :one
insert into question_options (id, course_id, question_id, position, body, pinned_last)
values ($1, $2, $3, $4, $5, $6)
returning id
`

type QuestionOptionInsertParams struct {
	ID         uuid.UUID
	CourseID   uuid.UUID
	QuestionID uuid.UUID
	Position   int16
	Body       string
	PinnedLast bool
}

func (q *Queries) QuestionOptionInsert(ctx context.Context, arg QuestionOptionInsertParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, questionOptionInsert,
		arg.ID,
		arg.CourseID,
		arg.QuestionID,
		arg.Position,
		arg.Body,
		arg.PinnedLast,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const questionOptions = `-- name: QuestionOptions :many
select id, position, body, pinned_last from question_options
where course_id = $1 and question_id = $2 order by position
`

type QuestionOptionsParams struct {
	CourseID   uuid.UUID
	QuestionID uuid.UUID
}

type QuestionOptionsRow struct {
	ID         uuid.UUID
	Position   int16
	Body       string
	PinnedLast bool
}

func (q *Queries) QuestionOptions(ctx context.Context, arg QuestionOptionsParams) ([]QuestionOptionsRow, error) {
	rows, err := q.db.Query(ctx, questionOptions, arg.CourseID, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionOptionsRow{}
	for rows.Next() {
		var i QuestionOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Body,
			&i.PinnedLast,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const questionOptionsDelete = `-- name: QuestionOptionsDelete :exec
delete from question_options where course_id = $1 and question_id = $2
`

type QuestionOptionsDeleteParams struct {
	CourseID   uuid.UUID
	QuestionID uuid.UUID
}

func (q *Queries) QuestionOptionsDelete(ctx context.Context, arg QuestionOptionsDeleteParams) error {
	_, err := q.db.Exec(ctx, questionOptionsDelete, arg.CourseID, arg.QuestionID)
	return err
}

const questionReview = `-- name: QuestionReview :one
update question_bank
set review_status = $1, reviewed_by = $2, reviewed_at = $3, version = version + 1, updated_at = now()
where course_id = $4 and id = $5 and version = $6
returning id, course_id, type, title, topic, difficulty, stem, answer_key, explanation, citations, origin, review_status, created_by, reviewed_by, reviewed_at, ai_job_id, archived_at, version, created_at, updated_at
`

type QuestionReviewParams struct {
	ReviewStatus    QuestionReviewStatus
	ReviewedBy      *uuid.UUID
	ReviewedAt      *time.Time
	CourseID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) QuestionReview(ctx context.Context, arg QuestionReviewParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, questionReview,
		arg.ReviewStatus,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.CourseID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.Topic,
		&i.Difficulty,
		&i.Stem,
		&i.AnswerKey,
		&i.Explanation,
		&i.Citations,
		&i.Origin,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AiJobID,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const questionUpdateContent = `-- name: QuestionUpdateContent :one
update question_bank
set title = $1, topic = $2, difficulty = $3, stem = $4,
    answer_key = $5, explanation = $6, version = version + 1, updated_at = now(),
    review_status = case when $7::boolean and review_status in ('APPROVED', 'REJECTED') then 'DRAFT'::question_review_status else review_status end,
    reviewed_by = case when $7::boolean and review_status in ('APPROVED', 'REJECTED') then null else reviewed_by end,
    reviewed_at = case when $7::boolean and review_status in ('APPROVED', 'REJECTED') then null else reviewed_at end
where course_id = $8 and id = $9 and version = $10
returning id, course_id, type, title, topic, difficulty, stem, answer_key, explanation, citations, origin, review_status, created_by, reviewed_by, reviewed_at, ai_job_id, archived_at, version, created_at, updated_at
`

type QuestionUpdateContentParams struct {
	Title           string
	Topic           string
	Difficulty      QuestionDifficulty
	Stem            string
	AnswerKey       json.RawMessage
	Explanation     *string
	ResetReview     bool
	CourseID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int32
}

// Sửa nội dung: tăng version, về DRAFT (gỡ người duyệt) nếu `reset_review`; `expected_version` là khoá lạc quan (0 dòng = sai version).
func (q *Queries) QuestionUpdateContent(ctx context.Context, arg QuestionUpdateContentParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, questionUpdateContent,
		arg.Title,
		arg.Topic,
		arg.Difficulty,
		arg.Stem,
		arg.AnswerKey,
		arg.Explanation,
		arg.ResetReview,
		arg.CourseID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.Title,
		&i.Topic,
		&i.Difficulty,
		&i.Stem,
		&i.AnswerKey,
		&i.Explanation,
		&i.Citations,
		&i.Origin,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AiJobID,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const questionUsage = `-- name: QuestionUsage :many
select distinct e.id, e.title, e.status from exam_items i
join exams e on e.course_id = i.course_id and e.id = i.exam_id
where i.course_id = $1 and i.question_id = $2
order by e.title, e.id
`

type QuestionUsageParams struct {
	CourseID   uuid.UUID
	QuestionID uuid.UUID
}

type QuestionUsageRow struct {
	ID     uuid.UUID
	Title  string
	Status ExamStatus
}

// Bài thi đang dùng câu này, kèm trạng thái (để khoá sửa / tính "đang dùng").
func (q *Queries) QuestionUsage(ctx context.Context, arg QuestionUsageParams) ([]QuestionUsageRow, error) {
	rows, err := q.db.Query(ctx, questionUsage, arg.CourseID, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionUsageRow{}
	for rows.Next() {
		var i QuestionUsageRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const testcaseDelete = `-- name: TestcaseDelete :one
delete from code_testcases where course_id = $1 and problem_id = $2 and id = $3
returning input_blob_key, expected_blob_key
`

type TestcaseDeleteParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
	ID        uuid.UUID
}

type TestcaseDeleteRow struct {
	InputBlobKey    *string
	ExpectedBlobKey *string
}

func (q *Queries) TestcaseDelete(ctx context.Context, arg TestcaseDeleteParams) (TestcaseDeleteRow, error) {
	row := q.db.QueryRow(ctx, testcaseDelete, arg.CourseID, arg.ProblemID, arg.ID)
	var i TestcaseDeleteRow
	err := row.Scan(&i.InputBlobKey, &i.ExpectedBlobKey)
	return i, err
}

const testcaseGet = `-- name: TestcaseGet :one
select id, course_id, problem_id, position, name, is_sample, weight, input, input_blob_key, expected, expected_blob_key, input_bytes, expected_bytes, source, approved, created_at, updated_at from code_testcases where course_id = $1 and problem_id = $2 and id = $3
`

type TestcaseGetParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) TestcaseGet(ctx context.Context, arg TestcaseGetParams) (CodeTestcase, error) {
	row := q.db.QueryRow(ctx, testcaseGet, arg.CourseID, arg.ProblemID, arg.ID)
	var i CodeTestcase
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ProblemID,
		&i.Position,
		&i.Name,
		&i.IsSample,
		&i.Weight,
		&i.Input,
		&i.InputBlobKey,
		&i.Expected,
		&i.ExpectedBlobKey,
		&i.InputBytes,
		&i.ExpectedBytes,
		&i.Source,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const testcaseIDsByPosition = `-- name: TestcaseIDsByPosition :many
select id from code_testcases where course_id = $1 and problem_id = $2 order by position, id
`

type TestcaseIDsByPositionParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) TestcaseIDsByPosition(ctx context.Context, arg TestcaseIDsByPositionParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, testcaseIDsByPosition, arg.CourseID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const testcaseInsert = `-- name: TestcaseInsert :one
insert into code_testcases (course_id, problem_id, position, name, is_sample, weight, input, input_blob_key, expected, expected_blob_key, input_bytes, expected_bytes, source, approved)
values ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14)
returning id, course_id, problem_id, position, name, is_sample, weight, input, input_blob_key, expected, expected_blob_key, input_bytes, expected_bytes, source, approved, created_at, updated_at
`

type TestcaseInsertParams struct {
	CourseID        uuid.UUID
	ProblemID       uuid.UUID
	Position        int32
	Name            string
	IsSample        bool
	Weight          int16
	Input           *string
	InputBlobKey    *string
	Expected        *string
	ExpectedBlobKey *string
	InputBytes      int32
	ExpectedBytes   int32
	Source          string
	Approved        bool
}

func (q *Queries) TestcaseInsert(ctx context.Context, arg TestcaseInsertParams) (CodeTestcase, error) {
	row := q.db.QueryRow(ctx, testcaseInsert,
		arg.CourseID,
		arg.ProblemID,
		arg.Position,
		arg.Name,
		arg.IsSample,
		arg.Weight,
		arg.Input,
		arg.InputBlobKey,
		arg.Expected,
		arg.ExpectedBlobKey,
		arg.InputBytes,
		arg.ExpectedBytes,
		arg.Source,
		arg.Approved,
	)
	var i CodeTestcase
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ProblemID,
		&i.Position,
		&i.Name,
		&i.IsSample,
		&i.Weight,
		&i.Input,
		&i.InputBlobKey,
		&i.Expected,
		&i.ExpectedBlobKey,
		&i.InputBytes,
		&i.ExpectedBytes,
		&i.Source,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const testcaseList = `-- name: TestcaseList :many
select id, position, name, is_sample, weight, input, input_blob_key, expected, expected_blob_key, input_bytes, expected_bytes, source, approved, created_at, updated_at
from code_testcases
where course_id = $1 and problem_id = $2
  and ($3::int is null or position > $3)
order by position
limit $4
`

type TestcaseListParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
	CursorPos *int32
	MaxRows   int32
}

type TestcaseListRow struct {
	ID              uuid.UUID
	Position        int32
	Name            string
	IsSample        bool
	Weight          int16
	Input           *string
	InputBlobKey    *string
	Expected        *string
	ExpectedBlobKey *string
	InputBytes      int32
	ExpectedBytes   int32
	Source          string
	Approved        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) TestcaseList(ctx context.Context, arg TestcaseListParams) ([]TestcaseListRow, error) {
	rows, err := q.db.Query(ctx, testcaseList,
		arg.CourseID,
		arg.ProblemID,
		arg.CursorPos,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestcaseListRow{}
	for rows.Next() {
		var i TestcaseListRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.IsSample,
			&i.Weight,
			&i.Input,
			&i.InputBlobKey,
			&i.Expected,
			&i.ExpectedBlobKey,
			&i.InputBytes,
			&i.ExpectedBytes,
			&i.Source,
			&i.Approved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const testcaseNames = `-- name: TestcaseNames :many
select name from code_testcases where course_id = $1 and problem_id = $2
`

type TestcaseNamesParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) TestcaseNames(ctx context.Context, arg TestcaseNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, testcaseNames, arg.CourseID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const testcaseSetPosition = `-- name: TestcaseSetPosition :exec
update code_testcases set position = $1, updated_at = now()
where course_id = $2 and problem_id = $3 and id = $4
`

type TestcaseSetPositionParams struct {
	Position  int32
	CourseID  uuid.UUID
	ProblemID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) TestcaseSetPosition(ctx context.Context, arg TestcaseSetPositionParams) error {
	_, err := q.db.Exec(ctx, testcaseSetPosition,
		arg.Position,
		arg.CourseID,
		arg.ProblemID,
		arg.ID,
	)
	return err
}

const testcaseStats = `-- name: TestcaseStats :one
select count(*) filter (where approved)::int as total,
       count(*)::int as total_all,
       count(*) filter (where approved and is_sample)::int as samples,
       count(*) filter (where approved and not is_sample)::int as hidden,
       coalesce(sum(weight) filter (where approved), 0)::int as total_weight,
       coalesce(max(position), 0)::int as max_position
from code_testcases where course_id = $1 and problem_id = $2
`

type TestcaseStatsParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
}

type TestcaseStatsRow struct {
	Total       int32
	TotalAll    int32
	Samples     int32
	Hidden      int32
	TotalWeight int32
	MaxPosition int32
}

func (q *Queries) TestcaseStats(ctx context.Context, arg TestcaseStatsParams) (TestcaseStatsRow, error) {
	row := q.db.QueryRow(ctx, testcaseStats, arg.CourseID, arg.ProblemID)
	var i TestcaseStatsRow
	err := row.Scan(
		&i.Total,
		&i.TotalAll,
		&i.Samples,
		&i.Hidden,
		&i.TotalWeight,
		&i.MaxPosition,
	)
	return i, err
}

const testcaseUpdate = `-- name: TestcaseUpdate :one
update code_testcases
set name = $1, is_sample = $2, weight = $3, position = $4,
    input = $5, input_blob_key = $6, expected = $7, expected_blob_key = $8,
    input_bytes = $9, expected_bytes = $10, updated_at = now()
where course_id = $11 and problem_id = $12 and id = $13
returning id, course_id, problem_id, position, name, is_sample, weight, input, input_blob_key, expected, expected_blob_key, input_bytes, expected_bytes, source, approved, created_at, updated_at
`

type TestcaseUpdateParams struct {
	Name            string
	IsSample        bool
	Weight          int16
	Position        int32
	Input           *string
	InputBlobKey    *string
	Expected        *string
	ExpectedBlobKey *string
	InputBytes      int32
	ExpectedBytes   int32
	CourseID        uuid.UUID
	ProblemID       uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) TestcaseUpdate(ctx context.Context, arg TestcaseUpdateParams) (CodeTestcase, error) {
	row := q.db.QueryRow(ctx, testcaseUpdate,
		arg.Name,
		arg.IsSample,
		arg.Weight,
		arg.Position,
		arg.Input,
		arg.InputBlobKey,
		arg.Expected,
		arg.ExpectedBlobKey,
		arg.InputBytes,
		arg.ExpectedBytes,
		arg.CourseID,
		arg.ProblemID,
		arg.ID,
	)
	var i CodeTestcase
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ProblemID,
		&i.Position,
		&i.Name,
		&i.IsSample,
		&i.Weight,
		&i.Input,
		&i.InputBlobKey,
		&i.Expected,
		&i.ExpectedBlobKey,
		&i.InputBytes,
		&i.ExpectedBytes,
		&i.Source,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const testcasesApprove = `-- name: TestcasesApprove :execrows
update code_testcases set approved = true, updated_at = now()
where course_id = $1 and problem_id = $2 and id = any($3::text[]::uuid[]) and not approved
`

type TestcasesApproveParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
	Ids       []string
}

func (q *Queries) TestcasesApprove(ctx context.Context, arg TestcasesApproveParams) (int64, error) {
	result, err := q.db.Exec(ctx, testcasesApprove, arg.CourseID, arg.ProblemID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const testcasesDeleteAll = `-- name: TestcasesDeleteAll :many
delete from code_testcases where course_id = $1 and problem_id = $2 returning input_blob_key, expected_blob_key
`

type TestcasesDeleteAllParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
}

type TestcasesDeleteAllRow struct {
	InputBlobKey    *string
	ExpectedBlobKey *string
}

func (q *Queries) TestcasesDeleteAll(ctx context.Context, arg TestcasesDeleteAllParams) ([]TestcasesDeleteAllRow, error) {
	rows, err := q.db.Query(ctx, testcasesDeleteAll, arg.CourseID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestcasesDeleteAllRow{}
	for rows.Next() {
		var i TestcasesDeleteAllRow
		if err := rows.Scan(&i.InputBlobKey, &i.ExpectedBlobKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
