// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_exam.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const examAttemptCounts = `-- name: ExamAttemptCounts :one
select count(*)::int as started, (count(*) filter (where status = 'GRADED'))::int as graded
from exam_attempts where course_id = $1 and exam_id = $2
`

type ExamAttemptCountsParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type ExamAttemptCountsRow struct {
	Started int32
	Graded  int32
}

func (q *Queries) ExamAttemptCounts(ctx context.Context, arg ExamAttemptCountsParams) (ExamAttemptCountsRow, error) {
	row := q.db.QueryRow(ctx, examAttemptCounts, arg.CourseID, arg.ExamID)
	var i ExamAttemptCountsRow
	err := row.Scan(&i.Started, &i.Graded)
	return i, err
}

const examAttemptsExtend = `-- name: ExamAttemptsExtend :execrows
update exam_attempts a
set deadline_at = least(a.started_at + make_interval(mins => e.duration_minutes::int), $1::timestamptz)
from exams e
where e.course_id = a.course_id and e.id = a.exam_id
  and a.course_id = $2 and a.exam_id = $3
  and a.status = 'IN_PROGRESS' and a.deadline_at >= $4::timestamptz
`

type ExamAttemptsExtendParams struct {
	NewClosesAt time.Time
	CourseID    uuid.UUID
	ExamID      uuid.UUID
	OldClosesAt time.Time
}

// Gia hạn: lượt đang làm bị chặn bởi mốc đóng cũ (deadline ≥ mốc cũ) được tính lại min(started_at + thời lượng, mốc mới).
func (q *Queries) ExamAttemptsExtend(ctx context.Context, arg ExamAttemptsExtendParams) (int64, error) {
	result, err := q.db.Exec(ctx, examAttemptsExtend,
		arg.NewClosesAt,
		arg.CourseID,
		arg.ExamID,
		arg.OldClosesAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const examClone = `-- name: ExamClone :one
insert into exams (course_id, title, instructions, kind, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, created_by)
select x.course_id, left(x.title, 110) || ' (bản sao)', x.instructions, x.kind, x.shuffle_questions, x.shuffle_options, x.max_score, x.rounding_step, x.multi_scoring,
       x.reveal_answers, x.appeal_days, $1
from exams x where x.course_id = $2 and x.id = $3
returning id, course_id, title, instructions, kind, status, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, publish_hold, regrading, published_at, created_by, version, created_at, updated_at
`

type ExamCloneParams struct {
	CreatedBy uuid.UUID
	CourseID  uuid.UUID
	ID        uuid.UUID
}

// Bản sao DRAFT: cùng cài đặt, không giờ; tiêu đề thêm " (bản sao)" (cắt tiêu đề để vẫn ≤ 120 ký tự).
func (q *Queries) ExamClone(ctx context.Context, arg ExamCloneParams) (Exam, error) {
	row := q.db.QueryRow(ctx, examClone, arg.CreatedBy, arg.CourseID, arg.ID)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Instructions,
		&i.Kind,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DurationMinutes,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.MaxScore,
		&i.RoundingStep,
		&i.MultiScoring,
		&i.RevealAnswers,
		&i.AppealDays,
		&i.PublishHold,
		&i.Regrading,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const examCodeQuestions = `-- name: ExamCodeQuestions :many
select q.id, q.title, cp.time_limit_ms,
       (select count(*) from code_testcases t where t.course_id = cp.course_id and t.problem_id = cp.question_id and t.approved)::int as approved_tests
from exam_items i
join question_bank q on q.course_id = i.course_id and q.id = i.question_id
join code_problems cp on cp.course_id = q.course_id and cp.question_id = q.id
where i.course_id = $1 and i.exam_id = $2 and q.type = 'CODE'
order by i.position
`

type ExamCodeQuestionsParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type ExamCodeQuestionsRow struct {
	ID            uuid.UUID
	Title         string
	TimeLimitMs   int32
	ApprovedTests int32
}

// Câu CODE của bài kèm tổng "đồng hồ" các test đã duyệt: mỗi test tốn tối đa 3 × time_limit_ms (clockLimit của máy chấm).
func (q *Queries) ExamCodeQuestions(ctx context.Context, arg ExamCodeQuestionsParams) ([]ExamCodeQuestionsRow, error) {
	rows, err := q.db.Query(ctx, examCodeQuestions, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamCodeQuestionsRow{}
	for rows.Next() {
		var i ExamCodeQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TimeLimitMs,
			&i.ApprovedTests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examDeleteDraft = `-- name: ExamDeleteDraft :execrows
delete from exams where course_id = $1 and id = $2 and status = 'DRAFT'
`

type ExamDeleteDraftParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) ExamDeleteDraft(ctx context.Context, arg ExamDeleteDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, examDeleteDraft, arg.CourseID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const examExtend = `-- name: ExamExtend :one
update exams set closes_at = $1, version = version + 1
where course_id = $2 and id = $3
returning id, course_id, title, instructions, kind, status, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, publish_hold, regrading, published_at, created_by, version, created_at, updated_at
`

type ExamExtendParams struct {
	ClosesAt *time.Time
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) ExamExtend(ctx context.Context, arg ExamExtendParams) (Exam, error) {
	row := q.db.QueryRow(ctx, examExtend, arg.ClosesAt, arg.CourseID, arg.ID)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Instructions,
		&i.Kind,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DurationMinutes,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.MaxScore,
		&i.RoundingStep,
		&i.MultiScoring,
		&i.RevealAnswers,
		&i.AppealDays,
		&i.PublishHold,
		&i.Regrading,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const examGet = `-- name: ExamGet :one
select id, course_id, title, instructions, kind, status, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, publish_hold, regrading, published_at, created_by, version, created_at, updated_at from exams where course_id = $1 and id = $2
`

type ExamGetParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) ExamGet(ctx context.Context, arg ExamGetParams) (Exam, error) {
	row := q.db.QueryRow(ctx, examGet, arg.CourseID, arg.ID)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Instructions,
		&i.Kind,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DurationMinutes,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.MaxScore,
		&i.RoundingStep,
		&i.MultiScoring,
		&i.RevealAnswers,
		&i.AppealDays,
		&i.PublishHold,
		&i.Regrading,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const examInsert = `-- name: ExamInsert :one

insert into exams (course_id, title, instructions, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step,
                   multi_scoring, reveal_answers, appeal_days, created_by)
values ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12, $13, $14)
returning id, course_id, title, instructions, kind, status, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, publish_hold, regrading, published_at, created_by, version, created_at, updated_at
`

type ExamInsertParams struct {
	CourseID         uuid.UUID
	Title            string
	Instructions     *string
	OpensAt          *time.Time
	ClosesAt         *time.Time
	DurationMinutes  *int16
	ShuffleQuestions bool
	ShuffleOptions   bool
	MaxScore         decimal.Decimal
	RoundingStep     decimal.Decimal
	MultiScoring     MultiScoring
	RevealAnswers    bool
	AppealDays       int16
	CreatedBy        uuid.UUID
}

// Bài thi (US-PE-04, SRS FEAT-weekly-exam 5.6–5.7, 4.2). Mọi truy vấn bắt đầu bằng course_id (luật 13).
// `effective_status` tính ở đây bằng `now` truyền vào (đồng hồ của ứng dụng, giả được trong test): SCHEDULED + now ≥ opens_at → OPEN; còn lại theo closes_at.
func (q *Queries) ExamInsert(ctx context.Context, arg ExamInsertParams) (Exam, error) {
	row := q.db.QueryRow(ctx, examInsert,
		arg.CourseID,
		arg.Title,
		arg.Instructions,
		arg.OpensAt,
		arg.ClosesAt,
		arg.DurationMinutes,
		arg.ShuffleQuestions,
		arg.ShuffleOptions,
		arg.MaxScore,
		arg.RoundingStep,
		arg.MultiScoring,
		arg.RevealAnswers,
		arg.AppealDays,
		arg.CreatedBy,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Instructions,
		&i.Kind,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DurationMinutes,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.MaxScore,
		&i.RoundingStep,
		&i.MultiScoring,
		&i.RevealAnswers,
		&i.AppealDays,
		&i.PublishHold,
		&i.Regrading,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const examItemInsert = `-- name: ExamItemInsert :exec
insert into exam_items (course_id, exam_id, question_id, position, points)
values ($1, $2, $3, $4, $5)
`

type ExamItemInsertParams struct {
	CourseID   uuid.UUID
	ExamID     uuid.UUID
	QuestionID uuid.UUID
	Position   int16
	Points     decimal.Decimal
}

func (q *Queries) ExamItemInsert(ctx context.Context, arg ExamItemInsertParams) error {
	_, err := q.db.Exec(ctx, examItemInsert,
		arg.CourseID,
		arg.ExamID,
		arg.QuestionID,
		arg.Position,
		arg.Points,
	)
	return err
}

const examItemList = `-- name: ExamItemList :many
select i.id, i.question_id, i.position, i.points, q.type, q.title, q.topic, q.difficulty, q.review_status, q.archived_at
from exam_items i
join question_bank q on q.course_id = i.course_id and q.id = i.question_id
where i.course_id = $1 and i.exam_id = $2
order by i.position
`

type ExamItemListParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type ExamItemListRow struct {
	ID           uuid.UUID
	QuestionID   uuid.UUID
	Position     int16
	Points       decimal.Decimal
	Type         QuestionType
	Title        string
	Topic        string
	Difficulty   QuestionDifficulty
	ReviewStatus QuestionReviewStatus
	ArchivedAt   *time.Time
}

func (q *Queries) ExamItemList(ctx context.Context, arg ExamItemListParams) ([]ExamItemListRow, error) {
	rows, err := q.db.Query(ctx, examItemList, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamItemListRow{}
	for rows.Next() {
		var i ExamItemListRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Position,
			&i.Points,
			&i.Type,
			&i.Title,
			&i.Topic,
			&i.Difficulty,
			&i.ReviewStatus,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examItemListShared = `-- name: ExamItemListShared :many
select i.id, i.question_id, i.position, i.points, q.type, q.title, q.topic, q.difficulty, q.review_status, q.archived_at
from exam_items i
join question_bank q on q.course_id = i.course_id and q.id = i.question_id
where i.course_id = $1 and i.exam_id = $2
order by i.position
for share of q
`

type ExamItemListSharedParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type ExamItemListSharedRow struct {
	ID           uuid.UUID
	QuestionID   uuid.UUID
	Position     int16
	Points       decimal.Decimal
	Type         QuestionType
	Title        string
	Topic        string
	Difficulty   QuestionDifficulty
	ReviewStatus QuestionReviewStatus
	ArchivedAt   *time.Time
}

// Như ExamItemList nhưng khoá chia sẻ các câu hỏi: một `REJECT` / lưu trữ đang chạy song song phải xong trước (hoặc chờ tới khi `schedule` commit) — SRS 4.2.4, AC10.
func (q *Queries) ExamItemListShared(ctx context.Context, arg ExamItemListSharedParams) ([]ExamItemListSharedRow, error) {
	rows, err := q.db.Query(ctx, examItemListShared, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamItemListSharedRow{}
	for rows.Next() {
		var i ExamItemListSharedRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Position,
			&i.Points,
			&i.Type,
			&i.Title,
			&i.Topic,
			&i.Difficulty,
			&i.ReviewStatus,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examItemsClone = `-- name: ExamItemsClone :exec
insert into exam_items (course_id, exam_id, question_id, position, points)
select i.course_id, $1, i.question_id, i.position, i.points
from exam_items i where i.course_id = $2 and i.exam_id = $3
`

type ExamItemsCloneParams struct {
	NewExamID uuid.UUID
	CourseID  uuid.UUID
	ExamID    uuid.UUID
}

func (q *Queries) ExamItemsClone(ctx context.Context, arg ExamItemsCloneParams) error {
	_, err := q.db.Exec(ctx, examItemsClone, arg.NewExamID, arg.CourseID, arg.ExamID)
	return err
}

const examItemsDelete = `-- name: ExamItemsDelete :exec
delete from exam_items where course_id = $1 and exam_id = $2
`

type ExamItemsDeleteParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

func (q *Queries) ExamItemsDelete(ctx context.Context, arg ExamItemsDeleteParams) error {
	_, err := q.db.Exec(ctx, examItemsDelete, arg.CourseID, arg.ExamID)
	return err
}

const examList = `-- name: ExamList :many
with e as (
  select x.id, x.course_id, x.title, x.instructions, x.kind, x.status, x.opens_at, x.closes_at, x.duration_minutes, x.shuffle_questions, x.shuffle_options, x.max_score, x.rounding_step, x.multi_scoring, x.reveal_answers, x.appeal_days, x.publish_hold, x.regrading, x.published_at, x.created_by, x.version, x.created_at, x.updated_at,
         (case when x.status in ('SCHEDULED', 'OPEN') and x.closes_at <= $4::timestamptz then 'CLOSED'
               when x.status = 'SCHEDULED' and x.opens_at <= $4::timestamptz then 'OPEN'
               else x.status::text end)::exam_status as eff
  from exams x
  where x.course_id = $5
    and (not $6::boolean or x.status <> 'DRAFT')
    and ($7::uuid is null or x.id = $7::uuid)
    and ($8::timestamptz is null or (x.created_at, x.id) < ($8::timestamptz, $9::uuid))
)
select e.id, e.course_id, e.title, e.instructions, e.kind, e.status, e.eff as effective_status, e.opens_at, e.closes_at, e.duration_minutes, e.max_score,
       e.published_at, e.version, e.created_at,
       (select count(*) from exam_items i where i.course_id = e.course_id and i.exam_id = e.id)::int as items_count,
       (select count(*) from exam_attempts a where a.course_id = e.course_id and a.exam_id = e.id)::int as attempts_started,
       (select count(*) from exam_attempts a where a.course_id = e.course_id and a.exam_id = e.id and a.status = 'GRADED')::int as attempts_graded,
       ma.id as my_attempt_id, ma.status as my_attempt_status, ma.deadline_at as my_deadline_at, ma.submitted_at as my_submitted_at,
       ma.adjusted_score as my_adjusted_score, ma.auto_score as my_auto_score -- service chỉ lộ điểm khi PUBLISHED
from e
left join exam_attempts ma on ma.course_id = e.course_id and ma.exam_id = e.id and ma.student_id = $1
where ($2::exam_status is null or e.eff = $2)
order by e.created_at desc, e.id desc
limit $3
`

type ExamListParams struct {
	StudentID   *uuid.UUID
	Status      *ExamStatus
	MaxRows     int32
	Now         time.Time
	CourseID    uuid.UUID
	StudentOnly bool
	ExamID      *uuid.UUID
	CursorAt    *time.Time
	CursorID    *uuid.UUID
}

type ExamListRow struct {
	ID              uuid.UUID
	CourseID        uuid.UUID
	Title           string
	Instructions    *string
	Kind            ExamKind
	Status          ExamStatus
	EffectiveStatus ExamStatus
	OpensAt         *time.Time
	ClosesAt        *time.Time
	DurationMinutes *int16
	MaxScore        decimal.Decimal
	PublishedAt     *time.Time
	Version         int32
	CreatedAt       time.Time
	ItemsCount      int32
	AttemptsStarted int32
	AttemptsGraded  int32
	MyAttemptID     *uuid.UUID
	MyAttemptStatus *AttemptStatus
	MyDeadlineAt    *time.Time
	MySubmittedAt   *time.Time
	MyAdjustedScore decimal.NullDecimal
	MyAutoScore     decimal.NullDecimal
}

// Danh sách theo vai: `student_only` ẩn DRAFT; `student_id` nối lượt làm của chính người đó. `status` lọc theo effective_status.
// Đếm mục / lượt bằng truy vấn con (không N+1). Phân trang con trỏ (created_at desc, id desc).
func (q *Queries) ExamList(ctx context.Context, arg ExamListParams) ([]ExamListRow, error) {
	rows, err := q.db.Query(ctx, examList,
		arg.StudentID,
		arg.Status,
		arg.MaxRows,
		arg.Now,
		arg.CourseID,
		arg.StudentOnly,
		arg.ExamID,
		arg.CursorAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamListRow{}
	for rows.Next() {
		var i ExamListRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Instructions,
			&i.Kind,
			&i.Status,
			&i.EffectiveStatus,
			&i.OpensAt,
			&i.ClosesAt,
			&i.DurationMinutes,
			&i.MaxScore,
			&i.PublishedAt,
			&i.Version,
			&i.CreatedAt,
			&i.ItemsCount,
			&i.AttemptsStarted,
			&i.AttemptsGraded,
			&i.MyAttemptID,
			&i.MyAttemptStatus,
			&i.MyDeadlineAt,
			&i.MySubmittedAt,
			&i.MyAdjustedScore,
			&i.MyAutoScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examLock = `-- name: ExamLock :one
select id, course_id, title, instructions, kind, status, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, publish_hold, regrading, published_at, created_by, version, created_at, updated_at from exams where course_id = $1 and id = $2 for update
`

type ExamLockParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) ExamLock(ctx context.Context, arg ExamLockParams) (Exam, error) {
	row := q.db.QueryRow(ctx, examLock, arg.CourseID, arg.ID)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Instructions,
		&i.Kind,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DurationMinutes,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.MaxScore,
		&i.RoundingStep,
		&i.MultiScoring,
		&i.RevealAnswers,
		&i.AppealDays,
		&i.PublishHold,
		&i.Regrading,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const examNotifyScheduled = `-- name: ExamNotifyScheduled :execrows
insert into notifications (user_id, course_id, type, title, body, link, dedupe_key)
select e.user_id, e.course_id, 'EXAM_SCHEDULED', $1, $2, $3, 'exam.scheduled:' || $4::text || ':' || e.user_id::text
from enrollments e
where e.course_id = $5 and e.role_in_course = 'STUDENT' and e.status = 'ACTIVE'
on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing
`

type ExamNotifyScheduledParams struct {
	Title    string
	Body     *string
	Link     *string
	ExamID   string
	CourseID uuid.UUID
}

// Thông báo EXAM_SCHEDULED cho mọi sinh viên ACTIVE; khử trùng theo (bài, người).
func (q *Queries) ExamNotifyScheduled(ctx context.Context, arg ExamNotifyScheduledParams) (int64, error) {
	result, err := q.db.Exec(ctx, examNotifyScheduled,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.ExamID,
		arg.CourseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const examNotifyUnscheduled = `-- name: ExamNotifyUnscheduled :execrows
insert into notifications (user_id, course_id, type, title, body, link, dedupe_key)
select u, $1, 'EXAM_UNSCHEDULED', $2, $3, $4, 'exam.unscheduled:' || $5::text || ':' || u::text
from unnest($6::text[]::uuid[]) as u
on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing
`

type ExamNotifyUnscheduledParams struct {
	CourseID *uuid.UUID
	Title    string
	Body     *string
	Link     *string
	OutboxID string
	UserIds  []string
}

func (q *Queries) ExamNotifyUnscheduled(ctx context.Context, arg ExamNotifyUnscheduledParams) (int64, error) {
	result, err := q.db.Exec(ctx, examNotifyUnscheduled,
		arg.CourseID,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.OutboxID,
		arg.UserIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const examPreviewItems = `-- name: ExamPreviewItems :many
select i.id as item_id, i.position, i.points, q.id as question_id, q.type, q.stem,
       cp.languages, cp.time_limit_ms, cp.memory_limit_mb, cp.starter_code
from exam_items i
join question_bank q on q.course_id = i.course_id and q.id = i.question_id
left join code_problems cp on cp.course_id = q.course_id and cp.question_id = q.id
where i.course_id = $1 and i.exam_id = $2
order by i.position
`

type ExamPreviewItemsParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type ExamPreviewItemsRow struct {
	ItemID        uuid.UUID
	Position      int16
	Points        decimal.Decimal
	QuestionID    uuid.UUID
	Type          QuestionType
	Stem          string
	Languages     []string
	TimeLimitMs   *int32
	MemoryLimitMb *int32
	StarterCode   json.RawMessage
}

func (q *Queries) ExamPreviewItems(ctx context.Context, arg ExamPreviewItemsParams) ([]ExamPreviewItemsRow, error) {
	rows, err := q.db.Query(ctx, examPreviewItems, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamPreviewItemsRow{}
	for rows.Next() {
		var i ExamPreviewItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Position,
			&i.Points,
			&i.QuestionID,
			&i.Type,
			&i.Stem,
			&i.Languages,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.StarterCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examPreviewOptions = `-- name: ExamPreviewOptions :many
select o.id, o.question_id, o.position, o.body, o.pinned_last
from question_options o
join exam_items i on i.course_id = o.course_id and i.question_id = o.question_id
where i.course_id = $1 and i.exam_id = $2
order by o.question_id, o.position
`

type ExamPreviewOptionsParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type ExamPreviewOptionsRow struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Position   int16
	Body       string
	PinnedLast bool
}

func (q *Queries) ExamPreviewOptions(ctx context.Context, arg ExamPreviewOptionsParams) ([]ExamPreviewOptionsRow, error) {
	rows, err := q.db.Query(ctx, examPreviewOptions, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamPreviewOptionsRow{}
	for rows.Next() {
		var i ExamPreviewOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Position,
			&i.Body,
			&i.PinnedLast,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examPreviewSamples = `-- name: ExamPreviewSamples :many
select t.problem_id, t.name, t.input, t.expected
from code_testcases t
join exam_items i on i.course_id = t.course_id and i.question_id = t.problem_id
where i.course_id = $1 and i.exam_id = $2
  and t.is_sample and t.approved and t.input is not null and t.expected is not null
order by t.problem_id, t.position
`

type ExamPreviewSamplesParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type ExamPreviewSamplesRow struct {
	ProblemID uuid.UUID
	Name      string
	Input     *string
	Expected  *string
}

// Test MẪU đã duyệt (sinh viên được thấy); test lưu ở kho đối tượng (> 64 KiB) không phải test mẫu thực tế nên bỏ.
func (q *Queries) ExamPreviewSamples(ctx context.Context, arg ExamPreviewSamplesParams) ([]ExamPreviewSamplesRow, error) {
	rows, err := q.db.Query(ctx, examPreviewSamples, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamPreviewSamplesRow{}
	for rows.Next() {
		var i ExamPreviewSamplesRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.Name,
			&i.Input,
			&i.Expected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examQuestionsByIDs = `-- name: ExamQuestionsByIDs :many
select id, type, review_status, archived_at from question_bank
where course_id = $1 and id = any($2::text[]::uuid[])
`

type ExamQuestionsByIDsParams struct {
	CourseID uuid.UUID
	Ids      []string
}

type ExamQuestionsByIDsRow struct {
	ID           uuid.UUID
	Type         QuestionType
	ReviewStatus QuestionReviewStatus
	ArchivedAt   *time.Time
}

// Câu của CÙNG lớp theo danh sách id (id của lớp khác không trả về → QUESTION_NOT_IN_COURSE). `::text[]::uuid[]` vì PgBouncer.
func (q *Queries) ExamQuestionsByIDs(ctx context.Context, arg ExamQuestionsByIDsParams) ([]ExamQuestionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, examQuestionsByIDs, arg.CourseID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamQuestionsByIDsRow{}
	for rows.Next() {
		var i ExamQuestionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ReviewStatus,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examRecallScheduled = `-- name: ExamRecallScheduled :many
delete from notifications
where course_id = $1 and type = 'EXAM_SCHEDULED' and dedupe_key like 'exam.scheduled:' || $2::text || ':%'
returning user_id
`

type ExamRecallScheduledParams struct {
	CourseID *uuid.UUID
	ExamID   string
}

// Thu hồi thông báo lịch của một bài (khi bỏ lịch): trả người đã nhận để báo "hoãn". Xoá cả dấu khử trùng nên lần lên lịch sau báo lại được.
func (q *Queries) ExamRecallScheduled(ctx context.Context, arg ExamRecallScheduledParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, examRecallScheduled, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examSetKind = `-- name: ExamSetKind :exec
update exams set kind = $1, version = version + 1 where course_id = $2 and id = $3
`

type ExamSetKindParams struct {
	Kind     ExamKind
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) ExamSetKind(ctx context.Context, arg ExamSetKindParams) error {
	_, err := q.db.Exec(ctx, examSetKind, arg.Kind, arg.CourseID, arg.ID)
	return err
}

const examSetStatus = `-- name: ExamSetStatus :one
update exams set status = $1, version = version + 1
where course_id = $2 and id = $3 and status = $4
returning id, course_id, title, instructions, kind, status, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, publish_hold, regrading, published_at, created_by, version, created_at, updated_at
`

type ExamSetStatusParams struct {
	ToStatus   ExamStatus
	CourseID   uuid.UUID
	ID         uuid.UUID
	FromStatus ExamStatus
}

// Chuyển trạng thái một bài (schedule / unschedule): `from_status` làm điều kiện để hai người gọi cùng lúc không chuyển hai lần.
func (q *Queries) ExamSetStatus(ctx context.Context, arg ExamSetStatusParams) (Exam, error) {
	row := q.db.QueryRow(ctx, examSetStatus,
		arg.ToStatus,
		arg.CourseID,
		arg.ID,
		arg.FromStatus,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Instructions,
		&i.Kind,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DurationMinutes,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.MaxScore,
		&i.RoundingStep,
		&i.MultiScoring,
		&i.RevealAnswers,
		&i.AppealDays,
		&i.PublishHold,
		&i.Regrading,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const examShare = `-- name: ExamShare :one
select id, course_id, title, instructions, kind, status, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, publish_hold, regrading, published_at, created_by, version, created_at, updated_at from exams where course_id = $1 and id = $2 for share
`

type ExamShareParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

// Bắt đầu làm bài: khoá chia sẻ hàng bài để `unschedule` / `extend` (FOR UPDATE) chờ — không có lượt nào chen vào giữa lúc kiểm trạng thái và INSERT (SRS 4.3.1).
func (q *Queries) ExamShare(ctx context.Context, arg ExamShareParams) (Exam, error) {
	row := q.db.QueryRow(ctx, examShare, arg.CourseID, arg.ID)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Instructions,
		&i.Kind,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DurationMinutes,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.MaxScore,
		&i.RoundingStep,
		&i.MultiScoring,
		&i.RevealAnswers,
		&i.AppealDays,
		&i.PublishHold,
		&i.Regrading,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const examTickClose = `-- name: ExamTickClose :many
update exams set status = 'CLOSED', version = version + 1
where status in ('SCHEDULED', 'OPEN') and closes_at <= $1::timestamptz
returning id, course_id
`

type ExamTickCloseRow struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

// (2) đóng bài đến hạn; SCHEDULED mà đã quá closes_at (máy chủ tắt dài) chuyển thẳng CLOSED.
func (q *Queries) ExamTickClose(ctx context.Context, now time.Time) ([]ExamTickCloseRow, error) {
	rows, err := q.db.Query(ctx, examTickClose, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamTickCloseRow{}
	for rows.Next() {
		var i ExamTickCloseRow
		if err := rows.Scan(&i.ID, &i.CourseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examTickOpen = `-- name: ExamTickOpen :many
update exams set status = 'OPEN', version = version + 1
where status = 'SCHEDULED' and opens_at <= $1::timestamptz and closes_at > $1::timestamptz
returning id, course_id
`

type ExamTickOpenRow struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

// (1) mở bài đến giờ (chưa quá closes_at); idempotent nhờ `where status = 'SCHEDULED'`.
func (q *Queries) ExamTickOpen(ctx context.Context, now time.Time) ([]ExamTickOpenRow, error) {
	rows, err := q.db.Query(ctx, examTickOpen, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamTickOpenRow{}
	for rows.Next() {
		var i ExamTickOpenRow
		if err := rows.Scan(&i.ID, &i.CourseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examUpdate = `-- name: ExamUpdate :one
update exams
set title = $1, instructions = $2, opens_at = $3, closes_at = $4,
    duration_minutes = $5, shuffle_questions = $6, shuffle_options = $7,
    max_score = $8, rounding_step = $9, multi_scoring = $10,
    reveal_answers = $11, appeal_days = $12, version = version + 1
where course_id = $13 and id = $14 and version = $15
returning id, course_id, title, instructions, kind, status, opens_at, closes_at, duration_minutes, shuffle_questions, shuffle_options, max_score, rounding_step, multi_scoring, reveal_answers, appeal_days, publish_hold, regrading, published_at, created_by, version, created_at, updated_at
`

type ExamUpdateParams struct {
	Title            string
	Instructions     *string
	OpensAt          *time.Time
	ClosesAt         *time.Time
	DurationMinutes  *int16
	ShuffleQuestions bool
	ShuffleOptions   bool
	MaxScore         decimal.Decimal
	RoundingStep     decimal.Decimal
	MultiScoring     MultiScoring
	RevealAnswers    bool
	AppealDays       int16
	CourseID         uuid.UUID
	ID               uuid.UUID
	ExpectedVersion  int32
}

// Ghi mọi trường người dùng sửa được; `expected_version` là khoá lạc quan (0 dòng = sai version). Service đã quyết trường nào được đổi theo trạng thái.
func (q *Queries) ExamUpdate(ctx context.Context, arg ExamUpdateParams) (Exam, error) {
	row := q.db.QueryRow(ctx, examUpdate,
		arg.Title,
		arg.Instructions,
		arg.OpensAt,
		arg.ClosesAt,
		arg.DurationMinutes,
		arg.ShuffleQuestions,
		arg.ShuffleOptions,
		arg.MaxScore,
		arg.RoundingStep,
		arg.MultiScoring,
		arg.RevealAnswers,
		arg.AppealDays,
		arg.CourseID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Instructions,
		&i.Kind,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DurationMinutes,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.MaxScore,
		&i.RoundingStep,
		&i.MultiScoring,
		&i.RevealAnswers,
		&i.AppealDays,
		&i.PublishHold,
		&i.Regrading,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const todayStudentExams = `-- name: TodayStudentExams :many
select e.id, e.course_id, e.title, e.opens_at, e.closes_at, e.duration_minutes, a.status as attempt_status, a.deadline_at as attempt_deadline
from exams e
left join exam_attempts a on a.course_id = e.course_id and a.exam_id = e.id and a.student_id = $1
where e.course_id = any($2::text[]::uuid[])
  and e.status in ('SCHEDULED', 'OPEN')
  and e.closes_at > $3::timestamptz
  and e.opens_at <= $4::timestamptz
  and (a.id is null or (a.status = 'IN_PROGRESS' and a.deadline_at > $3::timestamptz))
order by e.opens_at, e.id
`

type TodayStudentExamsParams struct {
	UserID    uuid.UUID
	CourseIds []string
	Now       time.Time
	Horizon   time.Time
}

type TodayStudentExamsRow struct {
	ID              uuid.UUID
	CourseID        uuid.UUID
	Title           string
	OpensAt         *time.Time
	ClosesAt        *time.Time
	DurationMinutes *int16
	AttemptStatus   *AttemptStatus
	AttemptDeadline *time.Time
}

// "Hôm nay" của sinh viên: bài SCHEDULED / OPEN còn hạn, mở trong `horizon`, chưa có lượt làm hoặc lượt còn đang làm — MỘT truy vấn cho mọi lớp.
func (q *Queries) TodayStudentExams(ctx context.Context, arg TodayStudentExamsParams) ([]TodayStudentExamsRow, error) {
	rows, err := q.db.Query(ctx, todayStudentExams,
		arg.UserID,
		arg.CourseIds,
		arg.Now,
		arg.Horizon,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayStudentExamsRow{}
	for rows.Next() {
		var i TodayStudentExamsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.OpensAt,
			&i.ClosesAt,
			&i.DurationMinutes,
			&i.AttemptStatus,
			&i.AttemptDeadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
