// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_integrity.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const attemptOfExam = `-- name: AttemptOfExam :one
select id, student_id from exam_attempts where course_id = $1 and exam_id = $2 and id = $3
`

type AttemptOfExamParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
	ID       uuid.UUID
}

type AttemptOfExamRow struct {
	ID        uuid.UUID
	StudentID uuid.UUID
}

// Lượt thuộc bài thi này (Giảng viên đọc log): không có → 404.
func (q *Queries) AttemptOfExam(ctx context.Context, arg AttemptOfExamParams) (AttemptOfExamRow, error) {
	row := q.db.QueryRow(ctx, attemptOfExam, arg.CourseID, arg.ExamID, arg.ID)
	var i AttemptOfExamRow
	err := row.Scan(&i.ID, &i.StudentID)
	return i, err
}

const examEventCount = `-- name: ExamEventCount :one
select count(*)::int from exam_events where course_id = $1 and attempt_id = $2
`

type ExamEventCountParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
}

func (q *Queries) ExamEventCount(ctx context.Context, arg ExamEventCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, examEventCount, arg.CourseID, arg.AttemptID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const examEventsInsert = `-- name: ExamEventsInsert :exec
insert into exam_events (course_id, exam_id, attempt_id, student_id, type, occurred_at, client_at, meta)
select $1, $2, $3, $4, x.type::exam_event_type, $5, x.client_at, x.meta
from jsonb_to_recordset($6::jsonb) as x(type text, client_at timestamptz, meta jsonb)
`

type ExamEventsInsertParams struct {
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	AttemptID uuid.UUID
	StudentID uuid.UUID
	At        time.Time
	Rows      json.RawMessage
}

// Một lệnh cho cả lô: `rows` = [{"type","client_at","meta"}]; `occurred_at` là giờ MÁY CHỦ.
func (q *Queries) ExamEventsInsert(ctx context.Context, arg ExamEventsInsertParams) error {
	_, err := q.db.Exec(ctx, examEventsInsert,
		arg.CourseID,
		arg.ExamID,
		arg.AttemptID,
		arg.StudentID,
		arg.At,
		arg.Rows,
	)
	return err
}

const examEventsList = `-- name: ExamEventsList :many
select id, type, occurred_at, client_at, meta from exam_events
where course_id = $1 and exam_id = $2 and attempt_id = $3
  and ($4::timestamptz is null or (occurred_at, id) < ($4::timestamptz, $5::uuid))
order by occurred_at desc, id desc
limit $6
`

type ExamEventsListParams struct {
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	AttemptID uuid.UUID
	CursorAt  *time.Time
	CursorID  *uuid.UUID
	RowLimit  int32
}

type ExamEventsListRow struct {
	ID         uuid.UUID
	Type       ExamEventType
	OccurredAt time.Time
	ClientAt   *time.Time
	Meta       json.RawMessage
}

func (q *Queries) ExamEventsList(ctx context.Context, arg ExamEventsListParams) ([]ExamEventsListRow, error) {
	rows, err := q.db.Query(ctx, examEventsList,
		arg.CourseID,
		arg.ExamID,
		arg.AttemptID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamEventsListRow{}
	for rows.Next() {
		var i ExamEventsListRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OccurredAt,
			&i.ClientAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examEventsSummary = `-- name: ExamEventsSummary :many
select type, count(*)::int as n,
       coalesce(sum((meta->>'duration_ms')::bigint), 0)::bigint as duration_ms,
       coalesce(sum((meta->>'chars')::bigint), 0)::bigint as chars
from exam_events
where course_id = $1 and attempt_id = $2
group by type
`

type ExamEventsSummaryParams struct {
	CourseID  uuid.UUID
	AttemptID uuid.UUID
}

type ExamEventsSummaryRow struct {
	Type       ExamEventType
	N          int32
	DurationMs int64
	Chars      int64
}

// Tóm tắt mỗi lượt theo loại: số lần, tổng thời gian rời tab (ms), tổng ký tự dán.
func (q *Queries) ExamEventsSummary(ctx context.Context, arg ExamEventsSummaryParams) ([]ExamEventsSummaryRow, error) {
	rows, err := q.db.Query(ctx, examEventsSummary, arg.CourseID, arg.AttemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamEventsSummaryRow{}
	for rows.Next() {
		var i ExamEventsSummaryRow
		if err := rows.Scan(
			&i.Type,
			&i.N,
			&i.DurationMs,
			&i.Chars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLatestAttempt = `-- name: LockLatestAttempt :one

select id, exam_id, deadline_at from exam_attempts
where student_id = $1 and status = 'IN_PROGRESS'
  and deadline_at + make_interval(secs => $2::int) > $3::timestamptz
order by deadline_at desc
limit 1
`

type LockLatestAttemptParams struct {
	StudentID    uuid.UUID
	GraceSeconds int32
	Now          time.Time
}

type LockLatestAttemptRow struct {
	ID         uuid.UUID
	ExamID     uuid.UUID
	DeadlineAt time.Time
}

// Liêm chính (US-PE-07, SRS FEAT-weekly-exam 4.7, 5.12): khoá chat, sự kiện rời tab / dán, so độ giống.
// Lượt IN_PROGRESS còn trong hạn + grace của sinh viên có `deadline_at` MUỘN nhất (mọi lớp). Dùng chỉ mục từng phần `exam_attempts_running_idx`.
func (q *Queries) LockLatestAttempt(ctx context.Context, arg LockLatestAttemptParams) (LockLatestAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockLatestAttempt, arg.StudentID, arg.GraceSeconds, arg.Now)
	var i LockLatestAttemptRow
	err := row.Scan(&i.ID, &i.ExamID, &i.DeadlineAt)
	return i, err
}

const lockRunningStudents = `-- name: LockRunningStudents :many
select student_id from exam_attempts where course_id = $1 and exam_id = $2 and status = 'IN_PROGRESS'
`

type LockRunningStudentsParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

func (q *Queries) LockRunningStudents(ctx context.Context, arg LockRunningStudentsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockRunningStudents, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var student_id uuid.UUID
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStillRunning = `-- name: LockStillRunning :many
select id from exam_attempts where id = any($1::text[]::uuid[]) and status = 'IN_PROGRESS'
`

func (q *Queries) LockStillRunning(ctx context.Context, ids []string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockStillRunning, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
