// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_similarity.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const similarityDueExams = `-- name: SimilarityDueExams :many
select e.course_id, e.id, e.created_by from exams e
where e.status in ('CLOSED', 'PUBLISHED') and e.kind in ('CODE', 'MIXED')
  and not exists (select 1 from exam_attempts a where a.course_id = e.course_id and a.exam_id = e.id and a.status = 'IN_PROGRESS')
  and not exists (select 1 from audit_log l where l.course_id = e.course_id and l.entity = 'exam' and l.entity_id = e.id::text and l.action in ('exam.similarity.queued', 'exam.similarity.run'))
order by e.closes_at
limit 20
`

type SimilarityDueExamsRow struct {
	CourseID  uuid.UUID
	ID        uuid.UUID
	CreatedBy uuid.UUID
}

// Bài code đã đóng, mọi lượt đã nộp, chưa từng xếp việc so độ giống (dấu vết ở audit_log): bộ lập lịch xếp việc `exam.similarity`.
func (q *Queries) SimilarityDueExams(ctx context.Context) ([]SimilarityDueExamsRow, error) {
	rows, err := q.db.Query(ctx, similarityDueExams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimilarityDueExamsRow{}
	for rows.Next() {
		var i SimilarityDueExamsRow
		if err := rows.Scan(&i.CourseID, &i.ID, &i.CreatedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const similarityFinalSubmissions = `-- name: SimilarityFinalSubmissions :many

select distinct on (s.attempt_id, s.item_id) s.id, s.attempt_id, s.item_id, s.problem_id, s.student_id, s.language, s.source
from code_submissions s
where s.course_id = $1 and s.exam_id = $2 and s.kind = 'SUBMIT' and s.status <> 'SUPERSEDED'
order by s.attempt_id, s.item_id, s.created_at desc, s.id desc
`

type SimilarityFinalSubmissionsParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

type SimilarityFinalSubmissionsRow struct {
	ID        uuid.UUID
	AttemptID uuid.UUID
	ItemID    uuid.UUID
	ProblemID uuid.UUID
	StudentID uuid.UUID
	Language  string
	Source    string
}

// So độ giống mã nguồn giữa các bản nộp cuối (US-PE-07 AC7–AC9, SRS FEAT-weekly-exam 4.7, 5.14). Mã không rời hệ thống.
// Bản SUBMIT cuối (mới nhất chưa bị thay, kể cả bản tự động) của mỗi (lượt, câu).
func (q *Queries) SimilarityFinalSubmissions(ctx context.Context, arg SimilarityFinalSubmissionsParams) ([]SimilarityFinalSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, similarityFinalSubmissions, arg.CourseID, arg.ExamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimilarityFinalSubmissionsRow{}
	for rows.Next() {
		var i SimilarityFinalSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.ItemID,
			&i.ProblemID,
			&i.StudentID,
			&i.Language,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const similarityGet = `-- name: SimilarityGet :one
select r.id, r.problem_id, qb.title as problem_title, r.run_id, r.attempt_a, r.attempt_b, r.submission_a, r.submission_b, ua.full_name as name_a, ub.full_name as name_b,
       r.score, r.shared_fingerprints, r.flagged, r.review_state, r.note, r.reviewed_at, r.created_at
from similarity_reports r
join question_bank qb on qb.course_id = r.course_id and qb.id = r.problem_id
join exam_attempts aa on aa.course_id = r.course_id and aa.id = r.attempt_a
join exam_attempts ab on ab.course_id = r.course_id and ab.id = r.attempt_b
join users ua on ua.id = aa.student_id
join users ub on ub.id = ab.student_id
where r.course_id = $1 and r.exam_id = $2 and r.id = $3
`

type SimilarityGetParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
	ID       uuid.UUID
}

type SimilarityGetRow struct {
	ID                 uuid.UUID
	ProblemID          uuid.UUID
	ProblemTitle       string
	RunID              uuid.UUID
	AttemptA           uuid.UUID
	AttemptB           uuid.UUID
	SubmissionA        uuid.UUID
	SubmissionB        uuid.UUID
	NameA              string
	NameB              string
	Score              decimal.Decimal
	SharedFingerprints int32
	Flagged            bool
	ReviewState        SimilarityReviewState
	Note               *string
	ReviewedAt         *time.Time
	CreatedAt          time.Time
}

func (q *Queries) SimilarityGet(ctx context.Context, arg SimilarityGetParams) (SimilarityGetRow, error) {
	row := q.db.QueryRow(ctx, similarityGet, arg.CourseID, arg.ExamID, arg.ID)
	var i SimilarityGetRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ProblemTitle,
		&i.RunID,
		&i.AttemptA,
		&i.AttemptB,
		&i.SubmissionA,
		&i.SubmissionB,
		&i.NameA,
		&i.NameB,
		&i.Score,
		&i.SharedFingerprints,
		&i.Flagged,
		&i.ReviewState,
		&i.Note,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const similarityInsert = `-- name: SimilarityInsert :exec
insert into similarity_reports (course_id, exam_id, problem_id, run_id, submission_a, submission_b, attempt_a, attempt_b, score, shared_fingerprints, flagged)
select $1, $2, x.problem_id, $3, x.sa, x.sb, x.aa, x.ab, (x.score::numeric / 1000)::numeric(4,3), x.shared, x.flagged
from jsonb_to_recordset($4::jsonb) as x(problem_id uuid, sa uuid, sb uuid, aa uuid, ab uuid, score int, shared int, flagged boolean)
`

type SimilarityInsertParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
	RunID    uuid.UUID
	Rows     json.RawMessage
}

// Một lệnh cho cả lô (≤ 200 cặp). `score` gửi dạng ‰ (số nguyên) rồi chia 1000: không đi qua số thực.
func (q *Queries) SimilarityInsert(ctx context.Context, arg SimilarityInsertParams) error {
	_, err := q.db.Exec(ctx, similarityInsert,
		arg.CourseID,
		arg.ExamID,
		arg.RunID,
		arg.Rows,
	)
	return err
}

const similarityLatestRun = `-- name: SimilarityLatestRun :one
select run_id from similarity_reports where course_id = $1 and exam_id = $2 order by created_at desc, id desc limit 1
`

type SimilarityLatestRunParams struct {
	CourseID uuid.UUID
	ExamID   uuid.UUID
}

func (q *Queries) SimilarityLatestRun(ctx context.Context, arg SimilarityLatestRunParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, similarityLatestRun, arg.CourseID, arg.ExamID)
	var run_id uuid.UUID
	err := row.Scan(&run_id)
	return run_id, err
}

const similarityList = `-- name: SimilarityList :many
select r.id, r.problem_id, qb.title as problem_title, r.run_id, r.attempt_a, r.attempt_b, ua.full_name as name_a, ub.full_name as name_b,
       r.score, r.shared_fingerprints, r.flagged, r.review_state, r.note, r.reviewed_at, r.created_at
from similarity_reports r
join question_bank qb on qb.course_id = r.course_id and qb.id = r.problem_id
join exam_attempts aa on aa.course_id = r.course_id and aa.id = r.attempt_a
join exam_attempts ab on ab.course_id = r.course_id and ab.id = r.attempt_b
join users ua on ua.id = aa.student_id
join users ub on ub.id = ab.student_id
where r.course_id = $1 and r.exam_id = $2 and r.run_id = $3
  and (not $4::boolean or r.flagged)
  and ($5::numeric is null or (r.score, r.id) < ($5::numeric, $6::uuid))
order by r.score desc, r.id desc
limit $7
`

type SimilarityListParams struct {
	CourseID    uuid.UUID
	ExamID      uuid.UUID
	RunID       uuid.UUID
	FlaggedOnly bool
	CursorScore decimal.NullDecimal
	CursorID    *uuid.UUID
	RowLimit    int32
}

type SimilarityListRow struct {
	ID                 uuid.UUID
	ProblemID          uuid.UUID
	ProblemTitle       string
	RunID              uuid.UUID
	AttemptA           uuid.UUID
	AttemptB           uuid.UUID
	NameA              string
	NameB              string
	Score              decimal.Decimal
	SharedFingerprints int32
	Flagged            bool
	ReviewState        SimilarityReviewState
	Note               *string
	ReviewedAt         *time.Time
	CreatedAt          time.Time
}

// Điểm cao trước (cursor theo (score, id)); mặc định bản chạy mới nhất; `flagged_only` lọc cặp gắn cờ.
func (q *Queries) SimilarityList(ctx context.Context, arg SimilarityListParams) ([]SimilarityListRow, error) {
	rows, err := q.db.Query(ctx, similarityList,
		arg.CourseID,
		arg.ExamID,
		arg.RunID,
		arg.FlaggedOnly,
		arg.CursorScore,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimilarityListRow{}
	for rows.Next() {
		var i SimilarityListRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.ProblemTitle,
			&i.RunID,
			&i.AttemptA,
			&i.AttemptB,
			&i.NameA,
			&i.NameB,
			&i.Score,
			&i.SharedFingerprints,
			&i.Flagged,
			&i.ReviewState,
			&i.Note,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const similarityReview = `-- name: SimilarityReview :one
update similarity_reports set review_state = $1, note = $2, reviewed_by = $3, reviewed_at = $4
where course_id = $5 and exam_id = $6 and id = $7
returning id
`

type SimilarityReviewParams struct {
	State    SimilarityReviewState
	Note     *string
	Reviewer *uuid.UUID
	At       *time.Time
	CourseID uuid.UUID
	ExamID   uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) SimilarityReview(ctx context.Context, arg SimilarityReviewParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, similarityReview,
		arg.State,
		arg.Note,
		arg.Reviewer,
		arg.At,
		arg.CourseID,
		arg.ExamID,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const similaritySource = `-- name: SimilaritySource :one
select language, source from code_submissions where course_id = $1 and id = $2
`

type SimilaritySourceParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

type SimilaritySourceRow struct {
	Language string
	Source   string
}

func (q *Queries) SimilaritySource(ctx context.Context, arg SimilaritySourceParams) (SimilaritySourceRow, error) {
	row := q.db.QueryRow(ctx, similaritySource, arg.CourseID, arg.ID)
	var i SimilaritySourceRow
	err := row.Scan(&i.Language, &i.Source)
	return i, err
}

const similarityStarters = `-- name: SimilarityStarters :many
select question_id, starter_code from code_problems where course_id = $1 and question_id = any($2::text[]::uuid[])
`

type SimilarityStartersParams struct {
	CourseID uuid.UUID
	Ids      []string
}

type SimilarityStartersRow struct {
	QuestionID  uuid.UUID
	StarterCode json.RawMessage
}

func (q *Queries) SimilarityStarters(ctx context.Context, arg SimilarityStartersParams) ([]SimilarityStartersRow, error) {
	rows, err := q.db.Query(ctx, similarityStarters, arg.CourseID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimilarityStartersRow{}
	for rows.Next() {
		var i SimilarityStartersRow
		if err := rows.Scan(&i.QuestionID, &i.StarterCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
