// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forum.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const bumpForumThread = `-- name: BumpForumThread :exec
update forum_threads set reply_count = reply_count + 1, last_activity_at = now()
where course_id = $1 and id = $2
`

type BumpForumThreadParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) BumpForumThread(ctx context.Context, arg BumpForumThreadParams) error {
	_, err := q.db.Exec(ctx, bumpForumThread, arg.CourseID, arg.ID)
	return err
}

const getForumThread = `-- name: GetForumThread :one
select id, course_id, author_id, title, body, tags, week_no, state, ai_state, ai_skip_reason, similar_of, pinned_at, reply_count, last_activity_at, embedding, deleted_at, version, created_at, updated_at from forum_threads where course_id = $1 and id = $2 and deleted_at is null
`

type GetForumThreadParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetForumThread(ctx context.Context, arg GetForumThreadParams) (ForumThread, error) {
	row := q.db.QueryRow(ctx, getForumThread, arg.CourseID, arg.ID)
	var i ForumThread
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.WeekNo,
		&i.State,
		&i.AiState,
		&i.AiSkipReason,
		&i.SimilarOf,
		&i.PinnedAt,
		&i.ReplyCount,
		&i.LastActivityAt,
		&i.Embedding,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertForumPost = `-- name: InsertForumPost :one
insert into forum_posts (course_id, thread_id, author_id, kind, body, verification_state, citations, confidence)
values ($1, $2, $3, $4, $5, $6,
        $7, $8)
returning id, course_id, thread_id, author_id, kind, body, verification_state, citations, confidence, ai_body, verified_by, verified_at, hidden_at, hidden_reason, hidden_by, deleted_at, embedding, version, created_at, updated_at
`

type InsertForumPostParams struct {
	CourseID          uuid.UUID
	ThreadID          uuid.UUID
	AuthorID          *uuid.UUID
	Kind              PostKind
	Body              string
	VerificationState PostVerification
	Citations         json.RawMessage
	Confidence        decimal.NullDecimal
}

func (q *Queries) InsertForumPost(ctx context.Context, arg InsertForumPostParams) (ForumPost, error) {
	row := q.db.QueryRow(ctx, insertForumPost,
		arg.CourseID,
		arg.ThreadID,
		arg.AuthorID,
		arg.Kind,
		arg.Body,
		arg.VerificationState,
		arg.Citations,
		arg.Confidence,
	)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ThreadID,
		&i.AuthorID,
		&i.Kind,
		&i.Body,
		&i.VerificationState,
		&i.Citations,
		&i.Confidence,
		&i.AiBody,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.HiddenAt,
		&i.HiddenReason,
		&i.HiddenBy,
		&i.DeletedAt,
		&i.Embedding,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertForumThread = `-- name: InsertForumThread :one

insert into forum_threads (course_id, author_id, title, body, tags, week_no)
values ($1, $2, $3, $4, $5, $6)
returning id, course_id, author_id, title, body, tags, week_no, state, ai_state, ai_skip_reason, similar_of, pinned_at, reply_count, last_activity_at, embedding, deleted_at, version, created_at, updated_at
`

type InsertForumThreadParams struct {
	CourseID uuid.UUID
	AuthorID uuid.UUID
	Title    string
	Body     string
	Tags     []string
	WeekNo   *int16
}

// Threads (US-P3-01; service ở US-P3-06).
func (q *Queries) InsertForumThread(ctx context.Context, arg InsertForumThreadParams) (ForumThread, error) {
	row := q.db.QueryRow(ctx, insertForumThread,
		arg.CourseID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.WeekNo,
	)
	var i ForumThread
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.WeekNo,
		&i.State,
		&i.AiState,
		&i.AiSkipReason,
		&i.SimilarOf,
		&i.PinnedAt,
		&i.ReplyCount,
		&i.LastActivityAt,
		&i.Embedding,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listForumPosts = `-- name: ListForumPosts :many
select id, course_id, thread_id, author_id, kind, body, verification_state, citations, confidence, ai_body, verified_by, verified_at, hidden_at, hidden_reason, hidden_by, deleted_at, embedding, version, created_at, updated_at from forum_posts
where thread_id = $1 and deleted_at is null
order by created_at, id
limit $2
`

type ListForumPostsParams struct {
	ThreadID  uuid.UUID
	PageLimit int32
}

func (q *Queries) ListForumPosts(ctx context.Context, arg ListForumPostsParams) ([]ForumPost, error) {
	rows, err := q.db.Query(ctx, listForumPosts, arg.ThreadID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForumPost{}
	for rows.Next() {
		var i ForumPost
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ThreadID,
			&i.AuthorID,
			&i.Kind,
			&i.Body,
			&i.VerificationState,
			&i.Citations,
			&i.Confidence,
			&i.AiBody,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.HiddenAt,
			&i.HiddenReason,
			&i.HiddenBy,
			&i.DeletedAt,
			&i.Embedding,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumThreads = `-- name: ListForumThreads :many
select id, course_id, author_id, title, body, tags, week_no, state, ai_state, ai_skip_reason, similar_of, pinned_at, reply_count, last_activity_at, embedding, deleted_at, version, created_at, updated_at from forum_threads
where course_id = $1 and deleted_at is null
  and ($2::timestamptz is null or (last_activity_at, id) < ($2::timestamptz, $3::uuid))
order by last_activity_at desc, id desc
limit $4
`

type ListForumThreadsParams struct {
	CourseID  uuid.UUID
	CursorAt  *time.Time
	CursorID  *uuid.UUID
	PageLimit int32
}

func (q *Queries) ListForumThreads(ctx context.Context, arg ListForumThreadsParams) ([]ForumThread, error) {
	rows, err := q.db.Query(ctx, listForumThreads,
		arg.CourseID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForumThread{}
	for rows.Next() {
		var i ForumThread
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.WeekNo,
			&i.State,
			&i.AiState,
			&i.AiSkipReason,
			&i.SimilarOf,
			&i.PinnedAt,
			&i.ReplyCount,
			&i.LastActivityAt,
			&i.Embedding,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
