// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one

select id, user_id, endpoint, key, request_hash, status_code, response, created_at from idempotency_keys
where user_id = $1 and endpoint = $2 and key = $3
`

type GetIdempotencyKeyParams struct {
	UserID   uuid.UUID
	Endpoint string
	Key      string
}

// Dự phòng bền cho Redis (SRS 5.5): khoá theo (user_id, endpoint, key).
func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Endpoint, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :execrows
insert into idempotency_keys (user_id, endpoint, key, request_hash, status_code, response)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
on conflict (user_id, endpoint, key) do nothing
`

type InsertIdempotencyKeyParams struct {
	UserID      uuid.UUID
	Endpoint    string
	Key         string
	RequestHash string
	StatusCode  int16
	Response    json.RawMessage
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.UserID,
		arg.Endpoint,
		arg.Key,
		arg.RequestHash,
		arg.StatusCode,
		arg.Response,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
