// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"

	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

const ingestClaim = `-- name: IngestClaim :one

update documents d
set status = 'PROCESSING', updated_at = now(), error = null
where d.id = $1
  and (d.status = 'QUEUED' or (d.status = 'PROCESSING' and d.updated_at < now() - make_interval(secs => $2::float8)))
  and not exists (select 1 from documents x where x.course_id = d.course_id and x.status = 'PROCESSING' and x.id <> d.id
                  and x.updated_at > now() - make_interval(secs => $2::float8))
returning d.id, d.course_id, d.title, d.type, d.filename, d.mime_type, d.blob_key, d.sha256, d.visible_to_students, d.use_for_rag, d.uploaded_by, d.version
`

type IngestClaimParams struct {
	ID       uuid.UUID
	IdleSecs float64
}

type IngestClaimRow struct {
	ID                uuid.UUID
	CourseID          uuid.UUID
	Title             string
	Type              DocumentType
	Filename          *string
	MimeType          *string
	BlobKey           *string
	Sha256            *string
	VisibleToStudents bool
	UseForRag         bool
	UploadedBy        *uuid.UUID
	Version           int32
}

// Nạp tài liệu và lập chỉ mục lại (US-P8-01, SRS FEAT-docs-calendar 4.2). Mọi đường ĐỌC content_chunks lọc theo course_ids.
// Nhận việc: QUEUED, hoặc PROCESSING mà nhịp gia hạn cuối đã quá `idle` giây; tối đa MỘT tài liệu PROCESSING (còn hạn) mỗi lớp. Không trả dòng = không nhận được.
func (q *Queries) IngestClaim(ctx context.Context, arg IngestClaimParams) (IngestClaimRow, error) {
	row := q.db.QueryRow(ctx, ingestClaim, arg.ID, arg.IdleSecs)
	var i IngestClaimRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Type,
		&i.Filename,
		&i.MimeType,
		&i.BlobKey,
		&i.Sha256,
		&i.VisibleToStudents,
		&i.UseForRag,
		&i.UploadedBy,
		&i.Version,
	)
	return i, err
}

const ingestDeleteChunks = `-- name: IngestDeleteChunks :exec
delete from content_chunks where document_id = $1 and course_ids @> array[$2::uuid]
`

type IngestDeleteChunksParams struct {
	DocumentID uuid.UUID
	CourseID   uuid.UUID
}

func (q *Queries) IngestDeleteChunks(ctx context.Context, arg IngestDeleteChunksParams) error {
	_, err := q.db.Exec(ctx, ingestDeleteChunks, arg.DocumentID, arg.CourseID)
	return err
}

const ingestDocumentState = `-- name: IngestDocumentState :one
select id, course_id, status, error, sha256, use_for_rag, uploaded_by from documents where id = $1
`

type IngestDocumentStateRow struct {
	ID         uuid.UUID
	CourseID   uuid.UUID
	Status     DocumentStatus
	Error      *string
	Sha256     *string
	UseForRag  bool
	UploadedBy *uuid.UUID
}

func (q *Queries) IngestDocumentState(ctx context.Context, id uuid.UUID) (IngestDocumentStateRow, error) {
	row := q.db.QueryRow(ctx, ingestDocumentState, id)
	var i IngestDocumentStateRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Status,
		&i.Error,
		&i.Sha256,
		&i.UseForRag,
		&i.UploadedBy,
	)
	return i, err
}

const ingestInsertChunk = `-- name: IngestInsertChunk :exec
insert into content_chunks (document_id, course_ids, audience, ord, page_no, heading, text, embedding)
values ($1,
        (select array_agg(c) from (select $2::uuid as c union select dc.course_id from document_courses dc where dc.document_id = $1) s),
        $3::chunk_audience, $4, $5, normalize($6::text, NFC), normalize($7::text, NFC), $8)
`

type IngestInsertChunkParams struct {
	DocumentID uuid.UUID
	CourseID   uuid.UUID
	Audience   ChunkAudience
	Ord        int32
	PageNo     *int32
	Heading    *string
	Text       string
	Embedding  *pgvector.Vector
}

// Chữ chuẩn hoá NFC ở DB (không có thư viện chuẩn hoá trong Go). course_ids = lớp chủ + lớp được chia sẻ.
func (q *Queries) IngestInsertChunk(ctx context.Context, arg IngestInsertChunkParams) error {
	_, err := q.db.Exec(ctx, ingestInsertChunk,
		arg.DocumentID,
		arg.CourseID,
		arg.Audience,
		arg.Ord,
		arg.PageNo,
		arg.Heading,
		arg.Text,
		arg.Embedding,
	)
	return err
}

const ingestMarkFailed = `-- name: IngestMarkFailed :execrows
update documents set status = 'FAILED', error = $1
where id = $2 and status = 'PROCESSING'
`

type IngestMarkFailedParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) IngestMarkFailed(ctx context.Context, arg IngestMarkFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, ingestMarkFailed, arg.Error, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ingestMarkReady = `-- name: IngestMarkReady :execrows
update documents set status = 'READY', page_count = $1, error = null
where id = $2 and status = 'PROCESSING' and sha256 is not distinct from $3::char(64)
`

type IngestMarkReadyParams struct {
	PageCount *int32
	ID        uuid.UUID
	Sha256    *string
}

// Chỉ khi tài liệu còn PROCESSING và băm không đổi (không ghi đè tệp mới hơn).
func (q *Queries) IngestMarkReady(ctx context.Context, arg IngestMarkReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, ingestMarkReady, arg.PageCount, arg.ID, arg.Sha256)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ingestRelease = `-- name: IngestRelease :execrows
update documents set status = 'QUEUED' where id = $1 and status = 'PROCESSING'
`

// Trả tài liệu về QUEUED khi docling tạm không dùng được (chờ thử lại 5 s / 30 s / 2 phút): không còn PROCESSING nên lớp không bị chặn và UI thấy "đang chờ".
func (q *Queries) IngestRelease(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, ingestRelease, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ingestRenewLease = `-- name: IngestRenewLease :execrows
update documents set updated_at = now() where id = $1 and status = 'PROCESSING'
`

func (q *Queries) IngestRenewLease(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, ingestRenewLease, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChunkTexts = `-- name: ListChunkTexts :many
select c.id, c.ord, c.heading, c.text
from content_chunks c
where c.document_id = $1 and c.course_ids @> array[$2::uuid]
order by c.ord
`

type ListChunkTextsParams struct {
	DocumentID uuid.UUID
	CourseID   uuid.UUID
}

type ListChunkTextsRow struct {
	ID      uuid.UUID
	Ord     int32
	Heading *string
	Text    string
}

// Đọc chữ đã lưu để lập chỉ mục lại (không gọi docling). Lọc theo tài liệu VÀ lớp.
func (q *Queries) ListChunkTexts(ctx context.Context, arg ListChunkTextsParams) ([]ListChunkTextsRow, error) {
	rows, err := q.db.Query(ctx, listChunkTexts, arg.DocumentID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChunkTextsRow{}
	for rows.Next() {
		var i ListChunkTextsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ord,
			&i.Heading,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseDocumentsForReindex = `-- name: ListCourseDocumentsForReindex :many
select id from documents where course_id = $1 and status = 'READY' and use_for_rag order by id
`

func (q *Queries) ListCourseDocumentsForReindex(ctx context.Context, courseID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCourseDocumentsForReindex, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChunkEmbedding = `-- name: SetChunkEmbedding :execrows
update content_chunks set embedding = $1
where id = $2 and document_id = $3 and course_ids @> array[$4::uuid]
`

type SetChunkEmbeddingParams struct {
	Embedding  *pgvector.Vector
	ID         uuid.UUID
	DocumentID uuid.UUID
	CourseID   uuid.UUID
}

func (q *Queries) SetChunkEmbedding(ctx context.Context, arg SetChunkEmbeddingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChunkEmbedding,
		arg.Embedding,
		arg.ID,
		arg.DocumentID,
		arg.CourseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
