// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getJob = `-- name: GetJob :one
select id, kind, status, progress, result, error, owner_id, created_at, updated_at, finished_at from jobs where id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJobForOwner = `-- name: GetJobForOwner :one
select id, kind, status, progress, result, error, owner_id, created_at, updated_at, finished_at from jobs where id = $1 and owner_id = $2
`

type GetJobForOwnerParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetJobForOwner(ctx context.Context, arg GetJobForOwnerParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobForOwner, arg.ID, arg.OwnerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one

insert into jobs (kind, owner_id)
values ($1, $2)
returning id, kind, status, progress, result, error, owner_id, created_at, updated_at, finished_at
`

type InsertJobParams struct {
	Kind    string
	OwnerID uuid.UUID
}

// Việc dài (SRS 5.4). Phân trang theo con trỏ khoá (created_at, id) — không bao giờ nhảy trang theo số.
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob, arg.Kind, arg.OwnerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobsByOwner = `-- name: ListJobsByOwner :many
select id, kind, status, progress, result, error, owner_id, created_at, updated_at, finished_at from jobs
where owner_id = $1
  and (
    $2::timestamptz is null
    or (created_at, id) < ($2::timestamptz, $3::uuid)
  )
order by created_at desc, id desc
limit $4
`

type ListJobsByOwnerParams struct {
	OwnerID         uuid.UUID
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	RowLimit        int32
}

func (q *Queries) ListJobsByOwner(ctx context.Context, arg ListJobsByOwnerParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByOwner,
		arg.OwnerID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Progress,
			&i.Result,
			&i.Error,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobFailed = `-- name: MarkJobFailed :one
update jobs
set status = 'FAILED', error = $1, finished_at = now()
where id = $2 and finished_at is null
returning id, kind, status, progress, result, error, owner_id, created_at, updated_at, finished_at
`

type MarkJobFailedParams struct {
	Error []byte
	ID    uuid.UUID
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobFailed, arg.Error, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const markJobSucceeded = `-- name: MarkJobSucceeded :one
update jobs
set status = 'SUCCEEDED', progress = 100, result = $1, finished_at = now()
where id = $2 and finished_at is null
returning id, kind, status, progress, result, error, owner_id, created_at, updated_at, finished_at
`

type MarkJobSucceededParams struct {
	Result []byte
	ID     uuid.UUID
}

func (q *Queries) MarkJobSucceeded(ctx context.Context, arg MarkJobSucceededParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobSucceeded, arg.Result, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateJobProgress = `-- name: UpdateJobProgress :one
update jobs
set progress = greatest(progress, $1::smallint),
    status = 'RUNNING'
where id = $2 and status in ('QUEUED', 'RUNNING')
returning id, kind, status, progress, result, error, owner_id, created_at, updated_at, finished_at
`

type UpdateJobProgressParams struct {
	Progress int16
	ID       uuid.UUID
}

// Tiến độ chỉ tăng (greatest); việc đang chạy thì chuyển QUEUED -> RUNNING.
func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobProgress, arg.Progress, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
