// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: judge.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const judgeApprovedTests = `-- name: JudgeApprovedTests :many
select id, position, is_sample, weight, input, input_blob_key, expected, expected_blob_key
from code_testcases
where course_id = $1 and problem_id = $2 and approved
order by position
`

type JudgeApprovedTestsParams struct {
	CourseID  uuid.UUID
	ProblemID uuid.UUID
}

type JudgeApprovedTestsRow struct {
	ID              uuid.UUID
	Position        int32
	IsSample        bool
	Weight          int16
	Input           *string
	InputBlobKey    *string
	Expected        *string
	ExpectedBlobKey *string
}

func (q *Queries) JudgeApprovedTests(ctx context.Context, arg JudgeApprovedTestsParams) ([]JudgeApprovedTestsRow, error) {
	rows, err := q.db.Query(ctx, judgeApprovedTests, arg.CourseID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeApprovedTestsRow{}
	for rows.Next() {
		var i JudgeApprovedTestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.IsSample,
			&i.Weight,
			&i.Input,
			&i.InputBlobKey,
			&i.Expected,
			&i.ExpectedBlobKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const judgeClaim = `-- name: JudgeClaim :one
update code_submissions
set status = 'RUNNING', lease_until = now() + $1::int * interval '1 millisecond', attempts = attempts + 1, enqueued_at = coalesce(enqueued_at, now())
where id = $2
  and ((status = 'QUEUED' and next_attempt_at <= now()) or (status = 'RUNNING' and lease_until < now()))
returning id, course_id, exam_id, attempt_id, item_id, problem_id, kind, language, source, fail_count, lease_until
`

type JudgeClaimParams struct {
	LeaseMs int32
	ID      uuid.UUID
}

type JudgeClaimRow struct {
	ID         uuid.UUID
	CourseID   uuid.UUID
	ExamID     uuid.UUID
	AttemptID  uuid.UUID
	ItemID     uuid.UUID
	ProblemID  uuid.UUID
	Kind       SubmissionKind
	Language   string
	Source     string
	FailCount  int16
	LeaseUntil *time.Time
}

// Nhận việc bằng MỘT lệnh: dòng QUEUED đến hạn HOẶC RUNNING hết thuê. 0 dòng ⇒ nơi khác đang chấm / đã xong / chưa đến hạn thử lại.
func (q *Queries) JudgeClaim(ctx context.Context, arg JudgeClaimParams) (JudgeClaimRow, error) {
	row := q.db.QueryRow(ctx, judgeClaim, arg.LeaseMs, arg.ID)
	var i JudgeClaimRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamID,
		&i.AttemptID,
		&i.ItemID,
		&i.ProblemID,
		&i.Kind,
		&i.Language,
		&i.Source,
		&i.FailCount,
		&i.LeaseUntil,
	)
	return i, err
}

const judgeConfigError = `-- name: JudgeConfigError :one
update code_submissions
set status = 'ERROR', verdict = 'IE', compile_log = $1, lease_until = null, judged_at = now()
where id = $2 and status = 'RUNNING' and lease_until = $3::timestamptz
returning id, kind, course_id, exam_id, attempt_id
`

type JudgeConfigErrorParams struct {
	CompileLog *string
	ID         uuid.UUID
	LeaseUntil time.Time
}

type JudgeConfigErrorRow struct {
	ID        uuid.UUID
	Kind      SubmissionKind
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	AttemptID uuid.UUID
}

// Lỗi cấu hình của bài (Σ weight = 0 …): IE ngay, không thử lại, không điểm 0 cho sinh viên (attempt ở lại GRADING cho tới khi sửa + chấm lại).
func (q *Queries) JudgeConfigError(ctx context.Context, arg JudgeConfigErrorParams) (JudgeConfigErrorRow, error) {
	row := q.db.QueryRow(ctx, judgeConfigError, arg.CompileLog, arg.ID, arg.LeaseUntil)
	var i JudgeConfigErrorRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CourseID,
		&i.ExamID,
		&i.AttemptID,
	)
	return i, err
}

const judgeDueUnqueued = `-- name: JudgeDueUnqueued :many
select id, kind from code_submissions
where status = 'QUEUED' and enqueued_at is null and next_attempt_at <= now()
order by next_attempt_at, id
limit $1
`

type JudgeDueUnqueuedRow struct {
	ID   uuid.UUID
	Kind SubmissionKind
}

// Tick: dòng QUEUED đến hạn mà chưa XADD (hoặc bị đặt lại để đưa lại).
func (q *Queries) JudgeDueUnqueued(ctx context.Context, maxRows int32) ([]JudgeDueUnqueuedRow, error) {
	rows, err := q.db.Query(ctx, judgeDueUnqueued, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeDueUnqueuedRow{}
	for rows.Next() {
		var i JudgeDueUnqueuedRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const judgeFail = `-- name: JudgeFail :one
update code_submissions
set fail_count = fail_count + 1,
    status = case when fail_count + 1 >= 4 then 'ERROR'::submission_status else 'QUEUED'::submission_status end,
    verdict = case when fail_count + 1 >= 4 then 'IE'::judge_verdict end,
    lease_until = null, enqueued_at = null, next_attempt_at = now() + $1::int * interval '1 millisecond', judged_at = case when fail_count + 1 >= 4 then now() end
where id = $2 and status = 'RUNNING' and lease_until = $3::timestamptz
returning status, fail_count, kind, course_id, exam_id, attempt_id
`

type JudgeFailParams struct {
	BackoffMs  int32
	ID         uuid.UUID
	LeaseUntil time.Time
}

type JudgeFailRow struct {
	Status    SubmissionStatus
	FailCount int16
	Kind      SubmissionKind
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	AttemptID uuid.UUID
}

// Lỗi THẬT (sandbox lỗi / IE): fail_count + 1; < 4 ⇒ QUEUED với next_attempt_at (1 s / 5 s / 30 s); = 4 ⇒ ERROR + IE.
func (q *Queries) JudgeFail(ctx context.Context, arg JudgeFailParams) (JudgeFailRow, error) {
	row := q.db.QueryRow(ctx, judgeFail, arg.BackoffMs, arg.ID, arg.LeaseUntil)
	var i JudgeFailRow
	err := row.Scan(
		&i.Status,
		&i.FailCount,
		&i.Kind,
		&i.CourseID,
		&i.ExamID,
		&i.AttemptID,
	)
	return i, err
}

const judgeFinish = `-- name: JudgeFinish :one
update code_submissions
set status = 'DONE', verdict = $1::judge_verdict, tests_version = $2, compile_ok = $3,
    compile_log = $4, results = $5, passed_weight = $6, total_weight = $7,
    time_ms_max = $8, memory_kb_max = $9, lease_until = null, judged_at = now()
where id = $10 and status = 'RUNNING' and lease_until = $11::timestamptz
returning id, course_id, exam_id, attempt_id, item_id, kind
`

type JudgeFinishParams struct {
	Verdict      JudgeVerdict
	TestsVersion *int32
	CompileOk    *bool
	CompileLog   *string
	Results      json.RawMessage
	PassedWeight *int32
	TotalWeight  *int32
	TimeMsMax    *int32
	MemoryKbMax  *int32
	ID           uuid.UUID
	LeaseUntil   time.Time
}

type JudgeFinishRow struct {
	ID        uuid.UUID
	CourseID  uuid.UUID
	ExamID    uuid.UUID
	AttemptID uuid.UUID
	ItemID    uuid.UUID
	Kind      SubmissionKind
}

// Ghi kết quả, rào chắn bằng thuê của mình: thuê đã bị nhận lại ⇒ 0 dòng ⇒ bỏ kết quả.
func (q *Queries) JudgeFinish(ctx context.Context, arg JudgeFinishParams) (JudgeFinishRow, error) {
	row := q.db.QueryRow(ctx, judgeFinish,
		arg.Verdict,
		arg.TestsVersion,
		arg.CompileOk,
		arg.CompileLog,
		arg.Results,
		arg.PassedWeight,
		arg.TotalWeight,
		arg.TimeMsMax,
		arg.MemoryKbMax,
		arg.ID,
		arg.LeaseUntil,
	)
	var i JudgeFinishRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamID,
		&i.AttemptID,
		&i.ItemID,
		&i.Kind,
	)
	return i, err
}

const judgeMarkEnqueued = `-- name: JudgeMarkEnqueued :execrows
update code_submissions set enqueued_at = now() where id = $1 and status = 'QUEUED'
`

func (q *Queries) JudgeMarkEnqueued(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, judgeMarkEnqueued, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const judgeProblem = `-- name: JudgeProblem :one
select time_limit_ms, memory_limit_mb, output_limit_kb, checker, float_eps, tests_version
from code_problems where course_id = $1 and question_id = $2
`

type JudgeProblemParams struct {
	CourseID   uuid.UUID
	QuestionID uuid.UUID
}

type JudgeProblemRow struct {
	TimeLimitMs   int32
	MemoryLimitMb int32
	OutputLimitKb int32
	Checker       CheckerKind
	FloatEps      decimal.NullDecimal
	TestsVersion  int32
}

func (q *Queries) JudgeProblem(ctx context.Context, arg JudgeProblemParams) (JudgeProblemRow, error) {
	row := q.db.QueryRow(ctx, judgeProblem, arg.CourseID, arg.QuestionID)
	var i JudgeProblemRow
	err := row.Scan(
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.OutputLimitKb,
		&i.Checker,
		&i.FloatEps,
		&i.TestsVersion,
	)
	return i, err
}

const judgeRenew = `-- name: JudgeRenew :one
update code_submissions
set lease_until = now() + $1::int * interval '1 millisecond'
where id = $2 and status = 'RUNNING' and lease_until = $3::timestamptz
returning lease_until
`

type JudgeRenewParams struct {
	LeaseMs  int32
	ID       uuid.UUID
	OldLease time.Time
}

func (q *Queries) JudgeRenew(ctx context.Context, arg JudgeRenewParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, judgeRenew, arg.LeaseMs, arg.ID, arg.OldLease)
	var lease_until *time.Time
	err := row.Scan(&lease_until)
	return lease_until, err
}

const judgeRequeueExpired = `-- name: JudgeRequeueExpired :many
update code_submissions
set status = 'QUEUED', lease_until = null, enqueued_at = null
where status = 'RUNNING' and lease_until < now()
returning id, kind
`

type JudgeRequeueExpiredRow struct {
	ID   uuid.UUID
	Kind SubmissionKind
}

// Tick: RUNNING hết thuê (worker chết / treo) ⇒ QUEUED, KHÔNG tăng fail_count (chưa chắc lỗi của bản nộp); lần sau tick XADD lại.
func (q *Queries) JudgeRequeueExpired(ctx context.Context) ([]JudgeRequeueExpiredRow, error) {
	rows, err := q.db.Query(ctx, judgeRequeueExpired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeRequeueExpiredRow{}
	for rows.Next() {
		var i JudgeRequeueExpiredRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const judgeResetStaleSignal = `-- name: JudgeResetStaleSignal :execrows
update code_submissions set enqueued_at = null
where status = 'QUEUED' and enqueued_at is not null and enqueued_at < now() - $1::int * interval '1 millisecond'
`

// Tick: QUEUED đã có enqueued_at quá lâu mà chưa ai nhận (Stream mất tin) ⇒ đưa lại.
func (q *Queries) JudgeResetStaleSignal(ctx context.Context, idleMs int32) (int64, error) {
	result, err := q.db.Exec(ctx, judgeResetStaleSignal, idleMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const judgeSupersedeQueued = `-- name: JudgeSupersedeQueued :one

update code_submissions c
set status = 'SUPERSEDED', enqueued_at = null
where c.id = $1 and c.status = 'QUEUED' and c.kind = 'SUBMIT'
  and exists (
    select 1 from code_submissions n
    where n.attempt_id = c.attempt_id and n.item_id = c.item_id and n.kind = 'SUBMIT' and n.status <> 'SUPERSEDED'
      and (n.created_at, n.id) > (c.created_at, c.id)
  )
returning c.id
`

// Hàng đợi chấm code (SRS FEAT-weekly-exam 4.5.7, góp ý #3). Trạng thái nhận việc / thuê / thử lại nằm Ở ĐÂY; Redis Stream chỉ là tín hiệu đánh thức.
// Bản SUBMIT đang xếp hàng mà đã có SUBMIT mới hơn của cùng (lượt, mục) → SUPERSEDED, không chạy sandbox. `Chạy thử` (RUN) không bao giờ bị thay.
func (q *Queries) JudgeSupersedeQueued(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, judgeSupersedeQueued, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}
