// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const libCountDownload = `-- name: LibCountDownload :exec
update documents set download_count = download_count + 1 where id = $1
`

func (q *Queries) LibCountDownload(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, libCountDownload, id)
	return err
}

const libGet = `-- name: LibGet :one
select d.id, d.title, d.type, d.filename, d.mime_type, d.size_bytes, d.category, d.week_no, d.updated_at, d.page_count, d.blob_key,
       (d.use_for_rag and exists (select 1 from content_chunks c where c.document_id = d.id and c.course_ids @> array[$1::uuid] and c.embedding is not null))::bool as can_ask_ai
from documents d
where d.id = $2
  and (d.course_id = $1 or exists (select 1 from document_courses dc where dc.document_id = d.id and dc.course_id = $1))
  and d.status = 'READY' and d.visible_to_students and d.type <> 'ANSWER_KEY'
`

type LibGetParams struct {
	CourseID uuid.UUID
	ID       uuid.UUID
}

type LibGetRow struct {
	ID        uuid.UUID
	Title     string
	Type      DocumentType
	Filename  *string
	MimeType  *string
	SizeBytes *int64
	Category  *string
	WeekNo    *int16
	UpdatedAt time.Time
	PageCount *int32
	BlobKey   *string
	CanAskAi  bool
}

func (q *Queries) LibGet(ctx context.Context, arg LibGetParams) (LibGetRow, error) {
	row := q.db.QueryRow(ctx, libGet, arg.CourseID, arg.ID)
	var i LibGetRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Category,
		&i.WeekNo,
		&i.UpdatedAt,
		&i.PageCount,
		&i.BlobKey,
		&i.CanAskAi,
	)
	return i, err
}

const libList = `-- name: LibList :many

select d.id, d.title, d.type, d.filename, d.mime_type, d.category, d.week_no, d.updated_at, d.page_count,
       (d.use_for_rag and exists (select 1 from content_chunks c where c.document_id = d.id and c.course_ids @> array[$1::uuid] and c.embedding is not null))::bool as can_ask_ai,
       case when $2::text is null then '' else coalesce((
         select left(regexp_replace(c.text, '\s+', ' ', 'g'), 160) from content_chunks c
         where c.document_id = d.id and c.course_ids @> array[$1::uuid] and c.tsv @@ vn_bigram_query($2::text) order by c.ord limit 1), '') end::text as snippet
from documents d
where (d.course_id = $1 or exists (select 1 from document_courses dc where dc.document_id = d.id and dc.course_id = $1))
  and d.status = 'READY' and d.visible_to_students and d.type <> 'ANSWER_KEY'
  and ($3::text is null or d.type::text = $3::text)
  and ($4::int is null or d.week_no = $4::int)
  and ($5::text is null or d.category = $5::text)
  and ($2::text is null
       or vn_fold(d.title) like '%' || vn_fold($2::text) || '%' escape '\'
       or vn_fold(coalesce(d.filename, '')) like '%' || vn_fold($2::text) || '%' escape '\'
       or vn_fold(coalesce(d.category, '')) like '%' || vn_fold($2::text) || '%' escape '\'
       or exists (select 1 from content_chunks c where c.document_id = d.id and c.course_ids @> array[$1::uuid] and c.tsv @@ vn_bigram_query($2::text)))
  and ($6::timestamptz is null or (d.updated_at, d.id) < ($6::timestamptz, $7::uuid))
order by d.updated_at desc, d.id desc
limit $8
`

type LibListParams struct {
	CourseID  uuid.UUID
	Q         *string
	Type      *string
	WeekNo    *int32
	Category  *string
	CursorAt  *time.Time
	CursorID  *uuid.UUID
	PageLimit int32
}

type LibListRow struct {
	ID        uuid.UUID
	Title     string
	Type      DocumentType
	Filename  *string
	MimeType  *string
	Category  *string
	WeekNo    *int16
	UpdatedAt time.Time
	PageCount *int32
	CanAskAi  bool
	Snippet   string
}

// US-P8-02 — thư viện của sinh viên: READY + visible_to_students + không ANSWER_KEY, của lớp hoặc được chia sẻ vào lớp.
// `q` (≥ 2 ký tự — dưới đó người gọi truyền NULL): khớp tên / tệp / chủ đề (vn_fold, LIKE) HOẶC từ khoá trên đoạn (tsv). snippet = ts_headline của đoạn khớp đầu tiên.
func (q *Queries) LibList(ctx context.Context, arg LibListParams) ([]LibListRow, error) {
	rows, err := q.db.Query(ctx, libList,
		arg.CourseID,
		arg.Q,
		arg.Type,
		arg.WeekNo,
		arg.Category,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibListRow{}
	for rows.Next() {
		var i LibListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Filename,
			&i.MimeType,
			&i.Category,
			&i.WeekNo,
			&i.UpdatedAt,
			&i.PageCount,
			&i.CanAskAi,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const libSearchTool = `-- name: LibSearchTool :many
select d.id, d.title, d.type, d.week_no,
       (select c.page_no from content_chunks c where c.document_id = d.id and c.course_ids @> array[$1::uuid] and c.tsv @@ vn_bigram_query($2::text) order by c.ord limit 1)::int as page_no,
       coalesce((select left(regexp_replace(c.text, '\s+', ' ', 'g'), 160) from content_chunks c where c.document_id = d.id and c.course_ids @> array[$1::uuid] and c.tsv @@ vn_bigram_query($2::text) order by c.ord limit 1), '')::text as snippet
from documents d
where (d.course_id = $1 or exists (select 1 from document_courses dc where dc.document_id = d.id and dc.course_id = $1))
  and d.status = 'READY' and d.visible_to_students and d.type <> 'ANSWER_KEY'
  and (vn_fold(d.title) like '%' || vn_fold($2::text) || '%' escape '\'
       or exists (select 1 from content_chunks c where c.document_id = d.id and c.course_ids @> array[$1::uuid] and c.tsv @@ vn_bigram_query($2::text)))
order by d.updated_at desc, d.id desc
limit 5
`

type LibSearchToolParams struct {
	CourseID uuid.UUID
	Q        string
}

type LibSearchToolRow struct {
	ID      uuid.UUID
	Title   string
	Type    DocumentType
	WeekNo  *int16
	PageNo  int32
	Snippet string
}

// Cho tool search_library: tối đa 5 tài liệu cùng bộ lọc của danh sách, kèm đoạn khớp đầu tiên (trang).
func (q *Queries) LibSearchTool(ctx context.Context, arg LibSearchToolParams) ([]LibSearchToolRow, error) {
	rows, err := q.db.Query(ctx, libSearchTool, arg.CourseID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibSearchToolRow{}
	for rows.Next() {
		var i LibSearchToolRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.WeekNo,
			&i.PageNo,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
