// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countLLMModelsByProvider = `-- name: CountLLMModelsByProvider :one
select count(*) from llm_models where provider_id = $1
`

func (q *Queries) CountLLMModelsByProvider(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLLMModelsByProvider, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLLMProviders = `-- name: CountLLMProviders :one
select count(*) from llm_providers
`

func (q *Queries) CountLLMProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLLMProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLLMModelsNotIn = `-- name: DeleteLLMModelsNotIn :many
delete from llm_models where provider_id = $1 and not (model = any($2::text[]))
returning id, model
`

type DeleteLLMModelsNotInParams struct {
	ProviderID uuid.UUID
	Keep       []string
}

type DeleteLLMModelsNotInRow struct {
	ID    uuid.UUID
	Model string
}

func (q *Queries) DeleteLLMModelsNotIn(ctx context.Context, arg DeleteLLMModelsNotInParams) ([]DeleteLLMModelsNotInRow, error) {
	rows, err := q.db.Query(ctx, deleteLLMModelsNotIn, arg.ProviderID, arg.Keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteLLMModelsNotInRow{}
	for rows.Next() {
		var i DeleteLLMModelsNotInRow
		if err := rows.Scan(&i.ID, &i.Model); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLLMProvider = `-- name: DeleteLLMProvider :execrows
delete from llm_providers where id = $1
`

func (q *Queries) DeleteLLMProvider(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLLMProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLLMRoutesByTask = `-- name: DeleteLLMRoutesByTask :exec
delete from llm_task_routes where task = $1
`

func (q *Queries) DeleteLLMRoutesByTask(ctx context.Context, task string) error {
	_, err := q.db.Exec(ctx, deleteLLMRoutesByTask, task)
	return err
}

const getLLMBudget = `-- name: GetLLMBudget :one
select id, scope, course_id, daily_limit, monthly_limit, version, created_at, updated_at from llm_budgets
 where scope = $1 and course_id is not distinct from $2
`

type GetLLMBudgetParams struct {
	Scope    string
	CourseID *uuid.UUID
}

func (q *Queries) GetLLMBudget(ctx context.Context, arg GetLLMBudgetParams) (LlmBudget, error) {
	row := q.db.QueryRow(ctx, getLLMBudget, arg.Scope, arg.CourseID)
	var i LlmBudget
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.CourseID,
		&i.DailyLimit,
		&i.MonthlyLimit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLLMProvider = `-- name: GetLLMProvider :one
select id, type, name, base_url, api_key_enc, enabled, rpm_limit, tpm_limit, last_test_ok, last_test_at, last_test_error, version, created_at, updated_at from llm_providers where id = $1
`

func (q *Queries) GetLLMProvider(ctx context.Context, id uuid.UUID) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getLLMProvider, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.LastTestOk,
		&i.LastTestAt,
		&i.LastTestError,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLLMBudget = `-- name: InsertLLMBudget :one
insert into llm_budgets (scope, course_id, daily_limit, monthly_limit)
values ($1, $2, $3, $4)
returning id, scope, course_id, daily_limit, monthly_limit, version, created_at, updated_at
`

type InsertLLMBudgetParams struct {
	Scope        string
	CourseID     *uuid.UUID
	DailyLimit   decimal.NullDecimal
	MonthlyLimit decimal.NullDecimal
}

func (q *Queries) InsertLLMBudget(ctx context.Context, arg InsertLLMBudgetParams) (LlmBudget, error) {
	row := q.db.QueryRow(ctx, insertLLMBudget,
		arg.Scope,
		arg.CourseID,
		arg.DailyLimit,
		arg.MonthlyLimit,
	)
	var i LlmBudget
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.CourseID,
		&i.DailyLimit,
		&i.MonthlyLimit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLLMProvider = `-- name: InsertLLMProvider :one
insert into llm_providers (id, type, name, base_url, api_key_enc, enabled, rpm_limit, tpm_limit, last_test_ok, last_test_at, last_test_error)
values (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
returning id, type, name, base_url, api_key_enc, enabled, rpm_limit, tpm_limit, last_test_ok, last_test_at, last_test_error, version, created_at, updated_at
`

type InsertLLMProviderParams struct {
	ID            uuid.UUID
	Type          string
	Name          string
	BaseUrl       *string
	ApiKeyEnc     []byte
	Enabled       bool
	RpmLimit      *int32
	TpmLimit      *int32
	LastTestOk    *bool
	LastTestAt    *time.Time
	LastTestError *string
}

func (q *Queries) InsertLLMProvider(ctx context.Context, arg InsertLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, insertLLMProvider,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.LastTestOk,
		arg.LastTestAt,
		arg.LastTestError,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.LastTestOk,
		&i.LastTestAt,
		&i.LastTestError,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLLMRoute = `-- name: InsertLLMRoute :one
insert into llm_task_routes (task, model_id, fallback_order, params, version)
values ($1, $2, $3, $4, $5)
returning id, task, model_id, fallback_order, params, version, created_at, updated_at
`

type InsertLLMRouteParams struct {
	Task          string
	ModelID       uuid.UUID
	FallbackOrder int32
	Params        json.RawMessage
	Version       int32
}

func (q *Queries) InsertLLMRoute(ctx context.Context, arg InsertLLMRouteParams) (LlmTaskRoute, error) {
	row := q.db.QueryRow(ctx, insertLLMRoute,
		arg.Task,
		arg.ModelID,
		arg.FallbackOrder,
		arg.Params,
		arg.Version,
	)
	var i LlmTaskRoute
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.ModelID,
		&i.FallbackOrder,
		&i.Params,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lLMTasksUsingModels = `-- name: LLMTasksUsingModels :many
select distinct task from llm_task_routes where model_id = any($1::uuid[]) order by task
`

func (q *Queries) LLMTasksUsingModels(ctx context.Context, ids []uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, lLMTasksUsingModels, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var task string
		if err := rows.Scan(&task); err != nil {
			return nil, err
		}
		items = append(items, task)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lLMTasksUsingProvider = `-- name: LLMTasksUsingProvider :many
select distinct r.task
  from llm_task_routes r join llm_models m on m.id = r.model_id
 where m.provider_id = $1
 order by r.task
`

// Tác vụ đang dùng nhà cung cấp / mô hình (chặn xoá).
func (q *Queries) LLMTasksUsingProvider(ctx context.Context, providerID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, lLMTasksUsingProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var task string
		if err := rows.Scan(&task); err != nil {
			return nil, err
		}
		items = append(items, task)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMModels = `-- name: ListLLMModels :many
select id, provider_id, model, kind, dims, price_in, price_out, enabled, created_at, updated_at from llm_models order by provider_id, created_at, id
`

func (q *Queries) ListLLMModels(ctx context.Context) ([]LlmModel, error) {
	rows, err := q.db.Query(ctx, listLLMModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmModel{}
	for rows.Next() {
		var i LlmModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.Kind,
			&i.Dims,
			&i.PriceIn,
			&i.PriceOut,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMModelsByIDs = `-- name: ListLLMModelsByIDs :many
select id, provider_id, model, kind, dims, price_in, price_out, enabled, created_at, updated_at from llm_models where id = any($1::uuid[])
`

func (q *Queries) ListLLMModelsByIDs(ctx context.Context, ids []uuid.UUID) ([]LlmModel, error) {
	rows, err := q.db.Query(ctx, listLLMModelsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmModel{}
	for rows.Next() {
		var i LlmModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.Kind,
			&i.Dims,
			&i.PriceIn,
			&i.PriceOut,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMModelsByProvider = `-- name: ListLLMModelsByProvider :many
select id, provider_id, model, kind, dims, price_in, price_out, enabled, created_at, updated_at from llm_models where provider_id = $1 order by created_at, id
`

func (q *Queries) ListLLMModelsByProvider(ctx context.Context, providerID uuid.UUID) ([]LlmModel, error) {
	rows, err := q.db.Query(ctx, listLLMModelsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmModel{}
	for rows.Next() {
		var i LlmModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.Kind,
			&i.Dims,
			&i.PriceIn,
			&i.PriceOut,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMProviders = `-- name: ListLLMProviders :many

select id, type, name, base_url, api_key_enc, enabled, rpm_limit, tpm_limit, last_test_ok, last_test_at, last_test_error, version, created_at, updated_at from llm_providers order by created_at, id
`

// Cấu hình cổng LLM (FEAT-llm-gateway 5.2). Khoá API chỉ đi vào/ra dưới dạng bytea đã mã hoá.
func (q *Queries) ListLLMProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listLLMProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmProvider{}
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.Enabled,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.LastTestOk,
			&i.LastTestAt,
			&i.LastTestError,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMRoutes = `-- name: ListLLMRoutes :many
select r.id, r.task, r.model_id, r.fallback_order, r.params, r.version,
       m.provider_id, m.model, m.kind, m.dims, m.enabled as model_enabled, p.name as provider_name, p.enabled as provider_enabled
  from llm_task_routes r
  join llm_models m on m.id = r.model_id
  join llm_providers p on p.id = m.provider_id
 order by r.task, r.fallback_order
`

type ListLLMRoutesRow struct {
	ID              uuid.UUID
	Task            string
	ModelID         uuid.UUID
	FallbackOrder   int32
	Params          json.RawMessage
	Version         int32
	ProviderID      uuid.UUID
	Model           string
	Kind            string
	Dims            *int32
	ModelEnabled    bool
	ProviderName    string
	ProviderEnabled bool
}

func (q *Queries) ListLLMRoutes(ctx context.Context) ([]ListLLMRoutesRow, error) {
	rows, err := q.db.Query(ctx, listLLMRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLLMRoutesRow{}
	for rows.Next() {
		var i ListLLMRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.ModelID,
			&i.FallbackOrder,
			&i.Params,
			&i.Version,
			&i.ProviderID,
			&i.Model,
			&i.Kind,
			&i.Dims,
			&i.ModelEnabled,
			&i.ProviderName,
			&i.ProviderEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMRoutesByTask = `-- name: ListLLMRoutesByTask :many
select id, task, model_id, fallback_order, params, version, created_at, updated_at from llm_task_routes where task = $1 order by fallback_order
`

func (q *Queries) ListLLMRoutesByTask(ctx context.Context, task string) ([]LlmTaskRoute, error) {
	rows, err := q.db.Query(ctx, listLLMRoutesByTask, task)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmTaskRoute{}
	for rows.Next() {
		var i LlmTaskRoute
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.ModelID,
			&i.FallbackOrder,
			&i.Params,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLLMTask = `-- name: LockLLMTask :exec
select pg_advisory_xact_lock(hashtextextended('llm_route:' || $1::text, 0))
`

// Khoá tư vấn theo tác vụ: hai Admin tạo tuyến lần đầu cùng lúc không đua nhau.
func (q *Queries) LockLLMTask(ctx context.Context, task string) error {
	_, err := q.db.Exec(ctx, lockLLMTask, task)
	return err
}

const updateLLMBudget = `-- name: UpdateLLMBudget :one
update llm_budgets
   set daily_limit = $1, monthly_limit = $2, version = version + 1
 where id = $3 and version = $4
returning id, scope, course_id, daily_limit, monthly_limit, version, created_at, updated_at
`

type UpdateLLMBudgetParams struct {
	DailyLimit   decimal.NullDecimal
	MonthlyLimit decimal.NullDecimal
	ID           uuid.UUID
	Version      int32
}

func (q *Queries) UpdateLLMBudget(ctx context.Context, arg UpdateLLMBudgetParams) (LlmBudget, error) {
	row := q.db.QueryRow(ctx, updateLLMBudget,
		arg.DailyLimit,
		arg.MonthlyLimit,
		arg.ID,
		arg.Version,
	)
	var i LlmBudget
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.CourseID,
		&i.DailyLimit,
		&i.MonthlyLimit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLLMProvider = `-- name: UpdateLLMProvider :one
update llm_providers
   set type = $1,
       name = $2,
       base_url = $3,
       api_key_enc = coalesce($4, api_key_enc),
       enabled = $5,
       rpm_limit = $6,
       tpm_limit = $7,
       last_test_ok = case when $8::boolean then null else last_test_ok end,
       last_test_at = case when $8::boolean then null else last_test_at end,
       last_test_error = case when $8::boolean then null else last_test_error end,
       version = version + 1
 where id = $9 and version = $10
returning id, type, name, base_url, api_key_enc, enabled, rpm_limit, tpm_limit, last_test_ok, last_test_at, last_test_error, version, created_at, updated_at
`

type UpdateLLMProviderParams struct {
	Type      string
	Name      string
	BaseUrl   *string
	ApiKeyEnc []byte
	Enabled   bool
	RpmLimit  *int32
	TpmLimit  *int32
	ResetTest bool
	ID        uuid.UUID
	Version   int32
}

// Sửa có khoá lạc quan: 0 dòng = sai version hoặc không tồn tại. `api_key_enc` NULL = giữ khoá cũ.
func (q *Queries) UpdateLLMProvider(ctx context.Context, arg UpdateLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateLLMProvider,
		arg.Type,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.Enabled,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.ResetTest,
		arg.ID,
		arg.Version,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.LastTestOk,
		&i.LastTestAt,
		&i.LastTestError,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLLMProviderTest = `-- name: UpdateLLMProviderTest :one
update llm_providers
   set last_test_ok = $1, last_test_at = $2, last_test_error = $3
 where id = $4
returning id, type, name, base_url, api_key_enc, enabled, rpm_limit, tpm_limit, last_test_ok, last_test_at, last_test_error, version, created_at, updated_at
`

type UpdateLLMProviderTestParams struct {
	LastTestOk    *bool
	LastTestAt    *time.Time
	LastTestError *string
	ID            uuid.UUID
}

// Kết quả Test không đổi version (không phải sửa cấu hình).
func (q *Queries) UpdateLLMProviderTest(ctx context.Context, arg UpdateLLMProviderTestParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateLLMProviderTest,
		arg.LastTestOk,
		arg.LastTestAt,
		arg.LastTestError,
		arg.ID,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.Enabled,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.LastTestOk,
		&i.LastTestAt,
		&i.LastTestError,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLLMModel = `-- name: UpsertLLMModel :one
insert into llm_models (provider_id, model, kind, dims, price_in, price_out, enabled)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (provider_id, model) do update
   set kind = excluded.kind, dims = excluded.dims, price_in = excluded.price_in, price_out = excluded.price_out, enabled = excluded.enabled
returning id, provider_id, model, kind, dims, price_in, price_out, enabled, created_at, updated_at
`

type UpsertLLMModelParams struct {
	ProviderID uuid.UUID
	Model      string
	Kind       string
	Dims       *int32
	PriceIn    decimal.Decimal
	PriceOut   decimal.Decimal
	Enabled    bool
}

func (q *Queries) UpsertLLMModel(ctx context.Context, arg UpsertLLMModelParams) (LlmModel, error) {
	row := q.db.QueryRow(ctx, upsertLLMModel,
		arg.ProviderID,
		arg.Model,
		arg.Kind,
		arg.Dims,
		arg.PriceIn,
		arg.PriceOut,
		arg.Enabled,
	)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Model,
		&i.Kind,
		&i.Dims,
		&i.PriceIn,
		&i.PriceOut,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
