// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertMailOutbox = `-- name: InsertMailOutbox :one

insert into mail_outbox (to_addr, template, payload, dedupe_key)
values ($1, $2, $3, $4)
on conflict (dedupe_key) where dedupe_key is not null do nothing
returning id, to_addr, template, payload, status, attempts, last_error, dedupe_key, sent_at, created_at, updated_at
`

type InsertMailOutboxParams struct {
	ToAddr    string
	Template  string
	Payload   json.RawMessage
	DedupeKey *string
}

// Hàng đợi thư (SRS FEAT-account-security 5.5, 5.6). Không có đường HTTP đọc bảng này.
func (q *Queries) InsertMailOutbox(ctx context.Context, arg InsertMailOutboxParams) (MailOutbox, error) {
	row := q.db.QueryRow(ctx, insertMailOutbox,
		arg.ToAddr,
		arg.Template,
		arg.Payload,
		arg.DedupeKey,
	)
	var i MailOutbox
	err := row.Scan(
		&i.ID,
		&i.ToAddr,
		&i.Template,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DedupeKey,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockMailOutbox = `-- name: LockMailOutbox :one
select id, to_addr, template, payload, status, attempts, last_error, dedupe_key, sent_at, created_at, updated_at from mail_outbox where id = $1 for update
`

func (q *Queries) LockMailOutbox(ctx context.Context, id uuid.UUID) (MailOutbox, error) {
	row := q.db.QueryRow(ctx, lockMailOutbox, id)
	var i MailOutbox
	err := row.Scan(
		&i.ID,
		&i.ToAddr,
		&i.Template,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DedupeKey,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMailDead = `-- name: MarkMailDead :exec
update mail_outbox
set status = 'DEAD',
    attempts = least(attempts + 1, 4),
    last_error = left($1::text, 1000)
where id = $2 and status = 'QUEUED'
`

type MarkMailDeadParams struct {
	LastError string
	ID        uuid.UUID
}

func (q *Queries) MarkMailDead(ctx context.Context, arg MarkMailDeadParams) error {
	_, err := q.db.Exec(ctx, markMailDead, arg.LastError, arg.ID)
	return err
}

const markMailSent = `-- name: MarkMailSent :exec
update mail_outbox
set status = 'SENT', sent_at = now(), last_error = null
where id = $1 and status = 'QUEUED'
`

func (q *Queries) MarkMailSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMailSent, id)
	return err
}

const recordMailFailure = `-- name: RecordMailFailure :exec
update mail_outbox
set attempts = least(attempts + 1, 4),
    last_error = left($1::text, 1000)
where id = $2 and status = 'QUEUED'
`

type RecordMailFailureParams struct {
	LastError string
	ID        uuid.UUID
}

func (q *Queries) RecordMailFailure(ctx context.Context, arg RecordMailFailureParams) error {
	_, err := q.db.Exec(ctx, recordMailFailure, arg.LastError, arg.ID)
	return err
}
