// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type JobStatus string

const (
	JobStatusQUEUED    JobStatus = "QUEUED"
	JobStatusRUNNING   JobStatus = "RUNNING"
	JobStatusSUCCEEDED JobStatus = "SUCCEEDED"
	JobStatusFAILED    JobStatus = "FAILED"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type UserRole string

const (
	UserRoleADMIN   UserRole = "ADMIN"
	UserRoleTEACHER UserRole = "TEACHER"
	UserRoleTA      UserRole = "TA"
	UserRoleSTUDENT UserRole = "STUDENT"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusPENDINGVERIFICATION UserStatus = "PENDING_VERIFICATION"
	UserStatusINVITED             UserStatus = "INVITED"
	UserStatusACTIVE              UserStatus = "ACTIVE"
	UserStatusDISABLED            UserStatus = "DISABLED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID        uuid.UUID
	CourseID  *uuid.UUID
	ActorID   *uuid.UUID
	Entity    string
	EntityID  string
	Action    string
	Before    json.RawMessage
	After     json.RawMessage
	TraceID   *string
	CreatedAt time.Time
}

type IdempotencyKey struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Endpoint    string
	Key         string
	RequestHash string
	StatusCode  int16
	Response    json.RawMessage
	CreatedAt   time.Time
}

type Job struct {
	ID         uuid.UUID
	Kind       string
	Status     JobStatus
	Progress   int16
	Result     json.RawMessage
	Error      json.RawMessage
	OwnerID    uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	FinishedAt *time.Time
}

type Outbox struct {
	ID            uuid.UUID
	Topic         string
	Payload       json.RawMessage
	CreatedAt     time.Time
	NextAttemptAt time.Time
	EnqueuedAt    *time.Time
	DispatchedAt  *time.Time
	Attempts      int32
	LastError     *string
	DeadAt        *time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID                  uuid.UUID
	Email               string
	PasswordHash        *string
	FullName            string
	Role                UserRole
	StudentCode         *string
	EmailVerifiedAt     *time.Time
	FailedLogins        int32
	LockedUntil         *time.Time
	Status              UserStatus
	IcsToken            *string
	TrackingNoticeAckAt *time.Time
	LastLoginAt         *time.Time
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
