// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getOutbox = `-- name: GetOutbox :one
select id, topic, payload, created_at, next_attempt_at, enqueued_at, dispatched_at, attempts, last_error, dead_at, updated_at from outbox where id = $1
`

func (q *Queries) GetOutbox(ctx context.Context, id uuid.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, getOutbox, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.CreatedAt,
		&i.NextAttemptAt,
		&i.EnqueuedAt,
		&i.DispatchedAt,
		&i.Attempts,
		&i.LastError,
		&i.DeadAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :one

insert into outbox (topic, payload)
values ($1, $2)
returning id, topic, payload, created_at, next_attempt_at, enqueued_at, dispatched_at, attempts, last_error, dead_at, updated_at
`

type InsertOutboxParams struct {
	Topic   string
	Payload []byte
}

// Outbox (SRS 3.2, 5.3): relay lấy dòng tới hạn bằng FOR UPDATE SKIP LOCKED, consumer đánh dấu
// dispatched / failed (backoff) / dead. `attempts` tối đa 4 (ràng buộc outbox_attempts_chk).
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutbox, arg.Topic, arg.Payload)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.CreatedAt,
		&i.NextAttemptAt,
		&i.EnqueuedAt,
		&i.DispatchedAt,
		&i.Attempts,
		&i.LastError,
		&i.DeadAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboxDead = `-- name: MarkOutboxDead :execrows
update outbox
set dead_at = now(),
    last_error = left($1::text, 1000),
    enqueued_at = null
where id = $2 and dispatched_at is null and dead_at is null
`

type MarkOutboxDeadParams struct {
	LastError string
	ID        uuid.UUID
}

func (q *Queries) MarkOutboxDead(ctx context.Context, arg MarkOutboxDeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxDead, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxDispatched = `-- name: MarkOutboxDispatched :execrows
update outbox
set dispatched_at = now(), enqueued_at = null
where id = $1 and dispatched_at is null and dead_at is null
`

func (q *Queries) MarkOutboxDispatched(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxDispatched, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxEnqueued = `-- name: MarkOutboxEnqueued :execrows
update outbox
set enqueued_at = now()
where id = $1 and enqueued_at is null and dispatched_at is null and dead_at is null
`

func (q *Queries) MarkOutboxEnqueued(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEnqueued, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :one
update outbox
set attempts = attempts + 1,
    last_error = left($1::text, 1000),
    enqueued_at = null,
    next_attempt_at = now() + ($2::bigint * interval '1 millisecond')
where id = $3 and dispatched_at is null and dead_at is null
returning attempts
`

type MarkOutboxFailedParams struct {
	LastError string
	BackoffMs int64
	ID        uuid.UUID
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (int32, error) {
	row := q.db.QueryRow(ctx, markOutboxFailed, arg.LastError, arg.BackoffMs, arg.ID)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const requeueStaleOutbox = `-- name: RequeueStaleOutbox :many
update outbox
set enqueued_at = null
where enqueued_at is not null
  and dispatched_at is null
  and dead_at is null
  and enqueued_at < now() - ($1::bigint * interval '1 millisecond')
returning id
`

func (q *Queries) RequeueStaleOutbox(ctx context.Context, staleAfterMs int64) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, requeueStaleOutbox, staleAfterMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDueOutbox = `-- name: SelectDueOutbox :many
select id, topic, payload, created_at, next_attempt_at, enqueued_at, dispatched_at, attempts, last_error, dead_at, updated_at from outbox
where dispatched_at is null
  and dead_at is null
  and enqueued_at is null
  and next_attempt_at <= now()
order by next_attempt_at, id
limit $1
for update skip locked
`

func (q *Queries) SelectDueOutbox(ctx context.Context, rowLimit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, selectDueOutbox, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
			&i.NextAttemptAt,
			&i.EnqueuedAt,
			&i.DispatchedAt,
			&i.Attempts,
			&i.LastError,
			&i.DeadAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
