// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const agentSelf = `-- name: AgentSelf :one
select u.full_name, u.email, e.student_code_snapshot
from users u join enrollments e on e.user_id = u.id and e.course_id = $1
where u.id = $2
`

type AgentSelfParams struct {
	CourseID uuid.UUID
	UserID   uuid.UUID
}

type AgentSelfRow struct {
	FullName            string
	Email               string
	StudentCodeSnapshot *string
}

// Danh tính CỦA CHÍNH người đang chat (từ trusted_context) để phân biệt "nhắc chính mình" với "hỏi hộ người khác".
func (q *Queries) AgentSelf(ctx context.Context, arg AgentSelfParams) (AgentSelfRow, error) {
	row := q.db.QueryRow(ctx, agentSelf, arg.CourseID, arg.UserID)
	var i AgentSelfRow
	err := row.Scan(&i.FullName, &i.Email, &i.StudentCodeSnapshot)
	return i, err
}

const countPIIEventsByCourse = `-- name: CountPIIEventsByCourse :many
select pii_type, action, sum(count)::bigint as total
from pii_events
where course_id = $1 and created_at >= $2
group by pii_type, action
order by pii_type, action
`

type CountPIIEventsByCourseParams struct {
	CourseID uuid.UUID
	Since    time.Time
}

type CountPIIEventsByCourseRow struct {
	PiiType PiiKind
	Action  PiiAction
	Total   int64
}

func (q *Queries) CountPIIEventsByCourse(ctx context.Context, arg CountPIIEventsByCourseParams) ([]CountPIIEventsByCourseRow, error) {
	rows, err := q.db.Query(ctx, countPIIEventsByCourse, arg.CourseID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPIIEventsByCourseRow{}
	for rows.Next() {
		var i CountPIIEventsByCourseRow
		if err := rows.Scan(&i.PiiType, &i.Action, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPIIEvent = `-- name: InsertPIIEvent :exec

insert into pii_events (course_id, session_id, user_id, channel, pii_type, count, action)
values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPIIEventParams struct {
	CourseID  uuid.UUID
	SessionID *uuid.UUID
	UserID    uuid.UUID
	Channel   ChatChannel
	PiiType   PiiKind
	Count     int32
	Action    PiiAction
}

// Sự kiện PII (US-P3-01): chỉ loại + số lượng, không văn bản. Chỉ INSERT (trigger chặn UPDATE/DELETE).
func (q *Queries) InsertPIIEvent(ctx context.Context, arg InsertPIIEventParams) error {
	_, err := q.db.Exec(ctx, insertPIIEvent,
		arg.CourseID,
		arg.SessionID,
		arg.UserID,
		arg.Channel,
		arg.PiiType,
		arg.Count,
		arg.Action,
	)
	return err
}

const privacyRoster = `-- name: PrivacyRoster :many
select u.full_name, e.student_code_snapshot
from enrollments e join users u on u.id = e.user_id
where e.course_id = $1 and e.role_in_course = 'STUDENT' and e.status = 'ACTIVE'
`

type PrivacyRosterRow struct {
	FullName            string
	StudentCodeSnapshot *string
}

// Từ điển PII của một lớp: chỉ sinh viên ACTIVE (giảng viên / TA không vào từ điển — Q8).
func (q *Queries) PrivacyRoster(ctx context.Context, courseID uuid.UUID) ([]PrivacyRosterRow, error) {
	rows, err := q.db.Query(ctx, privacyRoster, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrivacyRosterRow{}
	for rows.Next() {
		var i PrivacyRosterRow
		if err := rows.Scan(&i.FullName, &i.StudentCodeSnapshot); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
