// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rag.sql

package store

import (
	"context"

	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

const ragSearch = `-- name: RagSearch :many

WITH q AS (
    SELECT $2::vector AS v,
           CASE WHEN $3::text LIKE '%"%' THEN websearch_to_tsquery('simple', vn_fold(normalize($3::text, NFC)))
                ELSE vn_bigram_query($3::text) END AS t
),
vec AS (
    SELECT c.id, ROW_NUMBER() OVER (ORDER BY c.embedding <=> q.v) AS r
    FROM content_chunks c JOIN documents d ON d.id = c.document_id, q
    WHERE c.course_ids @> ARRAY[$1::uuid]
      AND d.status = 'READY' AND d.use_for_rag AND d.type <> 'ANSWER_KEY'
      AND ($4::bool = false OR d.visible_to_students)
      AND c.audience::text = ANY($5::text[]) AND c.embedding IS NOT NULL
      AND (cardinality($6::uuid[]) = 0 OR c.document_id = ANY($6::uuid[]))
    ORDER BY c.embedding <=> q.v
    LIMIT 40
),
kw AS (
    SELECT c.id, ROW_NUMBER() OVER (ORDER BY ts_rank_cd(c.tsv, q.t) DESC) AS r
    FROM content_chunks c JOIN documents d ON d.id = c.document_id, q
    WHERE c.course_ids @> ARRAY[$1::uuid]
      AND d.status = 'READY' AND d.use_for_rag AND d.type <> 'ANSWER_KEY'
      AND ($4::bool = false OR d.visible_to_students)
      AND c.audience::text = ANY($5::text[]) AND c.embedding IS NOT NULL
      AND (cardinality($6::uuid[]) = 0 OR c.document_id = ANY($6::uuid[]))
      AND c.tsv @@ q.t
    ORDER BY ts_rank_cd(c.tsv, q.t) DESC
    LIMIT 40
),
fused AS (
    SELECT x.id, SUM(1.0 / (60 + x.r)) AS s
    FROM (SELECT vec.id, vec.r FROM vec UNION ALL SELECT kw.id, kw.r FROM kw) x
    GROUP BY x.id ORDER BY s DESC LIMIT $7
)
SELECT c.id AS chunk_id, c.document_id, d.title, c.page_no, c.heading, c.text,
       (1 - (c.embedding <=> (SELECT v FROM q)))::float8 AS cosine, f.s::float8 AS score
FROM fused f JOIN content_chunks c ON c.id = f.id JOIN documents d ON d.id = c.document_id
WHERE c.course_ids @> ARRAY[$1::uuid]
ORDER BY f.s DESC
`

type RagSearchParams struct {
	CourseID    uuid.UUID
	Vec         pgvector.Vector
	QueryText   string
	StudentOnly bool
	Audiences   []string
	DocumentIds []uuid.UUID
	K           int32
}

type RagSearchRow struct {
	ChunkID    uuid.UUID
	DocumentID uuid.UUID
	Title      string
	PageNo     *int32
	Heading    *string
	Text       string
	Cosine     float64
	Score      float64
}

// Truy xuất tất định cho hỏi–đáp (US-P8-01, SRS FEAT-docs-calendar 4.3). MỌI điều kiện (lớp, READY, cờ, audience, không ANSWER_KEY) nằm TRONG từng nhánh,
// trước ORDER BY … LIMIT: lọc sau khi lấy láng giềng gần nhất sẽ trả thiếu khi 40 láng giềng đầu đều bị cấm.
// Không có truy vấn nào cho audience 'GRADING' (P7 tạo gói riêng).
func (q *Queries) RagSearch(ctx context.Context, arg RagSearchParams) ([]RagSearchRow, error) {
	rows, err := q.db.Query(ctx, ragSearch,
		arg.CourseID,
		arg.Vec,
		arg.QueryText,
		arg.StudentOnly,
		arg.Audiences,
		arg.DocumentIds,
		arg.K,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RagSearchRow{}
	for rows.Next() {
		var i RagSearchRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentID,
			&i.Title,
			&i.PageNo,
			&i.Heading,
			&i.Text,
			&i.Cosine,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
