// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: today.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const dismissCourseSetup = `-- name: DismissCourseSetup :execrows
update courses
set settings = jsonb_set(settings, '{setup}', coalesce(settings -> 'setup', '{}'::jsonb) || jsonb_build_object('dismissed_at', $1::text), true)
where id = $2 and (settings #>> '{setup,dismissed_at}') is null
`

type DismissCourseSetupParams struct {
	At string
	ID uuid.UUID
}

// Ghi mốc bỏ qua một lần; gọi lại không đổi mốc (idempotent). Số dòng = 1 khi VỪA ghi.
func (q *Queries) DismissCourseSetup(ctx context.Context, arg DismissCourseSetupParams) (int64, error) {
	result, err := q.db.Exec(ctx, dismissCourseSetup, arg.At, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existingSessionStarts = `-- name: ExistingSessionStarts :many
select starts_at from class_sessions where course_id = $1 and starts_at = any($2::text[]::timestamptz[])
`

type ExistingSessionStartsParams struct {
	CourseID uuid.UUID
	Starts   []string
}

// Giờ bắt đầu đã có trong lớp (chuỗi RFC 3339 → timestamptz) để bỏ qua buổi trùng.
func (q *Queries) ExistingSessionStarts(ctx context.Context, arg ExistingSessionStartsParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, existingSessionStarts, arg.CourseID, arg.Starts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var starts_at time.Time
		if err := rows.Scan(&starts_at); err != nil {
			return nil, err
		}
		items = append(items, starts_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :execrows
insert into class_sessions (course_id, session_no, starts_at, ends_at, room)
values ($1, $2, $3, $4, $5)
on conflict (course_id, starts_at) do nothing
`

type InsertSessionParams struct {
	CourseID  uuid.UUID
	SessionNo int32
	StartsAt  time.Time
	EndsAt    time.Time
	Room      *string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSession,
		arg.CourseID,
		arg.SessionNo,
		arg.StartsAt,
		arg.EndsAt,
		arg.Room,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSessions = `-- name: ListSessions :many
select id, session_no, starts_at, ends_at, room, topic
from class_sessions
where course_id = $1 and ($2::timestamptz is null or starts_at > $2::timestamptz)
order by starts_at
limit $3
`

type ListSessionsParams struct {
	CourseID uuid.UUID
	After    *time.Time
	Lim      int32
}

type ListSessionsRow struct {
	ID        uuid.UUID
	SessionNo int32
	StartsAt  time.Time
	EndsAt    time.Time
	Room      *string
	Topic     *string
}

// Theo starts_at tăng dần; con trỏ = starts_at của dòng cuối trang trước.
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.CourseID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionNo,
			&i.StartsAt,
			&i.EndsAt,
			&i.Room,
			&i.Topic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSessionNo = `-- name: MaxSessionNo :one

select coalesce(max(session_no), 0)::int from class_sessions where course_id = $1
`

// ===== Buổi học tối thiểu (US-P2-12) =====
func (q *Queries) MaxSessionNo(ctx context.Context, courseID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxSessionNo, courseID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const sessionNoInRange = `-- name: SessionNoInRange :one
select exists (select 1 from class_sessions where course_id = $1 and session_no between $2::int and $3::int) as taken
`

type SessionNoInRangeParams struct {
	CourseID uuid.UUID
	Lo       int32
	Hi       int32
}

func (q *Queries) SessionNoInRange(ctx context.Context, arg SessionNoInRangeParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionNoInRange, arg.CourseID, arg.Lo, arg.Hi)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const todayAdminCoursesNoTeacher = `-- name: TodayAdminCoursesNoTeacher :many
select c.id, c.class_code
from courses c
where c.status = 'ACTIVE'
  and not exists (select 1 from enrollments e where e.course_id = c.id and e.role_in_course = 'TEACHER' and e.status = 'ACTIVE')
order by c.class_code, c.id
limit 50
`

type TodayAdminCoursesNoTeacherRow struct {
	ID        uuid.UUID
	ClassCode string
}

func (q *Queries) TodayAdminCoursesNoTeacher(ctx context.Context) ([]TodayAdminCoursesNoTeacherRow, error) {
	rows, err := q.db.Query(ctx, todayAdminCoursesNoTeacher)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayAdminCoursesNoTeacherRow{}
	for rows.Next() {
		var i TodayAdminCoursesNoTeacherRow
		if err := rows.Scan(&i.ID, &i.ClassCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayAdminExpiredInvites = `-- name: TodayAdminExpiredInvites :one
select count(*)::int
from users u
where u.status = 'INVITED' and u.role in ('TEACHER', 'TA')
  and exists (select 1 from auth_tokens t where t.user_id = u.id and t.kind = 'INVITE' and t.used_at is null and t.revoked_at is null and t.expires_at < $1::timestamptz)
  and not exists (select 1 from auth_tokens t where t.user_id = u.id and t.kind = 'INVITE' and t.used_at is null and t.revoked_at is null and t.expires_at >= $1::timestamptz)
`

// Giảng viên / TA được mời, chưa dùng, mọi lời mời còn sống đã hết hạn.
func (q *Queries) TodayAdminExpiredInvites(ctx context.Context, now time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, todayAdminExpiredInvites, now)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const todayAdminIDs = `-- name: TodayAdminIDs :many
select id from users where role = 'ADMIN' and status = 'ACTIVE'
`

func (q *Queries) TodayAdminIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, todayAdminIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayAdminProviders = `-- name: TodayAdminProviders :many
select id, name, coalesce(last_test_ok, true)::boolean as ok from llm_providers where enabled order by name
`

type TodayAdminProvidersRow struct {
	ID   uuid.UUID
	Name string
	Ok   bool
}

// Nhà cung cấp AI đang bật: lỗi nếu lần kiểm gần nhất thất bại (mạch mở do Scheduler báo thêm).
func (q *Queries) TodayAdminProviders(ctx context.Context) ([]TodayAdminProvidersRow, error) {
	rows, err := q.db.Query(ctx, todayAdminProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayAdminProvidersRow{}
	for rows.Next() {
		var i TodayAdminProvidersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Ok); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayCourseMembers = `-- name: TodayCourseMembers :many
select user_id from enrollments where course_id = $1 and status in ('ACTIVE', 'PENDING')
`

// Mọi người đang ở / chờ trong lớp: bị ảnh hưởng khi lớp đổi hoặc lưu trữ.
func (q *Queries) TodayCourseMembers(ctx context.Context, courseID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, todayCourseMembers, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayCourseStaff = `-- name: TodayCourseStaff :many
select user_id from enrollments where course_id = $1 and role_in_course in ('TEACHER', 'TA') and status = 'ACTIVE'
`

// Người bị ảnh hưởng khi lớp đổi: giảng viên + TA đang hoạt động (xoá cache "Hôm nay").
func (q *Queries) TodayCourseStaff(ctx context.Context, courseID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, todayCourseStaff, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todaySessions = `-- name: TodaySessions :many
select s.course_id, c.class_code, c.name as course_name, s.session_no, s.starts_at, s.ends_at, s.room
from class_sessions s
join courses c on c.id = s.course_id
where s.course_id = any($1::text[]::uuid[]) and s.ends_at > $2::timestamptz and s.starts_at < $3::timestamptz
order by s.starts_at, s.id
limit 60
`

type TodaySessionsParams struct {
	CourseIds []string
	FromAt    time.Time
	ToAt      time.Time
}

type TodaySessionsRow struct {
	CourseID   uuid.UUID
	ClassCode  string
	CourseName string
	SessionNo  int32
	StartsAt   time.Time
	EndsAt     time.Time
	Room       *string
}

// Buổi học của các lớp trong khoảng [from, to) (chưa kết thúc trước from), cũ → mới.
func (q *Queries) TodaySessions(ctx context.Context, arg TodaySessionsParams) ([]TodaySessionsRow, error) {
	rows, err := q.db.Query(ctx, todaySessions, arg.CourseIds, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodaySessionsRow{}
	for rows.Next() {
		var i TodaySessionsRow
		if err := rows.Scan(
			&i.CourseID,
			&i.ClassCode,
			&i.CourseName,
			&i.SessionNo,
			&i.StartsAt,
			&i.EndsAt,
			&i.Room,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todaySetup = `-- name: TodaySetup :many
select c.id as course_id,
       (exists (select 1 from enrollments e where e.course_id = c.id and e.role_in_course = 'STUDENT' and e.status in ('ACTIVE', 'PENDING')))::boolean as share_code,
       (exists (select 1 from documents d where d.course_id = c.id and d.type = 'COURSE_POLICY' and d.status <> 'FAILED'))::boolean as policy,
       (exists (select 1 from class_sessions s where s.course_id = c.id))::boolean as sessions,
       ((exists (select 1 from documents d where d.course_id = c.id and d.type <> 'COURSE_POLICY' and d.status <> 'FAILED')
        or exists (select 1 from document_courses dc join documents d on d.id = dc.document_id where dc.course_id = c.id and d.status <> 'FAILED')))::boolean as documents,
       coalesce(c.settings #>> '{setup,dismissed_at}', '')::text as dismissed
from courses c
where c.id = any($1::text[]::uuid[])
`

type TodaySetupRow struct {
	CourseID  uuid.UUID
	ShareCode bool
	Policy    bool
	Sessions  bool
	Documents bool
	Dismissed string
}

// Bốn bước "Thiết lập lớp mới" tự tick theo dữ liệu (SRS 4.7); dismissed = mốc giảng viên bỏ qua.
func (q *Queries) TodaySetup(ctx context.Context, courseIds []string) ([]TodaySetupRow, error) {
	rows, err := q.db.Query(ctx, todaySetup, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodaySetupRow{}
	for rows.Next() {
		var i TodaySetupRow
		if err := rows.Scan(
			&i.CourseID,
			&i.ShareCode,
			&i.Policy,
			&i.Sessions,
			&i.Documents,
			&i.Dismissed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayStaffPending = `-- name: TodayStaffPending :many
select c.course_id::uuid as course_id,
       coalesce(e.pending, 0)::int as pending,
       coalesce(e.oldest, 'epoch'::timestamptz)::timestamptz as oldest,
       coalesce(e.mismatch, 0)::int as mismatch,
       coalesce(e.mismatch_oldest, 'epoch'::timestamptz)::timestamptz as mismatch_oldest,
       coalesce(q.pending, 0)::int as questions,
       coalesce(q.oldest, 'epoch'::timestamptz)::timestamptz as questions_oldest,
       coalesce(s.exams, '[]'::jsonb)::jsonb as similarity,
       coalesce(w.exams, '[]'::jsonb)::jsonb as exam_work
from unnest($1::text[]::uuid[]) as c(course_id)
left join (
    select course_id,
           (count(*) filter (where warning is null)) as pending,
           min(status_changed_at) filter (where warning is null) as oldest,
           (count(*) filter (where warning = 'EMAIL_MISMATCH')) as mismatch,
           min(status_changed_at) filter (where warning = 'EMAIL_MISMATCH') as mismatch_oldest
    from enrollments
    where course_id = any($1::text[]::uuid[]) and role_in_course = 'STUDENT' and status = 'PENDING'
    group by course_id
) e on e.course_id = c.course_id
left join (
    select course_id, count(*) as pending, min(created_at) as oldest
    from question_bank
    where course_id = any($1::text[]::uuid[]) and review_status = 'PENDING' and archived_at is null
    group by course_id
) q on q.course_id = c.course_id
left join (
    -- US-PE-07: mỗi bài thi có cặp độ giống gắn cờ còn NEW ở bản chạy MỚI NHẤT (chỉ Giảng viên dùng); GỘP vào cùng truy vấn
    select r.course_id, jsonb_agg(jsonb_build_object('exam_id', r.exam_id, 'title', ex.title, 'n', r.n, 'oldest', r.oldest) order by r.oldest) as exams
    from (
        select sr.course_id, sr.exam_id, count(*) as n, min(sr.created_at) as oldest
        from similarity_reports sr
        where sr.course_id = any($1::text[]::uuid[]) and sr.flagged and sr.review_state = 'NEW'
          and sr.run_id = (select l.run_id from similarity_reports l where l.course_id = sr.course_id and l.exam_id = sr.exam_id order by l.created_at desc, l.id desc limit 1)
        group by sr.course_id, sr.exam_id
    ) r
    join exams ex on ex.course_id = r.course_id and ex.id = r.exam_id
    group by r.course_id
) s on s.course_id = c.course_id
left join (
    -- US-PE-08: việc của Staff về bài đã đóng / công bố (lượt chấm lỗi, hoãn công bố, phúc khảo chờ); bài cũ hơn 120 ngày thôi làm việc của hôm nay.
    select e.course_id, jsonb_agg(jsonb_build_object('exam_id', e.id, 'title', e.title, 'hold', e.publish_hold,
        'errors', (select count(distinct a.id) from exam_attempts a join code_submissions cs on cs.course_id = a.course_id and cs.attempt_id = a.id and cs.kind = 'SUBMIT' and cs.status = 'ERROR'
                    where a.course_id = e.course_id and a.exam_id = e.id),
        'ungraded', (select count(*) from exam_attempts a where a.course_id = e.course_id and a.exam_id = e.id and a.status <> 'GRADED'),
        'appeals', (select count(*) from exam_appeals p where p.course_id = e.course_id and p.exam_id = e.id and p.status = 'OPEN'),
        'appeal_oldest', (select min(p.created_at) from exam_appeals p where p.course_id = e.course_id and p.exam_id = e.id and p.status = 'OPEN'))) as exams
    from exams e
    where e.course_id = any($1::text[]::uuid[]) and e.status in ('CLOSED', 'PUBLISHED') and e.closes_at > now() - interval '120 days'
    group by e.course_id
) w on w.course_id = c.course_id
`

type TodayStaffPendingRow struct {
	CourseID        uuid.UUID
	Pending         int32
	Oldest          time.Time
	Mismatch        int32
	MismatchOldest  time.Time
	Questions       int32
	QuestionsOldest time.Time
	Similarity      json.RawMessage
	ExamWork        json.RawMessage
}

// (epoch = không có.) Mỗi lớp: yêu cầu vào lớp chờ duyệt (không tính chờ xác minh email của roster), cũ nhất, số hàng email chưa khớp MSSV,
// và (US-PE-03) số câu hỏi PENDING chưa lưu trữ cùng câu cũ nhất — GỘP vào MỘT truy vấn để Hôm nay của Staff giữ ngân sách ≤ 5 truy vấn.
func (q *Queries) TodayStaffPending(ctx context.Context, courseIds []string) ([]TodayStaffPendingRow, error) {
	rows, err := q.db.Query(ctx, todayStaffPending, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayStaffPendingRow{}
	for rows.Next() {
		var i TodayStaffPendingRow
		if err := rows.Scan(
			&i.CourseID,
			&i.Pending,
			&i.Oldest,
			&i.Mismatch,
			&i.MismatchOldest,
			&i.Questions,
			&i.QuestionsOldest,
			&i.Similarity,
			&i.ExamWork,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayUserCourses = `-- name: TodayUserCourses :many
select course_id from enrollments where user_id = $1 and status in ('ACTIVE', 'PENDING')
`

func (q *Queries) TodayUserCourses(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, todayUserCourses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var course_id uuid.UUID
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayViewer = `-- name: TodayViewer :many

select u.email, (u.email_verified_at is not null)::boolean as verified,
       e.course_id, c.class_code, e.role_in_course, e.status, e.status_changed_at
from users u
left join enrollments e on e.user_id = u.id and e.status in ('ACTIVE', 'PENDING')
left join courses c on c.id = e.course_id and c.status = 'ACTIVE'
where u.id = $1
`

type TodayViewerRow struct {
	Email           string
	Verified        bool
	CourseID        *uuid.UUID
	ClassCode       *string
	RoleInCourse    *EnrollmentRole
	Status          *EnrollmentStatus
	StatusChangedAt *time.Time
}

// "Hôm nay" (US-P2-11, SRS 4.7). Mỗi truy vấn là TỔNG HỢP cho cả tập lớp của người xem (không N+1).
// Người xem và ghi danh ACTIVE / PENDING của chính họ trong lớp còn mở: MỘT truy vấn dựng Viewer (SRS 4.7 "ngân sách truy vấn").
// Người chưa có lớp ⇒ đúng một dòng với course_id NULL.
func (q *Queries) TodayViewer(ctx context.Context, userID uuid.UUID) ([]TodayViewerRow, error) {
	rows, err := q.db.Query(ctx, todayViewer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayViewerRow{}
	for rows.Next() {
		var i TodayViewerRow
		if err := rows.Scan(
			&i.Email,
			&i.Verified,
			&i.CourseID,
			&i.ClassCode,
			&i.RoleInCourse,
			&i.Status,
			&i.StatusChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
