// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: today.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const dismissCourseSetup = `-- name: DismissCourseSetup :execrows
update courses
set settings = jsonb_set(settings, '{setup}', coalesce(settings -> 'setup', '{}'::jsonb) || jsonb_build_object('dismissed_at', $1::text), true)
where id = $2 and (settings #>> '{setup,dismissed_at}') is null
`

type DismissCourseSetupParams struct {
	At string
	ID uuid.UUID
}

// Ghi mốc bỏ qua một lần; gọi lại không đổi mốc (idempotent). Số dòng = 1 khi VỪA ghi.
func (q *Queries) DismissCourseSetup(ctx context.Context, arg DismissCourseSetupParams) (int64, error) {
	result, err := q.db.Exec(ctx, dismissCourseSetup, arg.At, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const todayAdminCoursesNoTeacher = `-- name: TodayAdminCoursesNoTeacher :many
select c.id, c.class_code
from courses c
where c.status = 'ACTIVE'
  and not exists (select 1 from enrollments e where e.course_id = c.id and e.role_in_course = 'TEACHER' and e.status = 'ACTIVE')
order by c.class_code, c.id
limit 50
`

type TodayAdminCoursesNoTeacherRow struct {
	ID        uuid.UUID
	ClassCode string
}

func (q *Queries) TodayAdminCoursesNoTeacher(ctx context.Context) ([]TodayAdminCoursesNoTeacherRow, error) {
	rows, err := q.db.Query(ctx, todayAdminCoursesNoTeacher)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayAdminCoursesNoTeacherRow{}
	for rows.Next() {
		var i TodayAdminCoursesNoTeacherRow
		if err := rows.Scan(&i.ID, &i.ClassCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayAdminExpiredInvites = `-- name: TodayAdminExpiredInvites :one
select count(*)::int
from users u
where u.status = 'INVITED' and u.role in ('TEACHER', 'TA')
  and exists (select 1 from auth_tokens t where t.user_id = u.id and t.kind = 'INVITE' and t.used_at is null and t.revoked_at is null and t.expires_at < $1::timestamptz)
  and not exists (select 1 from auth_tokens t where t.user_id = u.id and t.kind = 'INVITE' and t.used_at is null and t.revoked_at is null and t.expires_at >= $1::timestamptz)
`

// Giảng viên / TA được mời, chưa dùng, mọi lời mời còn sống đã hết hạn.
func (q *Queries) TodayAdminExpiredInvites(ctx context.Context, now time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, todayAdminExpiredInvites, now)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const todayAdminIDs = `-- name: TodayAdminIDs :many
select id from users where role = 'ADMIN' and status = 'ACTIVE'
`

func (q *Queries) TodayAdminIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, todayAdminIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayAdminProviders = `-- name: TodayAdminProviders :many
select id, name, coalesce(last_test_ok, true)::boolean as ok from llm_providers where enabled order by name
`

type TodayAdminProvidersRow struct {
	ID   uuid.UUID
	Name string
	Ok   bool
}

// Nhà cung cấp AI đang bật: lỗi nếu lần kiểm gần nhất thất bại (mạch mở do Scheduler báo thêm).
func (q *Queries) TodayAdminProviders(ctx context.Context) ([]TodayAdminProvidersRow, error) {
	rows, err := q.db.Query(ctx, todayAdminProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayAdminProvidersRow{}
	for rows.Next() {
		var i TodayAdminProvidersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Ok); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayCourseMembers = `-- name: TodayCourseMembers :many
select user_id from enrollments where course_id = $1 and status in ('ACTIVE', 'PENDING')
`

// Mọi người đang ở / chờ trong lớp: bị ảnh hưởng khi lớp đổi hoặc lưu trữ.
func (q *Queries) TodayCourseMembers(ctx context.Context, courseID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, todayCourseMembers, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayCourseStaff = `-- name: TodayCourseStaff :many
select user_id from enrollments where course_id = $1 and role_in_course in ('TEACHER', 'TA') and status = 'ACTIVE'
`

// Người bị ảnh hưởng khi lớp đổi: giảng viên + TA đang hoạt động (xoá cache "Hôm nay").
func (q *Queries) TodayCourseStaff(ctx context.Context, courseID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, todayCourseStaff, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todaySessions = `-- name: TodaySessions :many
select s.course_id, c.class_code, c.name as course_name, s.session_no, s.starts_at, s.ends_at, s.room
from class_sessions s
join courses c on c.id = s.course_id
where s.course_id = any($1::text[]::uuid[]) and s.ends_at > $2::timestamptz and s.starts_at < $3::timestamptz
order by s.starts_at, s.id
limit 60
`

type TodaySessionsParams struct {
	CourseIds []string
	FromAt    time.Time
	ToAt      time.Time
}

type TodaySessionsRow struct {
	CourseID   uuid.UUID
	ClassCode  string
	CourseName string
	SessionNo  int32
	StartsAt   time.Time
	EndsAt     time.Time
	Room       *string
}

// Buổi học của các lớp trong khoảng [from, to) (chưa kết thúc trước from), cũ → mới.
func (q *Queries) TodaySessions(ctx context.Context, arg TodaySessionsParams) ([]TodaySessionsRow, error) {
	rows, err := q.db.Query(ctx, todaySessions, arg.CourseIds, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodaySessionsRow{}
	for rows.Next() {
		var i TodaySessionsRow
		if err := rows.Scan(
			&i.CourseID,
			&i.ClassCode,
			&i.CourseName,
			&i.SessionNo,
			&i.StartsAt,
			&i.EndsAt,
			&i.Room,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todaySetup = `-- name: TodaySetup :many
select c.id as course_id,
       (exists (select 1 from enrollments e where e.course_id = c.id and e.role_in_course = 'STUDENT' and e.status in ('ACTIVE', 'PENDING')))::boolean as share_code,
       (exists (select 1 from documents d where d.course_id = c.id and d.type = 'COURSE_POLICY' and d.status <> 'FAILED'))::boolean as policy,
       (exists (select 1 from class_sessions s where s.course_id = c.id))::boolean as sessions,
       ((exists (select 1 from documents d where d.course_id = c.id and d.type <> 'COURSE_POLICY' and d.status <> 'FAILED')
        or exists (select 1 from document_courses dc join documents d on d.id = dc.document_id where dc.course_id = c.id and d.status <> 'FAILED')))::boolean as documents,
       coalesce(c.settings #>> '{setup,dismissed_at}', '')::text as dismissed
from courses c
where c.id = any($1::text[]::uuid[])
`

type TodaySetupRow struct {
	CourseID  uuid.UUID
	ShareCode bool
	Policy    bool
	Sessions  bool
	Documents bool
	Dismissed string
}

// Bốn bước "Thiết lập lớp mới" tự tick theo dữ liệu (SRS 4.7); dismissed = mốc giảng viên bỏ qua.
func (q *Queries) TodaySetup(ctx context.Context, courseIds []string) ([]TodaySetupRow, error) {
	rows, err := q.db.Query(ctx, todaySetup, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodaySetupRow{}
	for rows.Next() {
		var i TodaySetupRow
		if err := rows.Scan(
			&i.CourseID,
			&i.ShareCode,
			&i.Policy,
			&i.Sessions,
			&i.Documents,
			&i.Dismissed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayStaffPending = `-- name: TodayStaffPending :many
select e.course_id,
       (count(*) filter (where e.warning is null))::int as pending,
       coalesce(min(e.status_changed_at) filter (where e.warning is null), 'epoch'::timestamptz)::timestamptz as oldest,
       (count(*) filter (where e.warning = 'EMAIL_MISMATCH'))::int as mismatch,
       coalesce(min(e.status_changed_at) filter (where e.warning = 'EMAIL_MISMATCH'), 'epoch'::timestamptz)::timestamptz as mismatch_oldest
from enrollments e
where e.course_id = any($1::text[]::uuid[]) and e.role_in_course = 'STUDENT' and e.status = 'PENDING'
group by e.course_id
`

type TodayStaffPendingRow struct {
	CourseID       uuid.UUID
	Pending        int32
	Oldest         time.Time
	Mismatch       int32
	MismatchOldest time.Time
}

// (epoch = không có.) Mỗi lớp: yêu cầu vào lớp chờ duyệt (không tính chờ xác minh email của roster), cũ nhất, và số hàng email chưa khớp MSSV.
func (q *Queries) TodayStaffPending(ctx context.Context, courseIds []string) ([]TodayStaffPendingRow, error) {
	rows, err := q.db.Query(ctx, todayStaffPending, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayStaffPendingRow{}
	for rows.Next() {
		var i TodayStaffPendingRow
		if err := rows.Scan(
			&i.CourseID,
			&i.Pending,
			&i.Oldest,
			&i.Mismatch,
			&i.MismatchOldest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayUserCourses = `-- name: TodayUserCourses :many
select course_id from enrollments where user_id = $1 and status in ('ACTIVE', 'PENDING')
`

func (q *Queries) TodayUserCourses(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, todayUserCourses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var course_id uuid.UUID
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayViewer = `-- name: TodayViewer :many

select u.email, (u.email_verified_at is not null)::boolean as verified,
       e.course_id, c.class_code, e.role_in_course, e.status, e.status_changed_at
from users u
left join enrollments e on e.user_id = u.id and e.status in ('ACTIVE', 'PENDING')
left join courses c on c.id = e.course_id and c.status = 'ACTIVE'
where u.id = $1
`

type TodayViewerRow struct {
	Email           string
	Verified        bool
	CourseID        *uuid.UUID
	ClassCode       *string
	RoleInCourse    *EnrollmentRole
	Status          *EnrollmentStatus
	StatusChangedAt *time.Time
}

// "Hôm nay" (US-P2-11, SRS 4.7). Mỗi truy vấn là TỔNG HỢP cho cả tập lớp của người xem (không N+1).
// Người xem và ghi danh ACTIVE / PENDING của chính họ trong lớp còn mở: MỘT truy vấn dựng Viewer (SRS 4.7 "ngân sách truy vấn").
// Người chưa có lớp ⇒ đúng một dòng với course_id NULL.
func (q *Queries) TodayViewer(ctx context.Context, userID uuid.UUID) ([]TodayViewerRow, error) {
	rows, err := q.db.Query(ctx, todayViewer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayViewerRow{}
	for rows.Next() {
		var i TodayViewerRow
		if err := rows.Scan(
			&i.Email,
			&i.Verified,
			&i.CourseID,
			&i.ClassCode,
			&i.RoleInCourse,
			&i.Status,
			&i.StatusChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
