// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
select id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one

insert into users (email, full_name, role, status, password_hash, student_code)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
returning id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at
`

type InsertUserParams struct {
	Email        string
	FullName     string
	Role         UserRole
	Status       UserStatus
	PasswordHash *string
	StudentCode  *string
}

// Bảng `users` ở PG chỉ dùng cho test và các phase sau (không endpoint nghiệp vụ nào ghi).
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.Status,
		arg.PasswordHash,
		arg.StudentCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchLastLogin = `-- name: TouchLastLogin :exec
update users set last_login_at = $1::timestamptz where id = $2
`

type TouchLastLoginParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) TouchLastLogin(ctx context.Context, arg TouchLastLoginParams) error {
	_, err := q.db.Exec(ctx, touchLastLogin, arg.Now, arg.ID)
	return err
}
