// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_admin.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activateInvitedUser = `-- name: ActivateInvitedUser :one
update users
set password_hash = $1, status = 'ACTIVE', email_verified_at = coalesce(email_verified_at, $2::timestamptz), version = version + 1
where id = $3 and status = 'INVITED'
returning id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at
`

type ActivateInvitedUserParams struct {
	PasswordHash *string
	Now          time.Time
	ID           uuid.UUID
}

// Nhận lời mời: đặt mật khẩu, ACTIVE, email coi như đã xác minh (thư mời tới đúng hộp thư của họ).
func (q *Queries) ActivateInvitedUser(ctx context.Context, arg ActivateInvitedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, activateInvitedUser, arg.PasswordHash, arg.Now, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOtherActiveAdmins = `-- name: CountOtherActiveAdmins :one
select count(*) from users where role = 'ADMIN' and status = 'ACTIVE' and id <> $1
`

func (q *Queries) CountOtherActiveAdmins(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherActiveAdmins, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureUserSettings = `-- name: EnsureUserSettings :one
with ins as (
    insert into user_settings (user_id) values ($1) on conflict (user_id) do nothing returning user_id, notify_ticket_by_mail, notify_answer_by_mail, remind_deadline_by_mail, preferences, version, created_at, updated_at
)
select user_id, notify_ticket_by_mail, notify_answer_by_mail, remind_deadline_by_mail, preferences, version, created_at, updated_at from ins
union all
select user_id, notify_ticket_by_mail, notify_answer_by_mail, remind_deadline_by_mail, preferences, version, created_at, updated_at from user_settings where user_id = $1 and not exists (select 1 from ins)
`

type EnsureUserSettingsRow struct {
	UserID               uuid.UUID
	NotifyTicketByMail   bool
	NotifyAnswerByMail   bool
	RemindDeadlineByMail bool
	Preferences          json.RawMessage
	Version              int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// Tạo lười khi đọc lần đầu; luôn trả dòng hiện có.
func (q *Queries) EnsureUserSettings(ctx context.Context, userID uuid.UUID) (EnsureUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, ensureUserSettings, userID)
	var i EnsureUserSettingsRow
	err := row.Scan(
		&i.UserID,
		&i.NotifyTicketByMail,
		&i.NotifyAnswerByMail,
		&i.RemindDeadlineByMail,
		&i.Preferences,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAdminUser = `-- name: InsertAdminUser :one
insert into users (email, full_name, role, status, password_hash, email_verified_at)
values ($1, $2, 'ADMIN', 'ACTIVE', $3, $4::timestamptz)
on conflict (email) do nothing
returning id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at
`

type InsertAdminUserParams struct {
	Email        string
	FullName     string
	PasswordHash *string
	Now          time.Time
}

// `gateway admin create`: ADMIN ACTIVE đã xác minh; idempotent theo email.
func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertAdminUser,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.Now,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInvitedUser = `-- name: InsertInvitedUser :one

insert into users (email, full_name, role, status)
values ($1, $2, $3, 'INVITED')
on conflict (email) do nothing
returning id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at
`

type InsertInvitedUserParams struct {
	Email    string
	FullName string
	Role     UserRole
}

// Quản trị người dùng (FEAT-account-security US-P2-06). Danh sách: một truy vấn, khoá phân trang (created_at DESC, id DESC).
// Lời mời giảng viên / trợ giảng: chưa có mật khẩu. Trùng email ⇒ không dòng (handler trả 409 CONFLICT).
func (q *Queries) InsertInvitedUser(ctx context.Context, arg InsertInvitedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertInvitedUser, arg.Email, arg.FullName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
select id, email, full_name, role, status, last_login_at, version, created_at
from users
where ($1::user_role is null or role = $1::user_role)
  and ($2::user_status is null or status = $2::user_status)
  and ($3::text is null
       or vn_fold(full_name) like $3::text escape '\'
       or email like $4::text escape '\')
  and ($5::timestamptz is null or (created_at, id) < ($5::timestamptz, $6::uuid))
order by created_at desc, id desc
limit $7
`

type ListUsersAdminParams struct {
	Role      *UserRole
	Status    *UserStatus
	NameLike  *string
	EmailLike *string
	CurAt     *time.Time
	CurID     *uuid.UUID
	Lim       int32
}

type ListUsersAdminRow struct {
	ID          uuid.UUID
	Email       string
	FullName    string
	Role        UserRole
	Status      UserStatus
	LastLoginAt *time.Time
	Version     int32
	CreatedAt   time.Time
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin,
		arg.Role,
		arg.Status,
		arg.NameLike,
		arg.EmailLike,
		arg.CurAt,
		arg.CurID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersAdminRow{}
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForUpdate = `-- name: LockUserForUpdate :one
select id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at from users where id = $1 for update
`

func (q *Queries) LockUserForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, lockUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one

update users
set full_name = coalesce($1, full_name),
    student_code = case when $2::bool then $3 else student_code end,
    version = version + 1
where id = $4 and version = $5
returning id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at
`

type UpdateProfileParams struct {
	FullName       *string
	SetStudentCode bool
	StudentCode    *string
	ID             uuid.UUID
	Version        int32
}

// Hồ sơ và tuỳ chọn của chính mình (US-P2-07). `student_code` chỉ được GHI ở đây; không điều kiện nối lớp nào dùng nó (SRS 4.2.5).
// Khoá lạc quan theo version. Không dòng ⇒ sai version (handler đọc bản hiện hành để trả 409).
func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.FullName,
		arg.SetStudentCode,
		arg.StudentCode,
		arg.ID,
		arg.Version,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
update users
set full_name = coalesce($1, full_name),
    role = coalesce($2::user_role, role),
    status = coalesce($3::user_status, status),
    version = version + 1
where id = $4 and version = $5
returning id, email, password_hash, full_name, role, student_code, email_verified_at, failed_logins, locked_until, status, ics_token, tracking_notice_ack_at, last_login_at, version, created_at, updated_at
`

type UpdateUserAdminParams struct {
	FullName *string
	Role     *UserRole
	Status   *UserStatus
	ID       uuid.UUID
	Version  int32
}

// Khoá lạc quan theo version. Không dòng ⇒ sai version (người gọi đã khoá hàng nên người dùng chắc chắn còn).
func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAdmin,
		arg.FullName,
		arg.Role,
		arg.Status,
		arg.ID,
		arg.Version,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentCode,
		&i.EmailVerifiedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.Status,
		&i.IcsToken,
		&i.TrackingNoticeAckAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
update user_settings
set notify_ticket_by_mail = coalesce($1, notify_ticket_by_mail),
    notify_answer_by_mail = coalesce($2, notify_answer_by_mail),
    remind_deadline_by_mail = coalesce($3, remind_deadline_by_mail),
    -- US-P8-03: gộp từng khoá của preferences.reminders (khoá vắng = giữ nguyên)
    preferences = case when $4::jsonb is null then preferences
                  else jsonb_set(preferences, '{reminders}', coalesce(preferences->'reminders', '{}'::jsonb) || $4::jsonb) end,
    version = version + 1
where user_id = $5 and version = $6
returning user_id, notify_ticket_by_mail, notify_answer_by_mail, remind_deadline_by_mail, preferences, version, created_at, updated_at
`

type UpdateUserSettingsParams struct {
	NotifyTicketByMail   *bool
	NotifyAnswerByMail   *bool
	RemindDeadlineByMail *bool
	Reminders            json.RawMessage
	UserID               uuid.UUID
	Version              int32
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.NotifyTicketByMail,
		arg.NotifyAnswerByMail,
		arg.RemindDeadlineByMail,
		arg.Reminders,
		arg.UserID,
		arg.Version,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.NotifyTicketByMail,
		&i.NotifyAnswerByMail,
		&i.RemindDeadlineByMail,
		&i.Preferences,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
